### ISSUE TITLE
BSP: Incorrect range end position in problem reporter

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#1011]
_Originally posted by @ckipp01 in https://github.com/lihaoyi/mill/issues/999#issuecomment-733120085_

<img width="671" alt="Screenshot 2020-11-24 at 18 02 37" src="https://user-images.githubusercontent.com/13974112/100128333-721b1080-2e80-11eb-9f6f-3dd58e5b6f18.png">

One other thing that I do notice though is that the diagnostic from Mill is as follows:
```
"diagnostics": [
    {
      "range": {
        "start": {
          "line": 8,
          "character": 15
        },
        "end": {
          "line": 8,
          "character": 15
        }
      },
      "severity": 1,
      "source": "compiler from mill",
      "message": "type mismatch;\n found   : String(\"hi\")\n required: Int"
    }
  ],
```
Whereas both with sbt and with Bloop it's:

```
"diagnostics": [
    {
      "range": {
        "start": {
          "line": 8,
          "character": 15
        },
        "end": {
          "line": 8,
          "character": 19
        }
      },
      "severity": 1,
      "source": "sbt",
      "message": "type mismatch;\n found   : String(\"hi\")\n required: Int"
    }
  ]
```

It still seems to work fine (I think there is some magic on the LSP client side) to maybe highlight the full symbol, but it'd be better to correctly capture the entire range and not return 15 for both start character and end character.

If it helps at all, here is the code sbt uses to get the range from the `Problem`.

https://github.com/sbt/sbt/blob/13b09bcd8fa0fde86aa4f4f8d7089fcb18e345c6/main/src/main/scala/sbt/internal/server/BuildServerReporter.scala#L133-L159

**Comment by ckipp01** [comment]
So I didn't really realize this at the time, but this actually shouldn't be an issue for Metals. Metals actually takes that diagnostic and expands the range to the token in order to keep diagnostics alongside sytnax errors when you type. So when you look at the `bsp.trace.log` file it may look off, but in the `lsp.trace.log` file, it's right. This popped up during a conversation on matrix about IntelliJ and Bloop seeing the same behavior.

**Comment by lefou** [comment]
So this isn't really an issue anymore?

**Comment by ckipp01** [comment]
Correct. At least in the LSP world, if you look at the expanded range that LSP will report to the client, it will be correct. Metals actually has the ability to expand that point to the full symbol. I sort of misunderstood this in the beginning until the IntelliJ folks mentioned it as well. I believe this can be closed now.

**Comment by lefou** [comment]
Great, thanks for clarifying.
