### ISSUE TITLE
[BSP] buildTarget/javacOptions not found

### ISSUE THREAD

**Issue by Iltotore** [com-lihaoyi/mill#1091]
Hello, my issue is similar to #1024. It should be fixed in #1025 but the problem sill occurs in 0.9.4 on Windows 10.

**Comment by lefou** [comment]
Can you explain, how to reproduce this? Which BSP client? What steps?

**Comment by Iltotore** [comment]
I just run `mill mill.bsp.BSP/Install`, and created in my buildscript an empty `main` module in 2.13.4. When I import the project in idea using BSP, it hangs on javacOptions, so I tried using the Bloop contrib module and I got the same issue as mentionned in #1024

**Comment by lefou** [comment]
Should be fixed in main as part of my refactoring #1536. 

@Iltotore Can you verify it is fixed in main?

**Comment by Iltotore** [comment]
@lefou I checked it using the last `main` commit (`e972e1`). Your refactoring works fine using my old BSP `mill.json` configuration:
```scala
{
  "name": "mill-bsp",
  "argv": [
    "C:\\Users\\rapha\\scoop\\apps\\mill\\current\\mill.bat",
    "-i",
    "--disable-ticker",
    "--color",
    "false",
    "mill.bsp.BSP/start"
  ],
  "millVersion": "0.9.9",
  "bspVersion": "2.0.0",
  "languages": [
    "scala",
    "java"
  ]
}
```

But it doesn't using the new `mill-bsp.json` configuration generated using `mill.bsp.BSP/install`:
```scala
{
  "name": "mill-bsp",
  "argv": [
    "C:\\Users\\rapha\\scoop\\apps\\mill\\current\\mill.bat",
    "--bsp",
    "--disable-ticker",
    "--color",
    "false",
    "--jobs",
    "1"
  ],
  "millVersion": "0.10.0-M3-114-e972e1",
  "bspVersion": "2.0.0",
  "languages": [
    "scala",
    "java"
  ]
}
```

giving this error:
```
Exception in thread "Thread-2" java.lang.RuntimeException: java.io.IOException: WriteFile() failed: 233

	at mill.main.client.InputPumper.run(InputPumper.java:34)

	at java.lang.Thread.run(Thread.java:748)

Caused by: java.io.IOException: WriteFile() failed: 233

	at org.scalasbt.ipcsocket.Win32NamedPipeSocket$Win32NamedPipeSocketOutputStream.write(Win32NamedPipeSocket.java:198)

	at mill.main.client.InputPumper.run(InputPumper.java:28)

	... 1 more
```

**Comment by lefou** [comment]
Integesting. Thanks for checking!

This could be related to your `"C:\\Users\\rapha\\scoop\\apps\\mill\\current\\mill.bat"`. Is this the mill-assembly but named as `mill.bat` or some other wrapper script? I probably forgot to adapt adapt the Windows-batch-script-part of our assembly to recognize the `--bsp` switch.

**Comment by lefou** [comment]
Yes, it's a Windows-bug in mill. I opened a PR: https://github.com/com-lihaoyi/mill/pull/1557

**Comment by Iltotore** [comment]
It now works like a charm. 
> Is this the mill-assembly but named as mill.bat or some other wrapper script?

You probably know the answer now but yes, it was the mill assembly generated by the `ci/publish-local.sh` script
