### ISSUE TITLE
Support Scala 3 on ScalaJSModule

### ISSUE THREAD

**Issue by lolgab** [com-lihaoyi/mill#1103]
Currently `ScalaJSModule` doesn't support Scala 3.

The support should be something along the lines of what is done in the [Scala.js sbt plugin](https://github.com/scala-js/scala-js/blob/7920ac21e58fe4022fb0d04c9d450738cd3178e9/sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala#L685)

**Comment by lefou** [comment]
FYI, technically, the only thing we need to do is to adapt the Scala libraries. See this Gitter thread from Sept. 2020: https://gitter.im/lihaoyi/mill?at=5f52a9d759ac794e02ea6b82

I'm quoting the ad-hoc solution:

```scala
override def mapDependencies = T.task{ d: coursier.Dependency =>
  d match {
    case d if d.module.name.value == "scalajs-library_0.27" =>
      d.withModule(d.module.withName(coursier.core.ModuleName("scalajs-library_2.13")))
    case d if d.module.name.value == "scalajs-compiler_0.27.0-RC1" =>
      d.withModule(d.module.withName(coursier.core.ModuleName("scalajs-compiler_2.13.3")))
    case x => x
  }
}
```

**Comment by megri** [comment]
Artifacts on the 3.0.0-x branch requires slightly different intervention, as the scalajs compiler is builtin and enabled by a compiler flag. I had some success with this setup but I'm not sure if it's a 100 % correct:

```scala
trait Scala3JSModule extends ScalaJSModule {
  override def scalacPluginIvyDeps = T { Seq() }

  def scalacOptions = Seq("-scalajs")

  override def scalaLibraryIvyDeps = T {
    Agg(
      ivy"org.scala-lang:scala3-library_sjs1_${scalaVersion()}:${scalaVersion()}",
      ivy"org.scala-js:scalajs-test-bridge_2.13:${scalaJSVersion()}"
    )
  }
}

object myJSModule extends Scala3JSModule {
  // …
}
```

**Comment by bbarker** [comment]
> Artifacts on the 3.0.0-x branch requires slightly different intervention, as the scalajs compiler is builtin and enabled by a compiler flag. I had some success with this setup but I'm not sure if it's a 100 % correct:
> 
> ```scala
> trait Scala3JSModule extends ScalaJSModule {
>   override def scalacPluginIvyDeps = T { Seq() }
> 
>   def scalacOptions = Seq("-scalajs")
> 
>   override def scalaLibraryIvyDeps = T {
>     Agg(
>       ivy"org.scala-lang:scala3-library_sjs1_${scalaVersion()}:${scalaVersion()}",
>       ivy"org.scala-js:scalajs-test-bridge_2.13:${scalaJSVersion()}"
>     )
>   }
> }
> 
> object myJSModule extends Scala3JSModule {
>   // …
> }
> ```

I saw that Scala 3 + Scala.js is supported in mill 0.9.6 - is this still the best way to go about it in 0.9.6?

**Comment by lolgab** [comment]
@bbarker No, you just need a normal Scala.js module and set the Scala version to 3.0.0-RC2. It should work just fine.
