### ISSUE TITLE
BSP does not handle runIvyDeps

### ISSUE THREAD

**Issue by ml86** [com-lihaoyi/mill#1109]
I use mill mill.bsp.BSP/install and than import my project via BSP into IntelliJ IDEA. My problem is that when I run the main class of my project, IDEA does not seem to pick up the runIvyDeps. I defined them like this:
```
  override def runIvyDeps =
    Agg(
      ivy"org.apache.logging.log4j:log4j-slf4j-impl:2.13.3",
    )
```
I get the SLF4J warning about a missing binding so i am sure the runtime ivy deps are not picked up.

**Comment by ml86** [comment]
On a side node: `runIvyDeps` seems also to be ignored my `GenIdea`.

**Comment by lefou** [comment]
> On a side node: `runIvyDeps` seems also to be ignored my `GenIdea`.

See #1110

**Comment by lefou** [comment]
This is also an issue in Bloop plugin. See #1843

**Comment by lefou** [comment]
Is this still relevant?

**Comment by lolgab** [comment]
This works correctly on current Mill. Intellij correctly adds the `runIvyDeps`, tried exactly with log4j and I don't see any
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
logs.

**Comment by lefou** [comment]
Probably, this got fixed in https://github.com/com-lihaoyi/mill/pull/1536.
