### ISSUE TITLE
Support skeleton generation of mill project (via giter8 integration)

### ISSUE THREAD

**Issue by lilac** [com-lihaoyi/mill#1123]
We want to make it easy for user to get start using mill in a new project. But under current settings, we have to do a lot of manual work to get it work.

Sbt has a new command, that let us to generate a new project quickly. This is via an integration of giter8. We can do that as well.

**Comment by lefou** [comment]
Yeah, not the first time someone asks for it and it could make an easier start for newcomers as well as in corporate environments. Go ahead! I'd prefer to start with an external module but we could also target it as built-in command.
