### ISSUE TITLE
The BSP server returns wrong sources for mill-build target

### ISSUE THREAD

**Issue by heksesang** [com-lihaoyi/mill#1159]
The response for `buildTarget/sources` returns the following item for the `mill-build` target:
```
{
  "target": {
    "uri": "file:///Users/heksesang/Source/test-project/"
  },
  "sources": [
    {
      "uri": "file:/Users/heksesang/Source/test-project/src/",
      "kind": 2,
      "generated": false
    }
  ]
}
```

This means that `build.sc` is not correctly picked up as a source for that target (you have to copy it into `/src` to get IDE support, which is a tad tedious).

**Comment by camper42** [comment]
caused by this line: https://github.com/com-lihaoyi/mill/blob/main/bsp/src/mill/bsp/MillBuildServer.scala#L90

I changed `src` to `build.sc`, build a local version, now sourceItem is `build.sc` file instead of `src` dir
```
[Trace - 03:27:37 PM] Sending response 'buildTarget/sources - (3)'. Processing request took 1699ms
Result: {
  "items": [
    {
      "target": {
        "uri": "file:///Users/camper42/Code/mill/"
      },
      "sources": [
        {
          "uri": "file:/Users/camper42/Code/mill/build.sc",
          "kind": 1,
          "generated": false
        }
      ]
    },

```

but what IDE support is missing if URI is `/src` ? @heksesang

**Comment by heksesang** [comment]
Auto-complete and hover tooltips for Mill types that are not imported from ivy directly in the script. All that is there if I put the build.sc file into the /src folder, not if it is at root.

**Comment by camper42** [comment]
Preferences -> Languages & frameworks > Scala
Worksheet section:
Treat .sc files as: Always Ammonite

This makes auto-complete and hover tooltips available no matter mill-build buildTarget/sources is

---

When Treat .sc files as worksheet, `$file` & `$ivy` import still not available even buildTarget/sources is `build.sc`
![image](https://user-images.githubusercontent.com/3177898/119923067-a4c6d280-bfa3-11eb-9d97-b09bc64b2959.png)

**Comment by heksesang** [comment]
I am using vscode and not IntelliJ.

**Comment by camper42** [comment]
will check with vscode later (I thought Metals would automatically use bloop instead of built-in bsp server

**Comment by camper42** [comment]
![image](https://user-images.githubusercontent.com/3177898/119977766-648b4280-bfeb-11eb-9425-a7cb5439259e.png)
![image](https://user-images.githubusercontent.com/3177898/119977794-6b19ba00-bfeb-11eb-8a81-2fdd63a2a645.png)

Are these your expect?

**Comment by heksesang** [comment]
Yep, that is what has been missing. :)
