### ISSUE TITLE
mill don't add the repository of pom.xml of dependent libraries

### ISSUE THREAD

**Issue by zhenleibb** [com-lihaoyi/mill#1166]
## Reproduce the issue
I have a pom.xml:

``` {.example}
<dependency>
  <groupId>org.openimaj</groupId>
  <artifactId>common-stream</artifactId>
  <version>1.3.10</version>
  <scope>compile</scope>
</dependency>
```

I transform it to build.sc:

``` {.scala}
def ivyDeps =  Agg(ivy"org.openimaj:common-stream:1.3.10")
```

I get the error:

``` {.example}
$ mill -i createVideo.repl
Compiling /tmp/test/build.sc
[19/30] createVideo.compileClasspath | Downloading [18/18] artifacts (~16454/16454 bytes)
1 targets failed
createVideo.compileClasspath 
Resolution failed for 1 modules:
--------------------------------------------
  com.lowagie:itext:2.1.7.js6 
    not found: /home/zhenlei/.ivy2/local/com.lowagie/itext/2.1.7.js6/ivys/ivy.xml
    not found: https://repo1.maven.org/maven2/com/lowagie/itext/2.1.7.js6/itext-2.1.7.js6.pom
    not found: https://oss.sonatype.org/content/repositories/releases/com/lowagie/itext/2.1.7.js6/itext-2.1.7.js6.pom
    not found: http://maven.openimaj.org/com/lowagie/itext/2.1.7.js6/itext-2.1.7.js6.pom
    not found: http://snapshots.openimaj.org/com/lowagie/itext/2.1.7.js6/itext-2.1.7.js6.pom
```
## Other information
However maven is able to solve this dependency with a repository that isn\'t
indicated in pom.xml:

``` {.example}
Downloading from jaspersoft-third-party: http://jaspersoft.jfrog.io/jaspersoft/third-party-ce-artifacts/com/lowagie/itext/2.1.7.js6/itext-2.1.7.js6.pom
Downloaded from jaspersoft-third-party: http://jaspersoft.jfrog.io/jaspersoft/third-party-ce-artifacts/com/lowagie/itext/2.1.7.js6/itext-2.1.7.js6.pom (3.1 kB at 6.4 kB/s)
```
When I add this repository in `build.sc`.  The issue is solved.
## Possible cause
I think I have this error because the repository
\`http://jaspersoft.jfrog.io\` is indicated in a pom.xml of a dependency
lib. And mill don\'t add the repository it find in pom.xml. It add only
the repositories indicated in build.sc I\'m right? It is possible to
make a enhancement to solve this issue? It won\'t be practice to run
maven to debug a problem of Resolution failed of mill.

**Comment by lefou** [comment]
Personally, I think the current behavior is a god thing, as a repo is an abstraction over the source of origin and hence, again my personal opinion, it should be controlled in the build, not in some of the dependencies. But to get to the root of the issue, you should ask in the coursier project, whether this feature is supported by coursier or not.  Mill uses coursier to handle repositories and dependency resolution. But we're talking about a Maven specific feature here, I think. Of course, you can add the repository to your project, as you said. This is IMHO not a workaround but the solution. Making the repository explicit is a good thing.

**Comment by lefou** [comment]
No bug and not IMHO also an invalid feature request.
