### ISSUE TITLE
forkArgs can't pass java system properties to mill console

### ISSUE THREAD

**Issue by zhenleibb** [com-lihaoyi/mill#1208]
`forkArgs` can pass java system properties for mill foo.run, but no for `mill -i foo.console` and `mill -i foo.repl`
## Reproduce the bug
build.sc: 
```
  def forkArgs = Seq(s"-Djna.library.path=/home/kdf/usr/anaconda3/envs/tiktok/lib/python3.7/lib-dynload")
```
Main.sc:
```
package foo
object Main extends App{
print(System.getProperty("jna.library.path"))
}
```
shell:
```
$ mill foo.run
[38/38] foo.run 
/home/kdf/usr/anaconda3/envs/tiktok/lib/python3.7/lib-dynload
$ mill -i foo.repl
kdf-example-1@ System.getProperty("jna.library.path")  
res0: String = null

$ mill -i foo.console
scala> System.getProperty("jna.library.path") 
res0: String = null
```

**Comment by zhenleibb** [comment]
Exit a temporary solution to define -D system properties for mill repl? 
I have try to use `mill -D` to go around the issue, but it doesn't run:
```
$ mill -i -D jna.library.path=/home/kdf/usr/anaconda3/envs/tiktok/lib/python3.7/lib-dynload foo.repl
kdf-example-1@ System.getProperty("jna.library.path")  
res0: String = null
```

**Comment by lefou** [comment]
> Exist a temporary solution to define -D system properties for mill repl?
> I have try to use `mill -D` to go around the issue, but it doesn't run:

Just override or copy the `repl` target with it's original definition and adapt it. I think, you will need to use the `jvmArgs` of `Jvm.runSubprocess`.

A proper fix might look like something like this:

```scala
 def repl(replOptions: String*) = T.command {
    if (T.log.inStream == DummyInputStream){
      Result.Failure("repl needs to be run with the -i/--interactive flag")
    }else{
      Jvm.runSubprocess(
        mainClass = "ammonite.Main",
        classPath = ammoniteReplClasspath().map(_.path),
        forkArgs = forkArgs(),
        forkEnv = forkEnv(),
        mainArgs = replOptions,
        workingDir = os.pwd
      )
      Result.Success()
    }
  }
```

**Comment by zhenleibb** [comment]
It works, thank you ! 
Do you need I make a PR for it, or you are already on it?

**Comment by lefou** [comment]
Thanks for the feedback. I already create a PR.
