### ISSUE TITLE
mill doesn't respect the HOME environment variable and still writes into /home/{user}/.cache/coursier

### ISSUE THREAD

**Issue by yurivict** [com-lihaoyi/mill#1315]
It downloads jars into that directory.

For the purpose of package building cache directory should be unique for each build so that they wouldn't conflict through cache.

**Comment by lefou** [comment]
Mill does not explicitly set the directory for the coursier cache, so this issue originates upstream and should also reported upstream.

**Comment by yurivict** [comment]
What is the upstream URL?

**Comment by lefou** [comment]
> What is the upstream URL?

https://github.com/coursier/coursier

**Comment by yurivict** [comment]
https://github.com/coursier/coursier/issues/2036


Thanks!
