### ISSUE TITLE
Intellij BSP test returns null

### ISSUE THREAD

**Issue by sequencer** [com-lihaoyi/mill#1323]
Mill 0.9.6 failed to add BSP test via Intellij, which was implmented by @samvel1024 in JetBrains/intellij-scala#476
```
[Trace - 04:06:30 AM] Received request 'buildTarget/scalaTestClasses - (3)'
Params: {
  "targets": [
    {
      "uri": "file:///project/directory"
    }
  ],
  "originId": "5dcf406b-5e73-46db-919b-aecde0891332"
}


[Trace - 04:06:51 AM] Sending response 'buildTarget/scalaTestClasses - (3)'. Processing request took 20545ms
Result: null
```
However in https://build-server-protocol.github.io/docs/specification.html, I didn't see any definition of request `buildTarget/scalaTestClasses`
But I do searched related request from https://github.com/build-server-protocol/build-server-protocol/blob/master/docs/extensions/scala.md 
Does Intellij BSP implements a out-of-date spec? or BSP from build-server-protocol.github.io is out-of-date, and mill didn't implement it.

**Comment by lefou** [comment]
It's documented under Extensions > Scala: https://build-server-protocol.github.io/docs/extensions/scala.html#scala-test-classes-request

**Comment by sequencer** [comment]
Got it, I think mill should implement it to support IDEA?
mill+bsp+ScalaTest always trigger a class not found error, I hope BSP can resolve this issue.
