### ISSUE TITLE
Unable to consume locally published scala-native

### ISSUE THREAD

**Issue by avdv** [com-lihaoyi/mill#1326]
Hi.

I am using a custom scala-native build which I publish locally. The version of which is "0.4.1-SNAPSHOT".

Trying to use these artifacts from within mill results in:
```
Resolution failed for 5 modules:
--------------------------------------------
  org.scala-native:nativelib_native0.4_2.13:0.4.1-SNAPSHOT 
	not found: /home/claudio/.ivy2/local/org.scala-native/nativelib_native0.4_2.13/0.4.1-SNAPSHOT/ivys/ivy.xml
	not found: https://repo1.maven.org/maven2/org/scala-native/nativelib_native0.4_2.13/0.4.1-SNAPSHOT/nativelib_native0.4_2.13-0.4.1-SNAPSHOT.pom
  org.scala-native:test-interface_native0.4_2.13:0.4.1-SNAPSHOT 
	not found: /home/claudio/.ivy2/local/org.scala-native/test-interface_native0.4_2.13/0.4.1-SNAPSHOT/ivys/ivy.xml
	not found: https://repo1.maven.org/maven2/org/scala-native/test-interface_native0.4_2.13/0.4.1-SNAPSHOT/test-interface_native0.4_2.13-0.4.1-SNAPSHOT.pom
  org.scala-native:javalib_native0.4_2.13:0.4.1-SNAPSHOT 
	not found: /home/claudio/.ivy2/local/org.scala-native/javalib_native0.4_2.13/0.4.1-SNAPSHOT/ivys/ivy.xml
	not found: https://repo1.maven.org/maven2/org/scala-native/javalib_native0.4_2.13/0.4.1-SNAPSHOT/javalib_native0.4_2.13-0.4.1-SNAPSHOT.pom
  org.scala-native:scalalib_native0.4_2.13:0.4.1-SNAPSHOT 
	not found: /home/claudio/.ivy2/local/org.scala-native/scalalib_native0.4_2.13/0.4.1-SNAPSHOT/ivys/ivy.xml
	not found: https://repo1.maven.org/maven2/org/scala-native/scalalib_native0.4_2.13/0.4.1-SNAPSHOT/scalalib_native0.4_2.13-0.4.1-SNAPSHOT.pom
  org.scala-native:auxlib_native0.4_2.13:0.4.1-SNAPSHOT 
	not found: /home/claudio/.ivy2/local/org.scala-native/auxlib_native0.4_2.13/0.4.1-SNAPSHOT/ivys/ivy.xml
	not found: https://repo1.maven.org/maven2/org/scala-native/auxlib_native0.4_2.13/0.4.1-SNAPSHOT/auxlib_native0.4_2.13-0.4.1-SNAPSHOT.pom
```

That is caused by a naming mismatch since mill uses the binary scala-native version in the artifact name whereas sbt publishes with full cross scala-native version:
```console
$ ls ~/.ivy2/local/org.scala-native/*0.4.1*_2.13 -d
/home/claudio/.ivy2/local/org.scala-native/auxlib_native0.4.1-SNAPSHOT_2.13
/home/claudio/.ivy2/local/org.scala-native/clib_native0.4.1-SNAPSHOT_2.13
/home/claudio/.ivy2/local/org.scala-native/javalib_native0.4.1-SNAPSHOT_2.13
/home/claudio/.ivy2/local/org.scala-native/junit-async-native_native0.4.1-SNAPSHOT_2.13
/home/claudio/.ivy2/local/org.scala-native/junit-runtime_native0.4.1-SNAPSHOT_2.13
/home/claudio/.ivy2/local/org.scala-native/nativelib_native0.4.1-SNAPSHOT_2.13
/home/claudio/.ivy2/local/org.scala-native/posixlib_native0.4.1-SNAPSHOT_2.13
/home/claudio/.ivy2/local/org.scala-native/scalalib_native0.4.1-SNAPSHOT_2.13
/home/claudio/.ivy2/local/org.scala-native/test-interface_native0.4.1-SNAPSHOT_2.13
/home/claudio/.ivy2/local/org.scala-native/test-interface-sbt-defs_native0.4.1-SNAPSHOT_2.13
```

**Comment by lefou** [comment]
How did you declare the dependency? I assume you've used `ivy"org.scala-native::nativelib::0.4.1-SNAPSHOT"`. Have you tried to use three double-colons between org and name?

```diff
- `ivy"org.scala-native::nativelib::0.4.1-SNAPSHOT"`
+ `ivy"org.scala-native:::nativelib::0.4.1-SNAPSHOT"`
```

I haven't it tried myself, but this is the solution for default platform (JVM) dependencies.

**Comment by avdv** [comment]
I am building utest for my scala-native version, which just uses the ScalaNativeModule which in turn defines the dependencies on the scala-native libraries:
```
  object native extends Cross[NativeUtestModule](scalaNativeVersions: _*)
  class NativeUtestModule(val crossScalaVersion: String, crossScalaNativeVersion: String)
    extends UtestMainModule(crossScalaVersion) with ScalaNativeModule with UtestModule {
```
https://github.com/com-lihaoyi/utest/blob/b222fcf0b33e058cd1b3038f41e67b1a0f509720/build.sc#L115-L117

I worked around by overriding the `platformSuffix`:
```
  override def platformSuffix = s"_native${crossScalaNativeVersion}"
```

**Comment by lefou** [comment]
I think your workaround sounds reasonable. My suggestion was nonsense, after a second look to your issue. I think mill currently does not support it with dedicated syntax. I've no idea how common such kind of dependencies are or will be. Of course, we could support these, e.g. with three double-colons between name and version, but experience has shown that these are quite regularly overlooked. Maybe @lolgab has an opinion or more insights?

And BTW, Greetings to Leipzig!  @avdv, we met in person before in the Leipzig Scala user group.  :wave:

**Comment by avdv** [comment]
> And BTW, Greetings to Leipzig! @avdv, we met in person before in the Leipzig Scala user group.

Ja, viele Grüße Tobias! I remember the meetup - it was quite some time ago... :wave:

**Comment by lolgab** [comment]
Hi @avdv,
I think you are experiencing one of the rare cases where Mill is correct and the Scala Native sbt plugin is wrong.
There is a [open PR](https://github.com/scala-native/scala-native/pull/2207) in Scala Native to fix the versioning scheme so `0.4.1-SNAPSHOT` is considered binary compatible with `0.4.0` and consume libraries with `_0.4` suffix.
If you found already a workaround you have only to wait for that PR to be merged upstream, otherwise, as another workaround, you can _cheat_ by publishing Scala Native locally changing version from `0.4.1-SNAPSHOT` to `0.4.1` which will use a naming scheme coherent with Mill.

**Comment by avdv** [comment]
Thank you @lolgab, that looks like I could integrate that PR into my scala-native fork and then use it in place of the official one without rebuilding all the libraries I want to use... (currently, I am rebuilding sjavatime, scopt and utest locally / on CI).

**Comment by lefou** [comment]
Closing this, as this is neither a bug in mill nor a feature request. Also there is a workaround available.
