### ISSUE TITLE
Illegal character in URI using BSP

### ISSUE THREAD

**Issue by Iltotore** [com-lihaoyi/mill#1333]
Mill version: 0.9.7
BSP version: 2.0.0
OS: Windows 10

When syncing with BSP (mill.bsp.BSP/start), the following error occurs on Intellij IDEA:
> java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\Users\rapha\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\lihaoyi\mill-scalalib_2.13\0.9.7\mill-scalalib_2.13-0.9.7-sources.jar

Mill returns invalid URI from scalacOptions:
- URI must not contain backslashes.
- The String before the first `:` should be the file protocol.

The valid form of the above example should be `file:C:/Users/rapha/AppData/Local/Coursier/cache/v1/https/repo1.maven.org/maven2/com/lihaoyi/mill-scalalib_2.13/0.9.7/mill-scalalib_2.13-0.9.7-sources.jar`

**Comment by CidTori** [comment]
Same for me:

> java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\Users\{my user name}\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\lihaoyi\mill-contrib-buildinfo_2.13\0.9.7\mill-contrib-buildinfo_2.13-0.9.7-sources.jar
