### ISSUE TITLE
Can't modify scaladoc sources.

### ISSUE THREAD

**Issue by Iltotore** [com-lihaoyi/mill#1384]
## Introduction
Version: 0.9.8
Mill doesn't provide any way to set custom scaladoc sources, for example, when you want to create a single scaladoc of all of your modules.

## Solution
Add a new dedicated property and use it in `docJar` instead of `allSourcesFiles` directly

**Comment by lefou** [comment]
I can imagine a need for customizing the sources before doc processing, but I don't see how it helps in providing a aggregated doc jar without loosing the option to generate a non-aggregated doc jar. I think you will still need some aggregator module to collect all doc sources, in which case you could also just customize the existing sources targets.

**Comment by Iltotore** [comment]
> I can imagine a need for customizing the sources before doc processing, but I don't see how it helps in providing a aggregated doc jar without loosing the option to generate a non-aggregated doc jar

If you can customize the sources before processing, you can use the sources of other modules:
```scala
def docSources = T { submodule1.docSources() ++ submodule2.docSources() }
```
