### ISSUE TITLE
Unable to gracefully stop a task

### ISSUE THREAD

**Issue by Iltotore** [com-lihaoyi/mill#1425]
OS: Windows 10
Mill Version: 0.9.9

## Issue

There is no (documented ?) way to send shutdown message to the running task. For example, we can't gracefully shutdown a program launched via `JavaModule#run`.

**Edit: Shutdown hooks are called on Windows but Process#destroy behaviour is implementation dependent and we shouldn't rely on.**

## Suggested solution

When pressing the "shutdown input" (like CTRL+C or another combination to avoid clash with the "kill forcibly" command) should call a method of the running task (like `Task#shutdown`) instead of [destroying the process](https://github.com/com-lihaoyi/mill/blob/51620e7048921613c7cc4f2e180f332cd7d9b47d/main/src/modules/Jvm.scala#L158).

- The default implementation of `Task#shutdown` should wait for itself (the task) to finish.
- The `JavaModule#run` task should send a SIGINT to the program to request a graceful shutdown.

**Comment by lefou** [comment]
Intercepting `InterruptedException` is probably you best bet to detect a task abortion. Best way to improve the way sub processes are handled when a task is interrupted is by providing a better implementation that works on all platforms.

**Comment by lefou** [comment]
You can just override the `JavaModule#run` task and do whatever you think is the best in your use case. Mill is very easy to customize in that regard.

**Comment by Iltotore** [comment]
> You can just override the JavaModule#run task and do whatever you think is the best in your use case. Mill is very easy to customize in that regard.

Will try that thank you. Also Mill doesn't seem to abort task when executed in REPL mode (Ctrl+C doesn't do anything when trying to abord a `JavaModule#run`) ?
If preferable, I can open a new issue for this specific problem.
