### ISSUE TITLE
[BSP] Obsolete diagnostics are not cleared between compilations 

### ISSUE THREAD

**Issue by Baccata** [com-lihaoyi/mill#1429]
As per the [specification](https://build-server-protocol.github.io/docs/specification.html#publish-diagnostics), it's the server's responsibility to clear obsolete diagnostics. 

The problem occurs when using mill's bsp conjointly with metals, where displayed compile errors are only ever cleared when other compiler errors occur in subsequent compilations  (as opposed to successful compilation). 

I think a solution would be for the [diagnostic map](https://github.com/com-lihaoyi/mill/blob/main/bsp/src/mill/bsp/BspLoggedReporter.scala#L39) here to be stored by the server between compilation (whereas currently, a new BspLoggedReporter instance gets created every time compilation is called upon). Storing it would allow to apply a diff between two compiler runs, and reset all diagnostics that are obsolete. 

I'll try to work on it in the next few weeks.

**Comment by heksesang** [comment]
This is the same as https://github.com/com-lihaoyi/mill/issues/987?

**Comment by Baccata** [comment]
It is indeed, I'll close this one.
