### ISSUE TITLE
Cannot execute repl, Resolution failed for ammonite 6:2.3.8-65-0f0d597f

### ISSUE THREAD

**Issue by simao** [com-lihaoyi/mill#1438]
```
$ mill -i  anorm-async[2.13.6].repl
Preparing Java 11.0.12 runtime; this may take a minute or two ...
Compiling /home/simao/code/anorm-async/build.sc
[27/35] anorm-async[2.13.6].compile 
Compiling compiler interface...
[info] compiling 1 Scala source to /home/simao/code/anorm-async/out/anorm-async/2.13.6/compile/dest/classes ...
[warn] 2 deprecations (since 2.13.0); re-run with -deprecation for details
[warn] one warning found
[info] done compiling
[31/35] anorm-async[2.13.6].resolvedAmmoniteReplIvyDeps | Downloading [2/2] artifacts (~0/0 bytes)
1 targets failed
anorm-async[2.13.6].resolvedAmmoniteReplIvyDeps 
Resolution failed for 1 modules:
--------------------------------------------
  com.lihaoyi:ammonite_2.13.6:2.3.8-65-0f0d597f 
	not found: /home/simao/.ivy2/local/com.lihaoyi/ammonite_2.13.6/2.3.8-65-0f0d597f/ivys/ivy.xml
	not found: https://repo1.maven.org/maven2/com/lihaoyi/ammonite_2.13.6/2.3.8-65-0f0d597f/ammonite_2.13.6-2.3.8-65-0f0d597f.pom
```

I am running mill 0.9.9 using the bootstrap script, I got this error before and after deleting `./out` and `~/.mill`.

**Comment by lefou** [comment]
This is most probably not a bug. The following answer might help: https://github.com/com-lihaoyi/mill/discussions/1396#discussioncomment-969512

**Comment by gbersac** [comment]
Thanks @lefou , I had the same issue and the solution you proposed worked for me. Also, I discussed the problem in gitter https://gitter.im/lihaoyi/mill
That being said I disagree that this is not a bug. This is very frustrating for the user and really hurt the credibility of the project as a serious / mature competitor to sbt.
In my opinion, this is at least a usability / ux issue that need to be fixed. As a user, I just want mill to work.
### Proposed solution design
Maybe try to add a default value for ammonite if the default doesn't work. Or an incremental search for an ammonite version that works.

**Comment by lefou** [comment]
Having a default looks convenient at first sight, but in general, default versions tend to not age well. 

In this particular case it's rather hard to come up with a good default, as the Ammonite version highly depends on the already user-configured Scala version! What ever logic to retrieve a valid (if any) Ammonite version you have in mind, it will be definitely not easy to guess for other users and most likely not reproducible over time, which leads to a frustrating users experience too.

Therefore I think, it's much better to simply require an explicitly set Ammonite version, as we do for other versions like the `scalaVersion`.

Implementation wise, we should deprecate the currently defined default and print some warning in case a user starts the repl without a overridden `ammoniteVersion`. Also some documentation is required.

**Comment by lihaoyi** [comment]
@lefou could one solution be to closely follow the latest Scala/Ammonite releases with a corresponding Mill release? 

Ammonite already releases a new version to match every Scala minor version, and if Mill pulls that in, at least we'll be able to guarantee that if you use the latest Mill release with the latest Scala version, Ammonite will work out of the box. Scala doesn't release all that frequently, so matching releases wouldn't be too much of a maintenance overhead

Now if someone uses an old version of Mill with new version of Scala, there's not much we can do there, but at least we can make the "latest latest" case work.

**Comment by lefou** [comment]
@lihaoyi I understand the reasoning, but technically, it's not even needed to cut a new mill release for each new Scala or Ammonite release. And if it is not needed, why create new releases which will put more stress to Mill devs and users. It's the exact reason why this is configurable.

Each release means a lot of work, the smallest part is on the mill devs (e.g. releasing, testing, documenting, etc). The full storied only starts there and continues with work for plugin developers and users and so on.

**Comment by lefou** [comment]
Also, closely following dependent versions is to-date very easy for open source projects by using @scala-steward . E.g. for Ammonite, just define an ivy dependency an Ammonite and refer to the `ammoniteVersion` and voila, you'll receive a PR as soon a new Ammonite release is out.

**Comment by lihaoyi** [comment]
Yeah it's not otherwise necessary, it would be some additional operational overhead and churn just to get this working seamlessly.

I'll leave it to your judgement however you would like to decide on the tradeoff.

**Comment by lefou** [comment]
In the past it was not even possible to keep up with the latest versions of Scala and Ammonite. Also we currently have a stable branch for 0.9.x but development happens on main branch for upcoming 0.10, which has no stable API yet and hence no available external plugins. As always, the devil is in the details.

I'd favor to just try to provide a better error message to guide the user in case the built-time Ammonite version isn't available for the selected Scala runtime.
