### ISSUE TITLE
Nondeterministic client-server locks

### ISSUE THREAD

**Issue by sake92** [com-lihaoyi/mill#1447]
As discussed [here](https://github.com/com-lihaoyi/mill/pull/1089#issuecomment-751461785), the goal is to have 5 Mill servers in total that serve multiple clients.  
The issue is that Mill [client code](https://github.com/com-lihaoyi/mill/blob/main/main/client/src/mill/main/client/MillClientMain.java#L134) locks on a file *inside a project*, and not globally.  
That means if you run `mill foo.compile` in another folder, it will create a new server instance (different lock file) **with the same pipe name**.  
That causes the client to *nondeterministically* connect to one of the servers...
Not sure if I am missing some crucial details here but that's my understanding... 😄 

The solution could be to put these lock files inside user home folder maybe?

**Comment by lihaoyi** [comment]
Lock files are intended to be per project. If the named pipes aren't per project, a simple solution would be to add the project folder path (or a hash if the path) to the named pipe name to namespace them
