### ISSUE TITLE
`scala-library` dependency is not added to published jars' `pom.xml`

### ISSUE THREAD

**Issue by lolgab** [com-lihaoyi/mill#1487]
The issue was noticed by @olafurpg in Geny here: https://github.com/com-lihaoyi/geny/issues/32

When publishing libraries with Sbt the scala-library dependency is declared in the `dependencies` section of the `pom.xml`.
With libraries published with Mill this doesn't happen.

The same problem also happens with ScalaJS libraries that doesn't have any dependencies in the pom when created with Mill, but  when compiled with Sbt they emit these dependencies:
```xml
<dependencies>
    <dependency>
        <groupId>org.scala-lang</groupId>
        <artifactId>scala-library</artifactId>
        <version>2.13.5</version>
    </dependency>
    <dependency>
        <groupId>org.scala-js</groupId>
        <artifactId>scalajs-library_2.13</artifactId>
        <version>1.7.0</version>
    </dependency>
    <dependency>
        <groupId>org.scala-js</groupId>
        <artifactId>scalajs-test-bridge_2.13</artifactId>
        <version>1.7.0</version>
        <scope>test</scope>
    </dependency>
</dependencies>
```

**Comment by lefou** [comment]
Interesting. This doesn't impact builds as the scala library deps are introduced in `resolvedIvyDeps`. The only explanation I have is, that people tend to forget to include `super.ivyDeps()` when overriding `ivyDeps` and therefore we bring it late into the party. Solution: Either let the user always include `super.ivyDeps()`, which is error-prone. Or explicitly include the scala library when calculating the pom (e.g. in `publishXmlDeps`).  I currently tend to like the latter option more.

**Comment by lefou** [comment]
Unfortunately `publishXmlDeps` is in `PublishModule` and not scala-aware. To avoid coupling, we may need to introduce an additional target to `JavaModule` which provides the "final" ivyDeps. WDYT?

**Comment by lefou** [comment]
I'm wondering, if the current `scalaLibrarayIvyDeps` isn't a more general concept, we could move into `JavaModule`. It needs another name though, e.g. `platformIvyDeps` or `mandatoryIvyDeps`.

**Comment by lolgab** [comment]
> I'm wondering, if the current scalaLibrarayIvyDeps isn't a more general concept, we could move into JavaModule. It needs another name though, e.g. platformIvyDeps or mandatoryIvyDeps.

It reminds me of the same problem we fixed with `mandatoryScalacOptions`...
Maybe something like mandatoryIvyDeps is the way to go, but I have to look at the problem first, because it is not clear yet.
I'll let you know once I check it!
Thanks for looking at it!

**Comment by lefou** [comment]
TBH, I would favour to just add the scala-library to `ivyDeps` and let the user include `super.ivyDeps`. This is IMHO the canonical way to customize in mill and any special treatment suggests, that adding something in mill is always designed that way. As a safe point, we could just check for an existing scala-library downstream and issue a helpful error message, as compilation would fail anyways.

**Comment by lihaoyi** [comment]
Persoanoly I'd be in favor of a `mandatoryIvyDeps` or similar. Using `super.*` is certainly canonical, but that's traded off against the fact that we should make the default/concise thing what most people want and make the verbose thing what few people want.

Almost everyone wants to keep scala-library, and few people want to remove it. introducing `mandatoryIvyDeps` makes the common path not need to use `super.*`, and makes the rare path need to override a longer and mote obscure target name, which fits into the goal described above.

**Comment by lefou** [comment]
@lihaoyi I agree. I think the only thing that's bugging me is the new `allIvyDeps` target. It is only used in two places and I think we can omit that.

@lolgab I prepared some changes on top of your initial PR and would appreciate your review.

**Comment by lefou** [comment]
I think this `mandatoryIvyDeps` thing opens convenience for even more modules, e.g. in AspectJ we always want to add a runtime lib... 
Maybe, we should take the chance and introduce `mandatoryRunIvyDeps` and `mandatoryCompileIvyDeps` too. WDYT?

**Comment by lolgab** [comment]
I'd say to ship this as it is and then discuss `mandatoryRunIvyDeps` and `mandatoryCompileIvyDeps` elsewhere since the main motivation for this change was the fix of the scala-library in `pom`, and current PR it's enough to fix it.

**Comment by olafurpg** [comment]
Thank you for this fix! 🙏
