### ISSUE TITLE
Please mark 0.10.0-M2 pre-release

### ISSUE THREAD

**Issue by ryantm** [com-lihaoyi/mill#1506]
I am a maintainer of nixpkgs which packages mill, and we have automated update scripts that detect the latest version of this package and try to update to that. Currently, 0.10.0-M2 is marked as the "latest release" in GitHub, so it is trying to use that even though it is probably a pre-release.

Could you please change 0.10.0-M2 to be marked as a pre-release?

**Comment by lefou** [comment]
Sure. This release ins meant to be a milestone release. It is a proper release though. Users can use it. So downstream packaging still makes sense.
