### ISSUE TITLE
mill doesn't use COURSIER_CACHE

### ISSUE THREAD

**Issue by xushuxun** [com-lihaoyi/mill#1543]
On WSL 2, mill will download cache to the project related directory `./coursier`.

Setting bash env `COURSIER_CACHE=~/.coursier`, it seems not work.

**Comment by lefou** [comment]
This is probably because we override it for WSL without checking whether it was already defined: https://github.com/com-lihaoyi/mill/blob/067c7c7c9b020da0dcc14af1c122a7cddc4b0386/build.sc#L778
