### ISSUE TITLE
Add `T.ctx().workspace` to access the project top level directory

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#1544]
The question how to access the project root directory is asked frequently in the chat.

I think having the location of the project root directory in often useful. Sometime I see the use of `os.pwd`, which works but is doomed to fail. e.g. when we change some internals of Mill.

In my latest concrete case, I need this value to properly configure semanticdb-scalac-plugin for Metals support.

@lihaoyi Any objections?

**Comment by lihaoyi** [comment]
no objections, sounds reasoanble to me
