### ISSUE TITLE
0.10.0-M4 fails to compile build.sc if it contains a top level import from scala package

### ISSUE THREAD

**Issue by pbuszka** [com-lihaoyi/mill#1572]
mill 0.10.0-M4 when compiling build.sc for a large project throws a bunch of errors like `error while loading $times$colon, Missing dependency 'Add -Ytasty-reader to scalac options to parse the TASTy in /home/piotr/.cache/mill/download/0.10.0-M4(scala/$times$colon.class)', required by /home/piotr/.cache/mill/download/0.10.0-M4(scala/$times$colon.class)`
plus 11 more like this for several classes in scala and scala.util packages

tried with scalaVersion 2.13.3, 2.13.6 and 2.13.7 in the project

The same build.sc works on 0.9.10
Fails on 0.10.0-M3 too
0.10.0-M2 fails on something else so can't verify

Tried to add -Ytasty-reader in build.sc file but the problem happens during build.sc compilation so I would be surprised if it worked

**Comment by pbuszka** [comment]
In fact an empty build.sc with just imports and nothing else

import scala.sys.process._
import scala.sys
import scala.util.Try

triggers the same problems so it seems that importing something from scala package triggers the error

**Comment by pbuszka** [comment]
if I removed the problematic imports from top level and put them inside the object the problem disappears 
```
import scala.util.Try
object graphql extends Module {
 ...
}
```
fails
```
object graphql extends Module {
  import scala.util.Try
  ...
}
```
compiles

**Comment by lefou** [comment]
Could you please verify, that it does not happen with Mill 0.10.0-M3? 

I've the vague feeling it's related to the fact it's built and bundled with Scala 2.13.6. I can't recall, where I've seen it, but there is a slight chance that it might be just work when we upgrade to Scala 2.13.7.

**Comment by pbuszka** [comment]
Fails on M2 and M3
M1 there is no release artifact I suppose I get 404

**Comment by lefou** [comment]
@pbuszka Thanks for testing. As we changed the underlying Ammonite version (which is also the reason why 0.10.x is binary incompatible), we need to investigate, if this also happens with pure Ammonite scripts and how we can fix it.

**Comment by lolgab** [comment]
Checked with `0.10.0-M1-5-e3e32e` and it fails.

**Comment by lefou** [comment]
This is not an issue anymore since Mill 0.10.0-M5. I also tested all Mill 0.10.x versions from `x = 0..8`.
