### ISSUE TITLE
mill can't run when project path contains ":"

### ISSUE THREAD

**Issue by dev590t** [com-lihaoyi/mill#1575]
## reproduce bug
```
mkdir "bug : dir"
cd "bug : dir"
git clone --depth=1 https://github.com/com-lihaoyi/mill.git
cd mill/example/example-1
mill foo.run
```
It produces
```
Error: Could not find or load main class foo.Example
Caused by: java.lang.ClassNotFoundException: foo.Example
1 targets failed
foo.run subprocess failed
```

**Comment by lefou** [comment]
Which operating system? Can you post your `mill --version`?

**Comment by dev590t** [comment]
mill --version
Mill Build Tool version 0.9.8
Java version: 11, vendor: Oracle Corporation, runtime: /gnu/store/q7cgz76gd930nij982j6yybhzrvr1jna-openjdk-11.28-jdk
Default locale: en_US, platform encoding: UTF-8
OS name: "Linux", version: 5.9.3-gnu, arch: amd64

**Comment by lefou** [comment]
I think we don't properly mask the `:` symbol, which is also the separator for the `classpath` parameter of `java.exe`.

**Comment by lefou** [comment]
I can't find any reference in the Java Documentation, how we are supposed to "properly" escape the colon. :-(

**Comment by dev590t** [comment]
The issue is from which line of which file? Maybe I can have a idea

**Comment by lefou** [comment]
To run your main class, we need to launch a Java process with the correct classpath. As your project path contains a colon, also some elements of than classpath contain a colon. When we construct the cli parameters for the Java process we concat each path separated by a colon (or semicolon on Windows) but Java then deconstructs that classpath by splitting at the colon. As that results in incorrect paths it can't find your main and the `ClassNotFoundException` is thrown.

https://github.com/com-lihaoyi/mill/blob/93b78e52691cb1528243b047937d15fafebc3ec3/main/src/mill/modules/Jvm.scala#L108

**Comment by lefou** [comment]
I'm closing this as adding jar which itself contain a colon (`:`) in their file or directory name are not supported by Java. You you find a workaround, please comment and we can reopen an fix it.
