### ISSUE TITLE
ScalaPBModule  does not pick transformers

### ISSUE THREAD

**Issue by borissmidt** [com-lihaoyi/mill#1625]
I tend to replace the protobuf types to joda.time/java.time types when i generate protobuf dependencies:
This is possible by setting a single protobuf transformer which will replace one type with another.
But when i use this in 1 package these options are not picked up and the case class still contains google.porotbuf.timestamp.

when i have a project with 2 proto files and an converter:
`/protobuf/my/package/scalapb-options.proto`
```
package my.package
option (scalapb.options) = {
  scope: PACKAGE
  import: "com.package.ProtobufConversions._"
  field_transformations : [
    {
      when : {
        type: TYPE_MESSAGE
        type_name: ".google.protobuf.Timestamp"
      }
      set : {[scalapb.field] {type : 'org.joda.time.base.AbstractInstant' }}
    },
    {
      when : {
        type: TYPE_MESSAGE
        type_name: ".google.protobuf.Duration"
      }
      set : {[scalapb.field] {type : 'org.joda.time.Duration' }}
    }
  ]
};
```

and 
`/protobuf/my/package/protobuf/`

```
syntax = "proto3";

package my.package.protobuf;

import "google/protobuf/timestamp.proto";

message Interval {
    google.protobuf.Timestamp start = 1;
    google.protobuf.Timestamp end = 2;
}
```

https://scalapb.github.io/docs/transformations/

**Comment by lefou** [comment]
Fixed by #1626

**Comment by borissmidt** [comment]
Sadly the files with scalapb options aren't picked up even if you pass it as a `--proto_path` to scalapb.

To make multi projects build work i had to add this to my modules: 
```
override def scalaPBIncludePath: T[Seq[PathRef]] = T {
    Seq(scalaPBUnpackProto(), PathRef(this.millSourcePath / "resources")) ++ Target.sequence(moduleDeps.collect{case m: ScalaPBModule =>  m.scalaPBIncludePath})().flatten
 }
```
So we might need to add this as well to `ScalaPBModule` otherwise imports of protofiles difined in other packages are resolved and you fail wiht 'import x/y/z.proto` not found.

**Comment by borissmidt** [comment]
I've done some further research it seems that this is a problem in general with protoc that option files are not picked up because only imported files are added to the generation path.
So this has to be resolved on the build tool level, so we will have to work together with the scalapb maintainer to implement it in all build tools in a consistent way. I'll make a follow up PR if we can find a good solution.
My solution would just be to use a filename convention. which is rather easy to implement.
