### ISSUE TITLE
Release prebuilt assembly for 0.9.11

### ISSUE THREAD

**Issue by mallman** [com-lihaoyi/mill#1631]
I would like to run mill 0.9.11 from the mill script, but https://github.com/com-lihaoyi/mill/releases/tag/0.9.11 does not include an assembly. When I update `DEFAULT_MILL_VERSION=0.9.11` in my run script I get a 404 error.

**Comment by lefou** [comment]
Yeah, this is a know issue. I'm already working on it.

Background: Publishing to our Sonatype repository is currently not working. I tried many times with different setups, until now without success. Even if I would upload the assembly to the GitHub release page manually, we still would need some artifacts to be present in the coursier repo.

**Comment by lefou** [comment]
All artifacts uploaded to Maven Central and GitHub Releases.
