### ISSUE TITLE
Scala.js: Default to ECMAScript 2015

### ISSUE THREAD

**Issue by davesmith00000** [com-lihaoyi/mill#1665]
The official default for Scala.js is ECMAScript 2015, but Mill currently defaults to ES 5.1, here:

```scala
def useECMAScript2015: T[Boolean] = false
```

https://github.com/com-lihaoyi/mill/blob/main/scalajslib/src/ScalaJSModule.scala#L200

Mill should default to ES 2015 instead. The workaround is to add this line to your `build.sc` file:

```scala
override def useECMAScript2015 = T(true)
```

**Comment by lefou** [comment]
Can you provide a link to that claim?

I only found this:

> ES modules and Node.js
> ==
> Node.js needs explicit signaling that a module is an ECMAScript module (the default is CommonJS).

from https://www.scala-js.org/doc/project/module.html, 2022-01-11

**Comment by lolgab** [comment]
@lefou `ESModule` is an orthogonal setting to the `ESVersion`.
Scala.js recently (`1.6.0`) deprecated the `useECMAScript2015` for a `esVersion` setting that can have multiple values (`ES5`, `ES2015`, `ES2020`).
Mill should probably do the same.

**Comment by lefou** [comment]
Shouldn't we infer the default from the selected ScalaJS version then?

**Comment by davesmith00000** [comment]
Fair challenge, all I can only offer is that Scala.js's author suggested I raise this issue, which I realise is an appeal to authority but...

![image](https://user-images.githubusercontent.com/908709/148955538-650b360a-601f-4e67-ac69-847744ae8b3f.png)

I discovered this was a problem for me when I noticed that code compiled in sbt was working as expected, but identical code compiled through Mill resulted in runtime errors.

Currently all you've got is a boolean flag, so being consistent with sbt is easy enough, just set it to true as in the PR - however that is a bit of a magic value. Inferring the right version based on Scala.js version will be a marginally more involved change, but I'd be ok with it being a setting the user had to provide to avoid ambiguity.

**Comment by lolgab** [comment]
I think that for now we can change the default as you did.
Changing for a single version of ScalaJS is not possible for how Mill works. But I don't think it is a problem to change the default in `0.6` I don't think anybody still uses `0.6`.

In the future we could change mill to have `esVersion` and deprecate the option.

**Comment by lefou** [comment]
> Changing for a single version of ScalaJS is not possible for how Mill works. 

Why? We can just depend on `scalaJS` target and if the version is high enough (> 1.6 or even > 1.x) we can set it to `ECMAScript2015`.

> In the future we could change mill to have `esVersion` and deprecate the option.

We should do this now. The change is simple and we are still before a 0.10 release, so for adding and deprecating API this is the best time.
