### ISSUE TITLE
[RFC] Create a module that can compile and run Ammonite scripts and use it for Mill itself

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#1675]
This related to https://github.com/com-lihaoyi/Ammonite/issues/1228, which is worth a full read to understand the motivation

We need a module, that can 

* read an Ammonite or scala-cli script,
* inspect it's magic imports,
* collects all included files (when Ammonite script),
* resolved it's dependencies (in one go),
* compiles all files,
* and provided a way to run the script
  * as Ammonite script
  * as Mill script
  * as scala-cli script

Once this is ready, we can stop using Ammonite for all of these tasks and can use this module to provide better BSP support.

**Comment by hilcode** [comment]
Seems like a good idea. The less magic, the better.

**Comment by lefou** [comment]
It might be worth to evaluate, if we can adapt the `using` directive (https://scala-cli.virtuslab.org/docs/guides/configuration#in-scala-and-sc-files) from Scala-cli for Mill build scripts. It seems to be much easier to parse them from Mill.

**Comment by lefou** [comment]
* #2377 
* #2414

**Comment by lefou** [comment]
Closing as completed. Although Mill build scripts are no longer Ammonite scripts since then, we build Mill scripts now with a `MillBuildModule`.
