### ISSUE TITLE
Mill does not work with fish

### ISSUE THREAD

**Issue by Xusine1131** [com-lihaoyi/mill#1686]
I am using [fish](https://github.com/fish-shell/fish-shell) as my primary shell and fish is not compatible with bash and zsh. I got an error message like the following:
```sh
$ mill
Error: Could not find or load main class mill.main.client.MillClientMain
Caused by: java.lang.ClassNotFoundException: mill.main.client.MillClientMain
```
When I use zsh it works normally. My operating system is Linux and the version of fish is 3.3.1, and the version of zsh is 5.8

**Comment by lefou** [comment]
How do you have it installed? Which version is it?

**Comment by Xusine1131** [comment]
@lefou I am using Archlinux so it comes from the community repo. I install it directly with pacman. The version is 0.10.0

**Comment by lefou** [comment]
Sorry, I've no idea what "mill" is then. You may want to open an issue in the community repo if it doesn't work out of the box.

The "official" mill start script should be "sh" compatible. 

My personal (biased) recommendation is https://com-lihaoyi.github.io/mill/mill/Intro_to_Mill.html#_millw.

**Comment by Xusine1131** [comment]
@lefou FYI, I tried the manually installed version (with curl fetching the script) and it works, and I guess it might be a bug of packing. I will open a bug at that point and thanks!
