### ISSUE TITLE
Support Scala 3 compiler plugins

### ISSUE THREAD

**Issue by lolgab** [com-lihaoyi/mill#1691]
Scala 3 plugins are different from Scala 2 plugins.
https://docs.scala-lang.org/scala3/reference/changed-features/compiler-plugins.html

Trying to update Scala Native to Scala 3 in Utest ( which uses a compiler plugin ) failed with this log:
[message.txt](https://github.com/com-lihaoyi/mill/files/7918658/message.txt)

It was suggested in the Scala Native discord that:
> It looks like -Xplugin:path points to something which is not a compiler plugin
In Scala2 there was a xml file describing plugin, in Scala 3 there is plugin.properties file

It seems that Mill adds `-Xplugin` to all the jars in the plugin classpath, while Scala 3 seems to require this to be passed only in the plugin jar.

**Comment by lefou** [comment]
See this related issue #1690, with an extended discussion about plugin handling in MIll.

**Comment by lolgab** [comment]
Thank you!
So this is another problem which is also happening in Scala 2!

**Comment by lefou** [comment]
Yes, our current handling for scalac plugins is incorrect. I outlined two solutions here https://github.com/com-lihaoyi/mill/issues/1690#issuecomment-1019326117, and I would value your thoughs / expertise, @lolgab .

Quoting it here for completeness:
> Maybe, we are not supposed to resolve compiler plugins transitively? I could not find any information about this in the scala documentation. (We, @ckipp01 and me, also spoke about this before in context of scoverage plugin.) I think most plugins do not require additional dependencies but that's just a guess. The best transitive dependency mapping for compiler plugins would be to declare all API dependencies, which should be provided by the compiler itself (like scala library jar and compiler jar) as Maven provided scope, or in Mill speak as compile-only dependencies. Unfortunately we don't have control over this so I see two options to improve the situation:
> 
> 1. Never resolve compiler plugins transitively. This is essentially the same as providing each with `.exclude("*" -> "*")`. This will change behavior, as the resulting compiler classpath is likely smaller. This change might break compilations. It looks like this is what sbt does (from your given example above).
> 
> 2. Only generate `-Xplugin` options from the directly listed ivy deps but still provide all transitive dependencies as compiler classpath. This will only generate less options, which seems the right thing to do but still provides all declared transitive dependencies. This will not break currently succeeding compilations, but might still violate the expectation of the compiler, as we potentially provide to much (conflicting) dependencies.

**Comment by lefou** [comment]
I'm looking this conversation, as the discussion takes place at #1690. After we fixed it, this one is likely also fixed. If not, I'm unlocking it again.

**Comment by lefou** [comment]
I opened PR #1705 which should fix this issue. A review and ideally a local test would be great.
