### ISSUE TITLE
Auto detection of test frameworks

### ISSUE THREAD

**Issue by rockjam** [com-lihaoyi/mill#170]
If I remember correctly, sbt does automatic test framework detection based on dependencies in classpath. We should probably do the same thing.

**Comment by lihaoyi** [comment]
Looks like SBT just hardcodes a list of frameworks and uses them all the time

https://github.com/sbt/sbt-zero-thirteen/blob/069865794d295ae0a2a64bd534714eba831aac36/main/src/main/scala/sbt/Defaults.scala#L451

Shouldn't be hard for us to do the same

**Comment by rockjam** [comment]
Didn't know that they are hard coded. Well, it makes it easier this way.

**Comment by jastice** [comment]
Gotcha I ran into with sbt: sbt tries to use all the test frameworks detected in a project on every test class, even when using `testOnly`. Passing command line params intended for a specific framework will break the test run in this case. Hopefully this can be avoided in mill :)

**Comment by lihaoyi** [comment]
I've definitely hit the case where passing arguments into the test framework makes another framework fail to parse... maybe we should just document which framework to use and expect people to choose them explicitly?

Given that we support running multiple test frameworks already, I'm not sure what Mill's behavior is when arguments to one framework fail to parse for another

**Comment by jastice** [comment]
In sbt it's non-trivial to select the framework manually (need to mess with the `testFrameworks` setting). If it was easier in mill to pass the appropriate framework as an argument to the test run, that could make support from IntelliJ more smooth down the road.

**Comment by lihaoyi** [comment]
Given Mill trivially supports multiple test modules, I suspect the best way to let people select the appropriate test framework is just to say "put the different test framework tests in different test modules". Then you can pick which test module to run and pass args appropriately

**Comment by sake92** [comment]
Maven's Surefire also had issues with this: https://issues.apache.org/jira/browse/SUREFIRE-377
It seems that framework-per-module is the cleanest solution.  
Would that mean refactoring `testFrameworks: Seq[String]` to be `testFramework: String`? @lihaoyi @lefou ?

**Comment by lefou** [comment]
> Would that mean refactoring `testFrameworks: Seq[String]` to be `testFramework: String`?

Yes! I also think, we should provide some ready to use traits for common test frameworks for easier consumption.

e.g. the best support for testng is via out own `TestFramework` implementation, which is really hard to use right now:

```scala
trait TestNg extends TestModule {
  override def testFramework: T[String] = "mill.testng.TestNGFramework"
  override def ivyDeps: T[Loose.Agg[Dep]] = super.ivyDeps() ++ Agg(
    ivy"com.lihaoyi:mill-contrib-testng_2.13:${mill.BuildInfo.millVersion}"
  )
}
```

**Comment by lefou** [comment]
In conclusion, explicit selection of a single test framework is the most desired features. So auto-detection is from the table.
