### ISSUE TITLE
Mill 0.10.0: `IO error while decoding .DS_Store with UTF-8: MALFORMED`

### ISSUE THREAD

**Issue by davesmith00000** [com-lihaoyi/mill#1707]
During local publishing I'm getting a new 'error' since upgrading to Mill `0.10.0`.

Happens consistently on every project/artefact, and although reported as an error (see below), it doesn't seem to actually affect anything.

```
Publishing Artifact((..)) to ivy repo /Users/(..)/.ivy2/local
[39/60] <project>.publishVersion
[49/60] <project>.docJar
error: IO error while decoding /Users/(..)/<project>/src/.DS_Store with UTF-8: MALFORMED[1]
Please try specifying another one using the -encoding option
```

Just thought I'd mention it since it seems to be new and presumably unexpected.

**Comment by Sailsman63** [comment]
Is this always during the `.docJar` phase?

`.DS_Store` is a mac-specific file - it's the memory of directory-layout options, etc. It should definitely be ignored, as probably should any other dotfiles?

**Comment by lefou** [comment]
We typically ignore `.`-prefixed files when processing sources; maybe there is a code path in `docJar`, where this is forgotten.

**Comment by davesmith00000** [comment]
Hi, I've tested it again and yes, I myself can only see it happening at the `docJar` phase.

**Comment by davesmith00000** [comment]
@lefou I noticed that the PR had been merged to main, so I tested from main. Your fix appears to have worked perfectly, I am no longer seeing the error. 🎉 

Also I must say how pleasantly surprised I was at how easy and quick local testing of Mill was - tip of the hat to the team for that one! 💪 

Thanks!
