### ISSUE TITLE
Support Scala.js linker config `OutputPatterns`

### ISSUE THREAD

**Issue by shishkin** [com-lihaoyi/mill#1721]
In order to be able to run `ESModule`s on Node without tinkering with `package.json`, linker output needs to have `.mjs` extension instead of `.js`. Scala.js linker supports this via [`OutputPatterns`](https://www.scala-js.org/doc/project/module.html#es-modules-and-nodejs). Mill `ScalaJSModule` doesn't expose that config in its API.

Also, would it make sense to expose Scala.js linker API directly instead of the current facade API?

**Comment by lolgab** [comment]
> Also, would it make sense to expose Scala.js linker API directly instead of the current facade API?

This is not possible because we need to support multiple versions of Scala.js and by depending on it directly you lose this property.
