### ISSUE TITLE
Mill fails to evaluate task for specific Scala snapshot version

### ISSUE THREAD

**Issue by WojciechMazur** [com-lihaoyi/mill#1730]
Hey, I'm currently working on an unmanaged community build for Scala, an enhancement to the current Dotty community build that is not going to be maintained by the Dotty team (eg. by adjusting builds, forking projects or applying fixes). 
While working on Mill support I've found an issue when trying to use a specific Scala version, as an example let's use `requests` library 

When running resolve I get expected output for available cross versions 
```
> mill resolve 'requests._'
[1/1] resolve 
Use cross-version 3.1.3-RC1-bin-df045ea75ab492c88beb146a3184340830278101-COMMUNITY-BUILD instead of 3.0.0
requests[2.11.12]
requests[2.12.13]
requests[2.13.5]
requests[3.1.3-RC1-bin-df045ea75ab492c88beb146a3184340830278101-COMMUNITY-BUILD]
```
Also trying to resolve compile task seems to return the correct result 
```
> mill resolve requests[3.1.3-RC1-bin-df045ea75ab492c88beb146a3184340830278101-COMMUNITY-BUILD].compile
[1/1] resolve 
requests[3.1.3-RC1-bin-df045ea75ab492c88beb146a3184340830278101-COMMUNITY-BUILD].compile
```
It can be also found when using mill internal API 

However, when I would try to run execute this task I would get an exception 
```
> mill show requests[3.1.3-RC1-bin-df045ea75ab492c88beb146a3184340830278101-COMMUNITY-BUILD].compile
[1/1] show 
[1/1] show > [27/27] requests[3.1.3-RC1-bin-df045ea75ab492c88beb146a3184340830278101-COMMUNITY-BUILD].compile 
1 targets failed
show 1 targets failed
requests[3.1.3-RC1-bin-df045ea75ab492c88beb146a3184340830278101-COMMUNITY-BUILD].compile java.util.NoSuchElementException: None.get
    scala.None$.get(Option.scala:627)
    scala.None$.get(Option.scala:626)
    mill.scalalib.ZincWorkerModule.$anonfun$worker$5(ZincWorkerModule.scala:38)
    mill.scalalib.worker.ZincWorkerImpl.compileBridgeIfNeeded(ZincWorkerImpl.scala:205)
    mill.scalalib.worker.ZincWorkerImpl.withCompilers(ZincWorkerImpl.scala:360)
    mill.scalalib.worker.ZincWorkerImpl.compileMixed0(ZincWorkerImpl.scala:310)
    mill.scalalib.worker.ZincWorkerImpl.compileMixed(ZincWorkerImpl.scala:280)
    mill.scalalib.ScalaModule.$anonfun$compile$2(ScalaModule.scala:174)
    mill.define.ApplyerGenerated.$anonfun$zipMap$9(ApplicativeGenerated.scala:21)
    mill.define.Task$MappedDest.evaluate(Task.scala:396)
```

In the case of simple, stable Scala versions (eg. 3.1.2-RC1) it works just fine

Tested with mill 0.9.12

**Comment by lefou** [comment]
Have you tried without "show"?

**Comment by lefou** [comment]
Also, it might be important to properly quote the expression, depending on your shell. E.g. fish is known to be picky.

**Comment by WojciechMazur** [comment]
Usage with quoted expression and without show gives the same results. Also, presented shell commands are you an easy reproducer. Actual code is using mill internals (evaluator with resolved tasks) to execute commands so it also should not interfere in the results.

**Comment by lefou** [comment]
Ah, now I see. Is this exact version available via your configured repositories and when yes, which? Or did you install it (publishLocal) into your local ivy repository before. Can you provide a listing of the relevant local ivy cache, esp. the `scala3-sbt-bridge`? Can you share your `build.sc`? 

I think the issue could be in `ZincWorkerApi.isBinaryBridgeAvailable` where we have various patterns for Scala versions, but non matches your given version. One fix could be to add your pattern, but I think the better fix would be to enhance `ScalaModule` to let it specify some more compiler details like the interface and whether it is available as binary or as source.

**Comment by WojciechMazur** [comment]
I'm using a custom maven repository to which I'm publishing Scala/library artifacts. Overall` build.sc` is the same as in the original repo or upickle, requests or other lihaoyi stack library, with a few exceptions: 
* We override Scala 3 version, for debug purpose all it's needed is to manually replace current Scala 3 version 
* We register our custom maven repo by replacing all usages of `PublishModule` with a custom  class that extends it and overrides repositories using following snippet (we make sure to make a custom repo appear first in the lookup)
```override def repositoriesTask: Task[Seq[Repository]] = T.task {
    MavenRepository(mavenRepoUrl) +: super.repositoriesTask()
  } 
  ```

Actually `isBinaryBridgeAvailable` and other regexes are matching this specific version. However, I've found a mysterious behaviour. 
The failure happens at this line https://github.com/com-lihaoyi/mill/blob/3f4dbfa3e0a4af018262d729501a247b94011fef/scalalib/src/ZincWorkerModule.scala#L65 (it's the same in the current main branch)

When I would try to run mill repl and would use the following snippet it works correctly
```
> val m = core.jvm("3.1.3-RC1-CB") 
m: core.CoreJvmModule = ammonite.predef.build#core.jvm:190

> m.zincWorker.scalaCompilerBridgeJar(m.scalaVersion(), m.scalaOrganization(), m.repositoriesTask()) 
res60: mill.api.Result[(Option[Array[os.Path]], os.Path)] = Success(
  value = (None, /root/.cache/coursier/v1/https/mvn-repo%3A8081/maven2/2022-02-04_9/org/scala-lang/scala3-sbt-bridge/3.1.3-RC1-CB/scala3-sbt-bridge-3.1.3-RC1-CB.jar)
)
```

However, further usage `m.compile()` leads to errors in the same way as before. 

As you can from the output I'm using a custom maven repo, this entry is present in `m.repositoriesTask()` 
Do you think it's possible that the worker is using different repositories?

**Comment by WojciechMazur** [comment]
Indeed ZincWorker does define only default  `repositoriesTask()` and is not able to find artifacts from the custom repo. Is there maybe some easy way to overwrite repositoriesTask() in ZincWorker? I would be great if we could define some global settings, but otherwise, I can try to overwrite it. 

```
> m.zincWorker.asInstanceOf[mill.scalalib.CoursierModule].repositoriesTask().map(_.repr).foreach(println) 
ivy:file:/root/.ivy2/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
https://repo1.maven.org/maven2

```

**Comment by lefou** [comment]
Exactly this could be the issue. ... oh, you were faster...

For info how to configure the zinc worker read this: https://com-lihaoyi.github.io/mill/mill/Configuring_Mill.html#_repository_configuration

**Comment by WojciechMazur** [comment]
The solution for the issue would be carefully read the docs ;) 
I'm going to use second part of this paragraph and overwrite the repo in ZincWorker by custom worker, described here https://com-lihaoyi.github.io/mill/mill/Configuring_Mill.html#_repository_configuration 

As I was going to hit comment, I've seen your comment. Thank you for your help! I will close this issue now.

**Comment by lefou** [comment]
I still wonder if we can't provide a better error message in this case.
