### ISSUE TITLE
Support Scala 3 `-Yscala-output-version` flag

### ISSUE THREAD

**Issue by lolgab** [com-lihaoyi/mill#1762]
The new `-Yscala-release` requires special build tool support.

This is a problem Sbt is also facing: https://github.com/sbt/sbt/pull/6814
Scala community discussion: https://contributors.scala-lang.org/t/improving-scala-3-forward-compatibility/5298/22

Possible solution in `ScalaModule` (inspired by the discussion in the Sbt Issue):
```scala
def scalaOutputVersion: T[String] = T { scalaVersion() }
def scalaVersion: T[String]
def mandatoryScalacOptions: T[Seq[String]] = T {
  if(scalaBinaryVersion(scalaVersion()) != scalaBinaryVersion(scalaOutputVersion())) Seq("-Yscala-release", scalaBinaryVersion(scalaOutputVersion()))
  else Seq.empty[String]
}
```

**Comment by lefou** [comment]
Sounds reasonable to me.

**Comment by prolativ** [comment]
The flag will be renamed to `-scala-output-version` starting from 3.1.2-RC2.
I seem to have a working implementation https://github.com/com-lihaoyi/mill/pull/1764 but it needs to wait for 3.1.2-RC2 and I would like to align it with the implementation for sbt to make sure the behaviour of the setting are possibly the same no matter what build tool a user chooses but it seems not so easy to achieve exactly the same semantics in sbt regarding which version of the standard library gets used at runtime.

**Comment by lolgab** [comment]
Since the compiler team decided to drop the `-scala-output-version` flag we don't need to support it anymore.
https://github.com/lampepfl/dotty/pull/15146
