### ISSUE TITLE
mill show __.task produces invalid json

### ISSUE THREAD

**Issue by daddykotex** [com-lihaoyi/mill#1763]
Hey! Thanks for mill, its great.

I found some information on gitter but not exactly what I'm looking for so I'm opening this so it can serve as a documentation reference if I'm not the only one that tries to do this.

I have a build with multiple modules being published to a repository. I want to produce a list of all the artifact coordinates that are generated. So, naturally, I went with the following approach:

`mill show __.artifactMetdata`

`artifactMetadata` definition is : `def artifactMetadata: Target[Artifact]`.
`Artifact` looks like: `case class Artifact(group: String, id: String, version: String)`

And so the result is: 
```json
{
    "group": "com.acme",
    "id": "pkg1",
    "version": "1.0.0"
}
{
    "group": "com.acme",
    "id": "pkg2",
    "version": "1.0.0"
}
```

It's fine, that's exactly what I need, but you can't pipe that into another tool. IMO, there are a few solutions:

- use Newline Delimited JSON (that's what we have here), but do not prettify the JSON, so each object is one line
- wrap the whole thing in an Array it's a valid JSON
- implement a command to do that (suggested in gitter)

I have written this implementation, and it works, but I find it kinda ugly and I don't like that it's relying on on an [experimental feature](https://com-lihaoyi.github.io/mill/mill/Extending_Mill.html#_evaluator_commands_experimental):

```scala
import mill.scalalib._
import mill.eval.Evaluator
import mill.api.Result

import scala.util.control.NonFatal

def allPublishedArtifacts(ev: Evaluator): mill.define.Command[Seq[Artifact]] =
  T.command {
    try {
      val artMeta = ev.rootModule.millInternal.segmentsToModules.values
        .collect { case x: scalalib.PublishModule => x }
        .map { _.artifactMetadata }
        .toSeq

      Result.Success(Evaluator.evalOrThrow(ev)(artMeta))
    } catch {
      case NonFatal(e) =>
        Result.Exception(
          e,
          new Result.OuterStack(new java.lang.Exception().getStackTrace)
        )
    }
  }
```

Is there an alternative to `mill show __.artifactMetadata` that would produce an output directly usable via another tool?

Is there a better way to implement a command where I need to find all modules of a given type (`PublishModule`) and run a target (`artifactMetadata`) on that type?

Thanks

**Comment by lefou** [comment]
I read your issue as two (unrelated) improvements requests:

1. make `mill show` always return valid output
2. Add support to select targets based on their (return) type

to 1.: This is actually a very good finding and I think we can make implement that rather easy. It is IMO essential to provide some stable output, so best is to always return an JSON array. Each element count be the output of a selected task. We could also add the task name, to make the output even more informative and import usage by downstream tools.

Example output:

```json
[
  "pkg1.artifactMetadata":
  {
      "group": "com.acme",
      "id": "pkg1",
      "version": "1.0.0"
  },
  "pkg2.artifctMetadata":
  {
      "group": "com.acme",
      "id": "pkg2",
      "version": "1.0.0"
  }
]
```

to 2.: This is actually not possible but we already discussed this idea in the chat and came to the conclusion that selecting by type would be very useful, for modules and for targets. We need to find a good syntax though. I have something like this in mind:

```shell
mill show (__:mill.scalalib.PublishModule).artifactMetadata
# or
mill show __.(_:mill.scalalib.publish.Artifact)
```

We need to make sure we find something that does not collide with the shell interpretation.

**Comment by daddykotex** [comment]
I'd be happy to work on 1.

I figured it's what made the most sense
