### ISSUE TITLE
README.md should include a link to scaladoc

### ISSUE THREAD

**Issue by tfenne** [com-lihaoyi/mill#1783]
It took me way longer than it should have to find the scaladoc for the pieces of mill that are useful when writing a build file.  I eventually got to https://www.javadoc.io/doc/com.lihaoyi/mill-scalalib_2.13 after looking through the vast number of modules/packages that are published by mill.  It would be really nice if in both the README and the mill docs there was a link out to this scaladoc, and possibly other module's scaladocs that are useful as _users_ of mill.

**Comment by lefou** [comment]
This is related to

* https://github.com/com-lihaoyi/mill/discussions/1750

Once, we have a way to aggregate API docs, we can provide a nice link. Until then, Multiple ScalaDoc sites without cross referencing each other are barely usable. 

I just want to point out, that once you open your `build.sc` in an IDE (IntelliJ or any BSP client, see https://com-lihaoyi.github.io/mill/mill/Intro_to_Mill.html#_ide_support) you can browse the Mill API through the sources. That's probably the reason, nobody really missed the API docs.

**Comment by lihaoyi** [comment]
Should be fixed by Should be fixed by https://github.com/com-lihaoyi/mill/pull/2448, which introduces `mill.scalalib.UnidocModule`

**Comment by lefou** [comment]
We now also have a prominent link to the "API" from the top of our documentation site.
