### ISSUE TITLE
Bad Repl shutdown

### ISSUE THREAD

**Issue by ajrnz** [com-lihaoyi/mill#1795]
Affects 0.10.2 (also 0.10.2-3-83fd03), linux and MacOS

Reproduce:

      ajr@xxx:~/temp/mill$ mkdir test
      ajr@xxx:~/temp/mill$ cd test
      ajr@xxx:~/temp/mill/test$ touch build.sc
      ajr@xxx:~/temp/mill/test$ mill --repl
      Loading...
      Compiling /home/ajr/temp/mill/test/build.sc
      Compiling /home/ajr/temp/mill/test/(console)
      Mill Build Tool, version 0.10.2
      @ Bye!

works the first time Ctrl-D to quit and try again

      ajr@xxx:~/temp/mill/test$ mill --repl
      Loading...
      Mill Build Tool, version 0.10.2
      /bin/stty: 'standard input': Input/output error
      /bin/stty: 'standard input': Input/output error
      java.lang.RuntimeException: Nonzero exit value: 1
        scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:164)
        scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:121)
        ammonite.terminal.TTY$.stty(Utils.scala:103)
        ammonite.terminal.TTY$.withSttyOverride(Utils.scala:119)
        ammonite.terminal.Terminal$.readLine(Terminal.scala:41)
        ammonite.repl.AmmoniteFrontEnd.readLine(AmmoniteFrontEnd.scala:133)
        ammonite.repl.AmmoniteFrontEnd.action(AmmoniteFrontEnd.scala:28)
        ammonite.repl.Repl.$anonfun$action$4(Repl.scala:194)
        ammonite.repl.Scoped.$anonfun$flatMap$1(Signaller.scala:45)
        ammonite.repl.Signaller.apply(Signaller.scala:28)
        ammonite.repl.Scoped.flatMap(Signaller.scala:45)
        ammonite.repl.Scoped.flatMap$(Signaller.scala:45)
        ammonite.repl.Signaller.flatMap(Signaller.scala:16)
        ammonite.repl.Repl.$anonfun$action$2(Repl.scala:178)
        ammonite.util.Catching.flatMap(Res.scala:115)
        ammonite.repl.Repl.action(Repl.scala:170)
        ammonite.repl.Repl.loop$1(Repl.scala:212)
        ammonite.repl.Repl.run(Repl.scala:227)
        ammonite.Main.$anonfun$run$1(Main.scala:236)
        scala.Option.getOrElse(Option.scala:201)
        ammonite.Main.run(Main.scala:224)
        mill.MillMain$.$anonfun$main0$5(MillMain.scala:238)
        ammonite.MainRunner.watchLoop(MainRunner.scala:53)
        mill.MillMain$.main0(MillMain.scala:238)
        mill.main.MillServerMain$.main0(MillServerMain.scala:78)
        mill.main.Server.$anonfun$handleRun$1(MillServerMain.scala:193)
        java.lang.Thread.run(Thread.java:829)
       ... <this is repeated>

The first attempt leaves a mill process lying around (which if you kill solves the problem). [I was under the impression that with `-i` or `--repl` there was no server process?]

So it looks like some kind of shutdown issue with the repl.

**Comment by lefou** [comment]
Thanks for your report. We've seen other weird behavior in Mill 0.10 with sub-processed which keep running although they were meant to stop. I think we introduced some bug in the 0.10 Milestone phase, most probably when we migrated our watch mode to Ammonites watch support.

**Comment by megri** [comment]
I'm also seeing this problem. The broken run seems to kill off the remaining millserver though, so every other `mill --repl` works.

**Comment by lefou** [comment]
This is a bug in argument parsing (in the Java part) and should be fixed by #1871.
