### ISSUE TITLE
Ergonomics improvement when generating custom manifest: strip trailing whitespace from inputs

### ISSUE THREAD

**Issue by Sailsman63** [com-lihaoyi/mill#1796]
`mill.modules.Jvm.JarManifest.add()` should strip trailing whitespace on input strings.

I recently spent a couple of hours running in circles trying to understand why my `.jar` would crash on launch with a very unhelpful error message. It turned out that one of my Manifest entries (generated by an `os.proc().call()`) was (unexpectedly) ending with an "\n" character.

The workaround is simple enough: add `.stripTrailing()` to the end of the call that generates the String. However, since *any* extra whitespace is at best extraneous, and can easily cause an invalid manifest, I feel that it would make more sense to handle this in `mill.modules.Jvm.JarManifest`

**Comment by lefou** [comment]
I don't think this is the right move. Once we strip trailing whitespaces, there is no way to add entries which should contain some. I worked with Manifest a lot in the past and have seen a lot of different content, so I'd rather not make any assumption about the users needs.

If you feed external output into your manifest, you should just make sure that your input is valid or sanitized.

**Comment by Sailsman63** [comment]
> Once we strip trailing whitespaces, there is no way to add entries which should contain some.

Huh... I'm a bit skeptical, but okay.
