### ISSUE TITLE
cannot find  build.sc

### ISSUE THREAD

**Issue by pxs7** [com-lihaoyi/mill#1884]
when just set HOME and  PATH=mill install path，  the following comes out

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 60.3M  100 60.3M    0     0  3671k      0  0:00:16  0:00:16 --:--:-- 4031k
No build file found, you should create build.sc to do something useful
Compiling /home/yifmo01/workspace/test/berkeley-hardfloat/build.sc
Cannot resolve hardfloat. Try `mill resolve _` to see what's available.

why mill cannot find  build.sc，  any enrichment variable needed to be set？

**Comment by lefou** [comment]
What platform? Which Mill version? What is installed in your `$PATH`, a mill script or binary? Do you have a local `.mill-version` file? 

Please try to write at human readable ticket. Markdown has code/listing markers. 

Can you post your `mill --version`?

**Comment by pxs7** [comment]
> What platform? Which Mill version? What is installed in your `$PATH`, a mill script or binary? Do you have a local `.mill-version` file?
> 
> Please try to write a human readable ticket. Markdown has code/listing markers.
> 
> Can you post your `mill --version`?
when use mill -v 
shim hash open(out/mill-worker-Npk3n49xqDc86mA4/WF+3pDfQ38=-1/io): No such device or address

**Comment by pxs7** [comment]
i use it in linux  redhat 7

**Comment by pxs7** [comment]
some actions were not right to cause such  problems

**Comment by lefou** [comment]
Dear @psx7, I simple don't understand what you are trying to say. You posted some error but no context, no clear sentences, no formatting, only cryptic words. It's neither helpful nor polite. The needed amount of work needed to understand what you're trying to say and to help on that thin data is unequally higher than the effort you put into opening this issue. Please elaborate.
