### ISSUE TITLE
Mill sometimes prompt the print popup in MacOS.

### ISSUE THREAD

**Issue by jilen** [com-lihaoyi/mill#1896]
<img width="757" alt="Screen Shot 2022-06-11 at 18 35 37" src="https://user-images.githubusercontent.com/546573/173184906-fc88e83c-1c44-498f-acc8-bd67d13f4af0.png">

I can confirm mill will prompt a print window while building.
I notice there are invalid char inside log.  This might be related to charset encoding or output formatting
And this might also be related to parallel building.

**Comment by jilen** [comment]
The build going on after I close the print popup manually.

**Comment by lefou** [comment]
That's probably some side effect of interfering output streams producing control sequences which your shell is interpreting. I guess, there is not much we can do about it. 

If you disagree, please provide more info how to reproduce it. Start with describing your environment (OS, shell, Java version, mill version) and the concrete action to reproduce.

**Comment by jilen** [comment]
@lefou I agree.
