### ISSUE TITLE
`jvm-opts` not working with server mode.

### ISSUE THREAD

**Issue by jilen** [com-lihaoyi/mill#1908]
Options defined in `.mill-jvm-opts`  not picked unlsess `--no-server` is specified.

`macro` expansion or `shapeless` based staff requires large stack size. But set `-Xss` in `.mill-jvm-opts` not working.

**Comment by lefou** [comment]
Do you have a small reproducer for this, by any chance? Or an idea, or some example of a code snippet known to need a high `-Xss` setting?

**Comment by jilen** [comment]
```scala
import java.lang.management._
val runtimeMxBean = ManagementFactory.getRuntimeMXBean()
val arguments = runtimeMxBean.getInputArguments()
```
I tried print the vm args in the `ZincWorkImpl` using java management api. And the options defined `.mill-jvm-opts` only seen while `--no-server` specified.

**Comment by lhns** [comment]
Moved to https://github.com/com-lihaoyi/mill/issues/5555
