### ISSUE TITLE
Mill does not apply reformat or fix to test files

### ISSUE THREAD

**Issue by carlosedp** [com-lihaoyi/mill#1934]
I have a scala 3 project and when I run scalafmt (using `reformat`) or `fix` from scalafix (using the [plugin](https://github.com/joan38/mill-scalafix)), mill is not applying to my test files in `prjnames/test/src` dir

This is my tree:

```sh
❯ tree
[ 51K]  ./
├── [1.4K]  backend/
│   ├── [ 483]  src/
│   │   └── [ 355]  Main.scala
│   └── [ 802]  test/
│       └── [ 674]  src/
│           └── [ 578]  MainSpec.scala
├── [3.1K]  frontend/
│   ├── [1.2K]  src/
│   │   └── [1.1K]  FrontEnd.scala
│   ├── [1.2K]  test/
│   │   └── [1.1K]  src/
│   │       └── [ 987]  FrontEndSpec.scala
│   └── [ 541]  ui/
│       └── [ 445]  html/
│           └── [ 349]  index.html
├── [ 258]  project/
│   └── [ 162]  metals.sbt
├── [3.5K]  build.sc
├── [1.7K]  mill*
├── [ 40K]  package-lock.json
└── [ 580]  package.json
  51K used in 11 directories, 10 files
```

Running:

```sh
❯ mill frontend.fix --verbose
[46/46] frontend.fix
Rewriting and linting 1 Scala sources against 5 rules
info: Processing (0/1) /Users/cdepaula/repos/scala-playground/zio-scalajs-stack/frontend/src/FrontEnd.scala
```

I also tried running for the test project directly but also the files were not found:

```sh
❯ mill __.fix --verbose
[75/119] backend.fix
Rewriting and linting 1 Scala sources against 5 rules
info: Processing (0/1) /Users/cdepaula/repos/scala-playground/zio-scalajs-stack/backend/src/Main.scala
[119/119] frontend.fix
Rewriting and linting 1 Scala sources against 5 rules
info: Processing (0/1) /Users/cdepaula/repos/scala-playground/zio-scalajs-stack/frontend/src/FrontEnd.scala


❯ mill frontend.test.fix
Cannot resolve frontend.test.fix. Try mill resolve frontend.test._ to see whats available.
❯ mill frontend.test.reformat
Cannot resolve frontend.test.reformat. Try mill resolve frontend.test._ to see whats available.
```

It doesn't see the `FrontEndSpec.scala` file... same happens to frontend.reformat.

on the other side, if I run `mill mill.scalalib.scalafmt.ScalafmtModule/reformatAll __.sources`, it reformats the source and test files

My `build.sc` file is at: <https://github.com/carlosedp/zio-scalajs-stack/blob/main/build.sc>

Thanks

**Comment by lefou** [comment]
This is related to `ScalafixModule` which comes from Mill plugin https://github.com/joan38/mill-scalafix. 

If you want to use the `reformat` target in a module, you need to extend the `ScalafmtModule`. I assume, you forget to add it to your tests, which should/might look like this:

```scala
object test extends Tests with ScalafmtModule
```

See also my comments in the Gitter chat: https://gitter.im/lihaoyi/mill?at=62cc382f0a5226479806d806

**Comment by carlosedp** [comment]
I ended up organizing my traits and importing relevant options from common traits in my project as seen in https://github.com/carlosedp/zio-scalajs-stack/blob/main/build.sc
Thanks @lefou

**Comment by lefou** [comment]
> So I understand I have to redefine in my test object all things I have in the "parent" project like importing the traits (scalafmt, scalafix), adding organize-imports, disabling semanticdb by scalacoptions and so on?
> 
> It's quite repetitive... isn't there a way to "inherit" from the parent project settings?
> 
> Thanks!

The most idiomatic approach in Scala and thus in Mill is to create one or many "common" traits which define your module stereotypes. Then only use these to define your modules. You can find this pattern in almost all projects, which have more than two or three modules (including Mill). It's rather natural to the OOP developer and the most intuitive way to comprehend a modules characteristics.

See also the section about [Using Modules](https://com-lihaoyi.github.io/mill/mill/Modules.html#_using_modules) in the documentation.

If you think (or observe a pattern) that tests always should use the same scalafix settings, you should probably open a discussion, issue or pull request in the mill-scalafix project.
