### ISSUE TITLE
Multiple duplicate help flags

### ISSUE THREAD

**Issue by ckipp01** [com-lihaoyi/mill#1952]
On the latest mill if you do a `mill --help` you'll notice there are multiple help flags that are duplicated and some conflicting. Here are a few:

_This is in there twice, the same both times_
```
 -h --home <path>     The home directory of the REPL; where it looks for config and caches
```

_This flag is in there twice with different descriptions_
```
--bsp                Run a BSP server against the passed scripts
--bsp                Enable BSP server mode.
```

_This one is in there twice with conflicting descriptions_
```
-v --version         Show Ammonite's version
-v --version         Show mill version and exit.
```

**Comment by lefou** [comment]
Interesting. I think, those were not present before. Maybe a consequence of a mainargs library bump. 

I think we should not inherit the args of Ammonite, but duplicate and wrap them. Essentially, we don't want all of Ammonites CLI flags, some are totally unsupported (e.g. `thin`) and other have different meaning (`bsp`).
