### ISSUE TITLE
`args` in testOnly not working.

### ISSUE THREAD

**Issue by jilen** [com-lihaoyi/mill#1957]
```scala
trait SbtTestBase extends Tests with TestModule.ScalaTest {

    protected val predefiedArgs = s"-Dmodule.base.dir=${millSourcePath}"

    override def testOnly(args: String*) = {
      super.testOnly((predefiedArgs +: args): _*)
    }

    override def test(args: String*) = {
      super.test((predefiedArgs +: args): _*)
    }
  }
```

Passing args to `testOnly` not working, but `test` works.
Note, the test args can be accessed via scalatest [ConfigMapFixture](https://www.scalatest.org/scaladoc/3.0.8/org/scalatest/fixture/ConfigMapFixture.html)

**Comment by lefou** [comment]
Can you please describe your args, what you expect and the actually (unexpected) output of Mill?

`TestModule.testOnly` expects the args to be wildcard selectors, and only after a `--` it accepts args to be passed to the test framework.

**Comment by jilen** [comment]
Hm, scalatest accept custom args like `-Dfoo=bar`, then it can be accessed via `ConfigMap` in suite.

**Comment by lefou** [comment]
If you have some args `myArg` that works for you with `test`:

```
mill myModule.test.test myArg
```

than it should also work with `testOnly`: 

```
mill myModule.test.testOnly my.test.suite -- myArg
```

**Comment by lefou** [comment]
There is a issue with your `predefinedArgs`. Either you specify the `--` on the cli or you add it to your `predefinedArgs`.

**Comment by jilen** [comment]
@lefou Thanks, let me have a try.

**Comment by jilen** [comment]
It works! Thanks again
