### ISSUE TITLE
Use of ScalaMetalsSupport results in scalac error - bad option

### ISSUE THREAD

**Issue by ghostbuster91** [com-lihaoyi/mill#1967]
Hi, 
I am trying to setup some scalafix rules in my project that require SemanticDB synthetics to work properly. I couldn't figure out a way how to pass `-P:semanticdb:synthetics:on` to the compiler as simply specifying it in scalacOptions was giving me following error:
```
[error] bad option: -P:semanticdb:synthetics:on
[error] one error found
1 targets failed
core.compile Compilation failed 
```

After poking around mill repository I found `ScalaMetalsSupport` which is supposed to enable synthetic rules as they are required for metals to work. 

However mixing that trait into my main module didn't fix the issue and I got another error: 
``` 
[error] bad option: -P:semanticdb:sourceroot:/home/kghost/dev/myproject
[error] one error found
1 targets failed
core.compile Compilation failed
```

I use mill 0.10.5 and scala 2.13.8

**Comment by lefou** [comment]
Have you added the semanticDb depdendency to your `scalacPluginIvyDeps`? Can you post your `build.sc`?

**Comment by ghostbuster91** [comment]
I thought so as it comes within `ScalaFixModule` but then I unintentionally overrided it by writing:
``` 
  override def scalacPluginIvyDeps = Agg(
    ivy"org.typelevel:::kind-projector:0.13.2"
  )
```

instead of 
```
  override def scalacPluginIvyDeps = super.scalacPluginIvyDeps() ++ Agg(
    ivy"org.typelevel:::kind-projector:0.13.2"
  ) 
``` 
:facepalm:
