### ISSUE TITLE
[feature request] Add support for setting `javaHome` in `javaModule`

### ISSUE THREAD

**Issue by ckipp01** [com-lihaoyi/mill#1983]
So a bit of back story first. I'm currently working with the [semanticdb-java](https://sourcegraph.github.io/scip-java/docs/manual-configuration.html) compiler plugin to enable Java sources to emit semanticdb. One of the issues I hit on is that on jdk 17 there are some extra flags that need to be passed in to the compiler to ensure that some things are available, like `com.sun`. Currently when you try to pass in the necessary flags for the plugin to work you'll see the following:

```
[info] compiling 1 Java source to /Users/ckipp/Documents/scala-workspace/minimal/out/javaModule/compile.dest/classes ...
[warn] Javac is running in 'local' mode. These flags have been removed:
[warn]  -J--add-exports, -Jjdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED, -J--add-exports, -Jjdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED, -J--add-exports, -Jjdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED, -J--add-exports, -Jjdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED, -J--add-exports, -Jjdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
[error] An exception has occurred in the compiler (17.0.3). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
[error] java.lang.IllegalAccessError: class com.sourcegraph.semanticdb_javac.SemanticdbPlugin (in unnamed module @0x79fa2a2c) cannot access class com.sun.tools.javac.api.BasicJavacTask (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.api to unnamed module @0x79fa2a2c
```

While I'm not super familiar with `LocalJavaCompiler` I see we hit on this in Metals [here](https://github.com/scalameta/metals/blob/main/sbt-metals/src/main/scala/scala/meta/metals/MetalsPlugin.scala#L54-L64) and it seemed that the solution was to make sure `javaHome` was set in sbt. By doing this when [`directOrFork`](https://github.com/sbt/zinc/blob/5804d50afd960330f34af35e4367fdb171204f5a/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/javac/JavaCompiler.scala#L41-L67) eventually gets called in Zinc if the `javaHome` is not set then you see a call to `JavaCompiler.local.getOrElse(JavaCompiler.fork(None))` which causes us to get a local compiler that rejects `-J` flags.

I was curious how this was handled in Mill and it seems that in [`ZincWorkerImpl.scala`](https://github.com/com-lihaoyi/mill/blob/main/scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala#L66) where we call `compilers` we are passing `None` for the `javaHome` that will eventually call `directOrFork` meaning that we will always get a local fork.

Would it be possible to instead of always passing `None` to instead create a new `def javaHome: T[Option[PathRef]] = None` so that this can be overridden in specific scenarios like this? Then when `compileJava` or `compileMixed` is called there is another parameter, `javaHome` that also gets passed, which can then be used?

**Comment by lefou** [comment]
I myself never hit this issue, but I trust you that this might be a necessary feature. I don't have any arguments against supporting it. 

My thoughts about an implementation: As we keep the zinc compiler instances in the shared `ZincWorkerImpl`, we also want the suggested `javaHome` target in that external module. To avoid complicated setups (in which we need to override a changed worker in each `JavaModule`), we could make it a `T.source` and read some default from an environment variable. Also, this value need to be considered as input for the cached compiler hash, so we don't confuse local and non-local instances.

**Comment by ckipp01** [comment]
Was able to play around with this a bit more and thanks to some input from @dos65 I think there is a much less invasive solution that I was able to test and it worked out.

Inside of `ZincWorkerImpl` we can change `javaOnlyCompilers` to something like this:
```scala
  def javaOnlyCompilers2(javacOptions: Seq[String]) = {
    // Keep the classpath as written by the user
    val classpathOptions = ClasspathOptions.of(
      /*bootLibrary*/ false,
      /*compiler*/ false,
      /*extra*/ false,
      /*autoBoot*/ false,
      /*filterLibrary*/ false
    )

    val dummyFile = new java.io.File("")
    // Zinc does not have an entry point for Java-only compilation, so we need
    // to make up a dummy ScalaCompiler instance.
    val scalac = ZincUtil.scalaCompiler(
      new ScalaInstance(
        version = "",
        loader = null,
        loaderCompilerOnly = null,
        loaderLibraryOnly = null,
        libraryJars = Array(dummyFile),
        compilerJars = Array(dummyFile),
        allJars = new Array(0),
        explicitActual = Some("")
      ),
      dummyFile,
      classpathOptions // this is used for javac too
    )

    val javaTools = {
      val (javaCompiler, javaDoc) =
        if (javacOptions.exists(_.startsWith("-J"))) {
          (javac.JavaCompiler.fork(None), javac.Javadoc.fork(None))

        } else {
          val compiler = javac.JavaCompiler.local.getOrElse(javac.JavaCompiler.fork(None))
          val docs = javac.Javadoc.local.getOrElse(javac.Javadoc.fork())
          (compiler, docs)
        }
      javac.JavaTools(javaCompiler, javaDoc)
    }

    ic.compilers(javaTools, scalac)
  }
```
_This was only for testing, we shouldn't keep it as since this would generate new compilers every time, but we can probably cache this instance off of `javacOptions` or something and if they change, then we create new ones._

But with this change I was able to have a small java module:

```
object javaModule extends JavaModule {

  def ivyDeps = Agg(ivy"com.sourcegraph:semanticdb-javac:0.8.2")

  def javacOptions = Seq(
    "-J--add-exports",
    "-Jjdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED",
    "-J--add-exports",
    "-Jjdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED",
    "-J--add-exports",
    "-Jjdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED",
    "-J--add-exports",
    "-Jjdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED",
    "-J--add-exports",
    "-Jjdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED",
    s"-Xplugin:semanticdb -sourceroot:${T.workspace} -targetroot:${T.dest}"
  )

}
```
Using JDK 17 this was able to compile file and produce semantidb as expected:

```
❯ ./mill-release javaModule.compile
[10/20] javaModule.resources
```
```
~/Documents/scala-workspace/minimal/out/javaModule/javacOptions.dest/META-INF/semanticdb/javaModule/src/idn main*
❯ l
.rw-r--r-- 5.5k ckipp 12 Aug 10:51  TokenType.java.semanticdb
```
Whereas before this would blow up:

```
❯ mill javaModule.compile
[19/19] javaModule.compile
[info] compiling 1 Java source to /Users/ckipp/Documents/scala-workspace/minimal/out/javaModule/compile.dest/classes ...
[warn] Javac is running in 'local' mode. These flags have been removed:
[warn]  -J--add-exports, -Jjdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED, -J--add-exports, -Jjdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED, -J--add-exports, -Jjdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED, -J--add-exports, -Jjdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED, -J--add-exports, -Jjdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
[error] An exception has occurred in the compiler (17.0.4). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
[error] java.lang.IllegalAccessError: class com.sourcegraph.semanticdb_javac.SemanticdbPlugin (in unnamed module @0x4e59433c) cannot access class com.sun.tools.javac.api.BasicJavacTask (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.api to unnamed module @0x4e59433c
...
```

Would making this small change to `javaOnlyCompilers` be fine?
