### ISSUE TITLE
Incremental compilation issues in large(ish) projects

### ISSUE THREAD

**Issue by alexarchambault** [com-lihaoyi/mill#2003]
In the [Scala CLI](https://github.com/VirtusLab/scala-cli), but also in the [coursier](https://github.com/coursier/coursier) or [Almond](https://github.com/almond-sh/almond) builds, we've been seeing consistently issues with incremental compilation. IIRC, these were things like whole module being re-compiled upon simple source changes that shouldn't require it.

These were frequent enough that we switched to [mill-scala-cli](https://github.com/scala-cli/mill-scala-cli) to handle compilation in those projects (even it though it has [some drawbacks](https://github.com/scala-cli/mill-scala-cli/tree/b71e15fe77dd937d66dfc31975e97140f8ef3d3b#benefits--drawbacks--limitations)). These issues are also quite hard or time-consuming to reproduce, and even more so to minimize. Which is quite frustrating, and is also why this wasn't reported earlier.

Sorry about the vague description here, I usually don't open issues if I don't have at least a repro, but I guess [you asked for it](https://github.com/scala-cli/mill-scala-cli/issues/2) ^^

**Comment by alexarchambault** [comment]
If you want to build Scala CLI without the mill-scala-cli plugin, you can add a line such as
```scala
  def enableScalaCli = false
```
right below [this one](https://github.com/VirtusLab/scala-cli/blob/8aab8a311c5fe5e81366ae4f56984df3478b721c/project/settings.sc#L786).

**Comment by lefou** [comment]
Thanks for reporting. Although the description is vague, we recently fixed an issue with incremental compilation in 0.10.5, which could also be the cause for your observations.

* Issue: https://github.com/com-lihaoyi/mill/issues/1901
* Fix: https://github.com/com-lihaoyi/mill/pull/1904
* Test case: https://github.com/com-lihaoyi/mill/pull/1907

It would be very helpful, if you could check whether a recent version of Mill >= 0.10.5 fixes your issues as well.

**Comment by alexarchambault** [comment]
Closing this issue… As of https://github.com/VirtusLab/scala-cli/pull/1335 (that uses Mill `0.10.7`), it seems the incremental compilation issues went away. It seems to be the same on the coursier build, where I had enabled mill-scala-cli too.

**Comment by lefou** [comment]
Thanks for checking and reporting! This issue was already fixed in Mill 0.10.5 then.
