### ISSUE TITLE
Document command parameter handling with mainargs

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#2029]

**Comment by lihaoyi** [comment]
Is this just a matter of adding a link to https://github.com/com-lihaoyi/mainargs? The docs there are pretty comprehensive, except for mill-specific things like taking `Task[_]` or `Evaluator`

**Comment by lefou** [comment]
Yeah it's the link and about the Mill specifics. 

* Handling tasks (`Task`) vs. referencing tasks (`Tasks`) from the cli
* How to evolve commands with args in a binary compatible way
* Best practices: using a args object vs. many separate args
