### ISSUE TITLE
Split out scalac compiler plugins

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#2035]
We have essentially two compiler plugins in Mill which we currently build as one:

* we don't require `override` on overridden `def`s and `val`s and special handle `mill.moduledefs.Cacher` instances
* we encode the ScalaDoc of targets as annotation `mill.moduledefs.Scaladoc`, se we can later extract and re-use them in `mill inspect`

Those are currently packaged in one ordinary Scala artifact `mill-moduledefs` based on Scala binary version.
Instead, they should be packaged for the full Scala version, to avoid conflicts.

Also, because of their packaging, they are currently not really usable outside of Mill, which makes developing external Mill plugins a bit more inconvenient, as e.g. the scaladoc encoding would be useful for external plugins too.

Contrary to the fact, that these modules change quite seldom, they need to be (re-)released whenever new Scala versions come out.

I suggest, to make them standalone project with their own release cycle and well defined compatibility scheme, so we can use them in Mill accordingly.

**Comment by lefou** [comment]
I started a new project: https://github.com/com-lihaoyi/mill-moduledefs

Once, we get it to properly publish, we can refactor to use that external project instead.

**Comment by lefou** [comment]
@lihaoyi I don't think we already have organization-wide secrets? Hence, could you please add the respective secrets to the new project? Thank you!

* Project: https://github.com/com-lihaoyi/mill-moduledefs
* Secrets: `SONATYPE_DEPLOY_USER`, `SONATYPE_DEPLOY_PASSWORD`, `SONATYPE_PGP_SECRET`, `SONATYPE_PGP_PASSWORD`

**Comment by lolgab** [comment]
Other projects are using organization-wide secrets
![secrets](https://user-images.githubusercontent.com/5793054/195833619-1b7e04a9-4dce-479c-af2b-c83bd49da4f4.png)

**Comment by lefou** [comment]
@lolgab Thanks for the info. I'll use these too, then.
