### ISSUE TITLE
Scoverage support on Scala 3.2

### ISSUE THREAD

**Issue by markehammons** [com-lihaoyi/mill#2043]
Scala 3.2 can generate scoverage info on its own. You need only do     
```
override def scalacOptions: Target[Seq[String]] =
      T {
        outer.scalacOptions() ++
          Seq(s"-coverage-out:${data().path.toIO.getPath()}")
```
To have coverage reports.

**Comment by lefou** [comment]
Yeah, collecting data that way is easy. But you still need to invoke some tools to generate a report from it.
