### ISSUE TITLE
`PublishModule` deletes `moduleDeps` created by other traits

### ISSUE THREAD

**Issue by lolgab** [com-lihaoyi/mill#2082]
`PublshModule` has the following code:
```scala
override def moduleDeps: Seq[PublishModule] = Seq.empty[PublishModule]
```
https://github.com/com-lihaoyi/mill/blob/c985ef8ef0224bb04738fe1383a08a19e7b94fd6/scalalib/src/PublishModule.scala#L16

which creates a very strange behaviour when a base trait manipulates the `moduleDeps`. If you add `with PublishModule` the dependencies added previously by other traits disappear.

## Proposed solution
If it's important that all the `moduleDeps` are `PublishModule`s, it should instead iterate over the `moduleDeps` and make sure that all the `moduleDeps` are proper `PublishModule`s, and then cast the result if the requirement passes, but it shouldn't delete any existing `moduleDeps` otherwise.

**Comment by lefou** [comment]
> `PublshModule` has the following code:
> 
> ```scala
> override def moduleDeps: Seq[PublishModule] = Seq.empty[PublishModule]
> ```
> 
> https://github.com/com-lihaoyi/mill/blob/c985ef8ef0224bb04738fe1383a08a19e7b94fd6/scalalib/src/PublishModule.scala#L16
> 
> which creates a very strange behaviour when a base trait manipulates the `moduleDeps`. If you add `with PublishModule` the dependencies added previously by other traits disappear.
> ## Proposed solution
> 
> If it's important that all the `moduleDeps` are `PublishModule`s, it should instead iterate over the `moduleDeps` and make sure that all the `moduleDeps` are proper `PublishModule`s, and then cast the result if the requirement passes, but it shouldn't delete any existing `moduleDeps` otherwise.

I agree. We should call `super.moduleDeps` and fail with a sensible error message if any of them is not a `PublishModule`
