### ISSUE TITLE
private targets name clashes overwrite outputs

### ISSUE THREAD

**Issue by lolgab** [com-lihaoyi/mill#2107]
## Problem
`private` target json files in the `out` directory use the name of the method as key. But when using traits you can have two different private targets that have the same name.

### Reproduction

Given this `build.sc` file:
```scala
import mill._
import mill.scalalib._

trait M1 extends Module {
  private def foo = T { "foo-m1" }
  def bar = T { foo() }
}

trait M2 extends Module {
  private def foo = T { "foo-m2" }
  def baz = T { foo() }
}

object mod extends M1 with M2
```

```
> mill show mod.bar
"foo-m1"
> mill show mod.baz
"foo-m1"
```

As you can see they both print `"foo-m1"` since the same `foo.json` is used for the two private targets in the two traits. This creates a name collision and Mill thinks that the target was already evaluated with `"foo-m1"` when in reality it is using the output from another trait.

**Comment by lefou** [comment]
Sounds like we need to always apply the same sub-directory layout as we do for overridden `def`s, except that we should probably use a different directory suffix (e.g. `private` or `super`), as `foo.overridden` might be semantically misleading. 

So we end up with:

```
out/
└── mod
    └── foo.super
        └── ammonite
            └── build
                ├── M1
                │   └── foo.json
                └── M2
                    └── foo.json
```

If we settle with `super`, we could also substitute `overridden` with `super`, so we don't have too many different suffixes.

/cc @lihaoyi

**Comment by lolgab** [comment]
> If we settle with `super`, we could also substitute `overridden` with `super`, so we don't have too many different suffixes.

This would be great! I really like this proposal. It really makes sense!

**Comment by lefou** [comment]
I added a test case as draft PR, but will not further work on this right now. We need to somehow get the information about the `private`-ness of the target in the right place, which may also result in binary incompatible code. Once we know a `NamedTask` is `private`, we can always use the `foo.super` out directory. The code is located at `Evaluator.plan`.

If anybody wants to implement it, please go ahead.

**Comment by lefou** [comment]
I'd rather schedule a proper fix for it for the next major version, as we again change the cache directory layout. 

I we get some patch sooner, we may (temporarily) keep the `overridden` suffix, even if it is a bit misleading, to avoid fundamental changes to the cache layout. 

As a workaround, you can rename one of the private `def`s.

**Comment by lolgab** [comment]
One thing we could document/suggest is to prefix private targets since they need to be considered "global". It's what I'm doing in my plugins at least.

**Comment by lefou** [comment]
Good point. Prefixing all targets names of a plugins is in general a good idea. I do it for is almost all plugins. (Writing a Plugin-Writer-Guide is still on my TODO list, haha.)

**Comment by lefou** [comment]
@lolgab Can you have a look at #2108, which should fix this issue?

**Comment by lolgab** [comment]
> @lolgab Can you have a look at #2108, which should fix this issue?

Sorry for not having reviewed in time, but I trust you doing the right change. Thank you for fixing this.
