### ISSUE TITLE
IDEA setup does not work for Scala 3.1 and 3.2

### ISSUE THREAD

**Issue by informarte** [com-lihaoyi/mill#2109]
```
./mill mill.scalalib.GenIdea/idea
```
does not work properly when the project uses Scala 3.1 or 3.2: IDEA will think that the project uses Scala 2.

For Scala 3.2, the problem can be worked around by adding
```
<language-level>Scala_3_2</language-level>
```
to the properties section of `.idea/libraries/scala3_library_3_3_2_0_jar.xml`.

**Comment by lefou** [comment]
Strange, language level for Scala 3.1 should work since Mill 0.10.4 (https://github.com/com-lihaoyi/mill/pull/1856)

Newer versions should work after https://github.com/com-lihaoyi/mill/pull/2111 is merged.

**Comment by informarte** [comment]
Regarding Scala 3.1, it seems I looked at an older version of `GenIdeaImpl.scala`.
