### ISSUE TITLE
Cleaning a module does not work

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#2256]
According to the documentation, one can clean a module and all its sub-modules with:

```
$ mill clean module
```

After executing it, the `out/module` path is not removed and all target and sub-module entries are still present.

Affected Mill version: `0.11.0-M2`, `0.10.10`, probably all `0.10.x`

**Comment by lefou** [comment]
My suspicion is, that this is broken since Mill 0.10 as we have changed the `out` layout in [1588](https://github.com/com-lihaoyi/mill/pull/1588) and there is no test covering `MillModule.clean`.

**Comment by DamianReeves** [comment]
Is there a version of mill I can pull down to test this?

**Comment by lefou** [comment]
Mill `0.10.10-5-e7ed05` is not published.

**Comment by DamianReeves** [comment]
> Mill `0.10.10-5-e7ed05` is now published.

Thanks
