### ISSUE TITLE
Jars not making it to the classpath

### ISSUE THREAD

**Issue by tballard** [com-lihaoyi/mill#2293]
I was trying to include some scalikejdbc stuff in my project, like so:

    ivy"org.scalikejdbc::scalikejdbc-interpolation:4.0.0",

which transitively imports 

    ivy"org.scalikejdbc::scalikejdbc-core:4.0.0",
    ivy"org.scalikejdbc::scalikejdbc-interpolation-macro:4.0.0",

I got a bunch of "not found: type not found: type SQLSyntaxSupport" errors. This happened when faithfully copying examples of using their code generator. Looking in the jar and the source, SQLSyntaxSupport seemed to be a valid type. It similarly failed to find other interpolation-related classes. 

However, If I repackage all the scalikejdbc class files into a single jar (desperation, ya know) it successfully finds the classes. I theorize that it may have to do with the fact that the 3 jars put files into the same package ...?

**Comment by lefou** [comment]
Can you provide a minimal reproduction?

**Comment by lefou** [comment]
```
$ cat build.sc
import mill._
import mill.scalalib._

object foo extends ScalaModule {
  def scalaVersion = "2.13.10"
  def ivyDeps = Agg(
    ivy"org.scalikejdbc::scalikejdbc-interpolation:4.0.0",
  )
}
```

```
$ mill showNamed foo.compileClasspath
No mill version specified.
You should provide a version via '.mill-version' file or --mill-version option.
Using mill version 0.10.11
[1/1] showNamed 
[1/1] showNamed > [2/15] foo.resources 
{
  "foo.compileClasspath": [
    "ref:c984eca8:/tmp/mill-2293/foo/resources",
    "qref:fb6ec868:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalikejdbc/scalikejdbc-interpolation_2.13/4.0.0/scalikejdbc-interpolation_2.13-4.0.0.jar",
    "qref:a94bfc28:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10.jar",
    "qref:8a2f7281:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalikejdbc/scalikejdbc-core_2.13/4.0.0/scalikejdbc-core_2.13-4.0.0.jar",
    "qref:20690266:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalikejdbc/scalikejdbc-interpolation-macro_2.13/4.0.0/scalikejdbc-interpolation-macro_2.13-4.0.0.jar",
    "qref:f8fdafac:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar",
    "qref:44ed873b:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/apache/commons/commons-dbcp2/2.9.0/commons-dbcp2-2.9.0.jar",
    "qref:27371a3d:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.13/2.1.0/scala-parser-combinators_2.13-2.1.0.jar",
    "qref:d65fa8a6:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.13/2.5.0/scala-collection-compat_2.13-2.5.0.jar",
    "qref:4baeb789:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.10/scala-reflect-2.13.10.jar",
    "qref:387ff03c:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.10.0/commons-pool2-2.10.0.jar",
    "qref:b8dca5b4:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2.jar"
  ]
}
```

Jars are present on classpath.

**Comment by tballard** [comment]
Yeah, they were present on my classpath by that measure, too, surprisingly. I didn't know the trick to catching the actual command line that got executed.

**Comment by lefou** [comment]
A reproducer might be still nice. Maybe you minimize your project? Any way, it's probably the same reason that make issues in Mill as well as in Ammonite. Maybe the pom files or the jars are any special?

**Comment by tballard** [comment]
I didn't notice any specialness when repackaging the jars and poms but I'm not sure what specialness would look like, anyway. It should be easy to convert a do-nothing script to a do-nothing project. I'll try to squeeze it between some "real" work.

**Comment by tballard** [comment]
I created a diminutive failing project for you. Where would you like it deposited?

**Comment by lefou** [comment]
> I created a diminutive failing project for you. Where would you like it deposited?

A Github repo or gist would be the easiest.

**Comment by tballard** [comment]
[db.tgz](https://github.com/com-lihaoyi/mill/files/10548368/db.tgz)

**Comment by tballard** [comment]
or https://gist.github.com/tballard/8e71e747f54ecd1c3109945cb6101f31 if it is really easier

**Comment by lefou** [comment]
After looking into it, I came to the conclusion that this is not an issue, but a user error.

Although the missing type `SQLSyntaxSupport` is located in the `scalikejdbc-interpolation_2.13-4.0.0.jar`, it is defined as inner trait in trait `scalalikejdbc.SQLSyntaxSupportFeature` and as such not directly usable.

It is only made accessible as `scalalike.SQLSyntaxSupport` by extending the trait `SQLSyntaxSupportFeature` it in the package object of `scalalibjdbc` which is located in `scalikejdbc_2.13-4.0.0.jar`.

Ergo, you have to have this jar in your dependencies. And the dependency defined in your reproducer does not transitively depend on it.

**Comment by tballard** [comment]
I noticed the inner trait thing, but that that source file was created by the scalikejdbc code generator so I didn't question it. Any advice on scala database libraries? I guess we're doing things in a weakly OMish way, i.e. case classes would be good, but we handle our own things linked by foreign keys.  Quill seemed like good magic, but dead slow to compile and the raw sql support didn't seem that great. Slick seemed like it was dead set on using futures which felt like more work than necessary for our purposes although the code generation was amazingly fast. Doobie wasn't that OMish and seemed overly functional, scalikejdbc seemed like it might be simple but this doesn't seem like a good start. I can't say I'm wild about the syntax for lots of joins in slick or quill.

**Comment by lefou** [comment]
Just in case I was not clear enough. You can perfectly use scalikejdbc, if you want. You just need to use another dependency.

```diff
-ivy"org.scalikejdbc::scalikejdbc-interpolation:4.0.0",
+ivy"org.scalikejdbc::scalikejdbc:4.0.0",
```

**Comment by tballard** [comment]
No, I got that, I just wondered if you had developed a fav.
