### ISSUE TITLE
can not config repository mirror via ~/.config/coursier/mirror.properties

### ISSUE THREAD

**Issue by yuchangyuan** [com-lihaoyi/mill#2312]
Repository mirror for coursier can be config in ~/.config/coursier/mirror.properties(in Linux), but this seems not apply to mill.

ref1: https://get-coursier.io/blog/2019/07/05/1.1.0-M14#mirrors
ref2: https://scalameta.org/metals/docs/troubleshooting/proxy/#mirrors

**Comment by lefou** [comment]
Thanks for reporting. The referenced documentation lists multiple ways to configure mirrors, e.g. gloabal properties file, env variable, properties, .... Which one did not work? Have you tried the other variants?

**Comment by yuchangyuan** [comment]
> Thanks for reporting. The referenced documentation lists multiple ways to configure mirrors, e.g. gloabal properties file, env variable, properties, .... Which one did not work? Have you tried the other variants?

I tryed global properties(`~/.config/coursier/mirror.properties`), and I have checked that this change works with `cs` command.

**Comment by yuchangyuan** [comment]
> 



> @yuchangyuan My experience is that mill can work well via proxy repositories, here's some stuff I tried / needed depending on different circumstances.
> 
> Here is some extra stuff you can try in build.sc
> 
> ```
> object CustomZincWorkerModule extends ZincWorkerModule with CoursierModule {
>   def repositoriesTask = T.task {
>     Seq(
>       MavenRepository("https://packages.corp.com/artifactory/maven/"),
>       coursier.LocalRepositories.ivy2Local
>     )
>   }
> }
> ```
> 
> ```
> trait CommonBuildSettings extends ScalaModule {
>   def repositoriesTask = CustomZincWorkerModule.repositoriesTask
>   def zincWorker       = CustomZincWorkerModule
>   def scalaVersion     = Config.scalaVersion  
> }
> ```
> 
> Perhaps try configured ammonites proxies too.
> 
> ```
> RUN mkdir -p /root/.mill/ammonite
> COPY predef.sc /root/.mill/ammonite/predef.sc
> COPY predef.sc /root/.mill/ammonite/predefScript.sc
> ```
> 
> and predef.sc
> 
> ```
> import coursierapi.MavenRepository
> 
> interp.repositories() ++= Seq(  
>   MavenRepository.of("https://packages.corp.com/artifactory/maven/"),
>   MavenRepository.of("https://packages.corp.com/artifactory/maven-jitpack-remote/")
> )
> ```
> 
> Maybe this helps, maybe not ...

thank you for your advise.  but in order to apply this approach, I need modify `build.sc` of every project, which sometimes not easy.

**Comment by lefou** [comment]
Have you tried the alternative approaches (from https://scalameta.org/metals/docs/troubleshooting/proxy/#mirrors)? 

* using `COURSIER_MIRRORS` environment variable 
* using `coursier.mirrors` system property.

**Comment by lefou** [comment]
> I don't know how to apply `-Dcoursier.mirrors` to mill.

It's 

```
> mill -D coursier.mirrors=... 
```
