### ISSUE TITLE
mill-bsp semantic token highlighting

### ISSUE THREAD

**Issue by Quafadas** [com-lihaoyi/mill#2340]
The new metals release includes support for semantic tokens. Mill already appears to correctly support many of the highlights... Which is awesome! However, there appears to be a slight divergence, I think on method highlighting. 

Here's mill
![image](https://user-images.githubusercontent.com/24899792/222743440-55086c0c-b5cc-40d8-8cec-a89f40f41022.png)

And bloop; 
![image](https://user-images.githubusercontent.com/24899792/222743541-fd0fdd83-b4dc-4256-a25d-124b89e4f88b.png)

I _think_ I would expect mill to highlight methods yellow too? Both cases here are the same codebase, with a  `switch build server` command that has (I believe) correctly imported and compiled.

**Comment by lefou** [comment]
From my understanding, there is nothing special in mill-bsp regarding semantic token highlighting. We produce semanticdb data with is used by metals to do the highlighting. You should check the effectively used semanticDB versions. Mill 0.10.x is using the exact version requested by Metals, Mill 0.11.x will use either the version requested by Metals or the version used to build Mill, whatever is higher.

**Comment by Quafadas** [comment]
Thanks for writing back - that makes sense and I've been through and checked the semantic versions. I did exactly these commands as suggested which revealed that metals requests a slightly higher Semantic DB version that mill appears to using  right now - it sounds like the long fix for this entire category of problems, is actually already in place in Mill 0.11 - which is a pretty cool finding! 

So I'll close this.
