### ISSUE TITLE
Logical loops in moduleDeps

### ISSUE THREAD

**Issue by tballard** [com-lihaoyi/mill#2341]
It appears that logical loops in moduleDeps are rewarded with a hearty stack trace as of 10.9. An error message with a  list of the modules in the loop(s) would be the right thing, I suppose.

**Comment by lefou** [comment]
Can you please provide a reproduction?

**Comment by tballard** [comment]
Sure:

import mill.scalalib._
import mill.define.Task

object a extends ScalaModule() {
   override def moduleDeps = Seq(a)

   override def scalaVersion = "2.13.7"
}
