### ISSUE TITLE
`twirlIvyDeps` don't align with twirl dependencies on scala 3

### ISSUE THREAD

**Issue by mrdziuban** [com-lihaoyi/mill#2388]
The default [`twirlIvyDeps`](https://github.com/com-lihaoyi/mill/blob/main/contrib/twirllib/src/mill/twirllib/TwirlModule.scala#L30-L35) refer to `scala-parser-combinators:1.1.2` but in the latest twirl 1.6 milestone/RC releases, [they've updated to use `scala-parser-combinators:2.1.0` when on scala 3](https://github.com/playframework/twirl/blob/main/build.sbt#L17-L22).

This causes a resolution error that can't be fixed just by adding the correct `scala-parser-combinators` version to `ivyDeps`. I was able to resolve this by overriding `twirlIvyDeps` in my `build.sc`

**Comment by lefou** [comment]
Looks like we need the same switch based on the twirl version as in the twirl repository you linked. Feel free to send a pull request.

**Comment by mrdziuban** [comment]
@lefou out of curiosity, why is having `scala-parser-combinators` in `twirlIvyDeps` necessary? I would have guessed that it would be pulled in transitively from depending on twirl itself

**Comment by lefou** [comment]
> @lefou out of curiosity, why is having `scala-parser-combinators` in `twirlIvyDeps` necessary? I would have guessed that it would be pulled in transitively from depending on twirl itself

Yeah, that was also my first though. I don't know. You could dig in the git history, if there is some clue, or just try to remove it. Maybe, it is/was an optional dependency or it was too old for some twirl version.

**Comment by mrdziuban** [comment]
Huh yeah [it is optional](https://github.com/playframework/twirl/blob/main/build.sbt#L125) for some reason, and tests in mill fail without it there 🤷‍♂️
