### ISSUE TITLE
Simplify the setup for cross-platform cross-version Scala modules

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#2405]
This example contains a minimal example for cross-publishing some modules across `{Scala-JVM,Scala.js}X{2.13.10,3.2.2}`

https://github.com/com-lihaoyi/mill/blob/main/example/web/6-cross-platform-publishing/build.sc

It's pretty complicated, given that this is a very common workflow: most Scala modules will support multiple Scala versions, and many will support multiple Scala platforms. There are other ways it can be laid out (e.g. a separate `Cross` for each module we publish) but none of them are any simpler

We should be able to simplify this somehow

**Comment by lolgab** [comment]
Previous work in this area: https://github.com/lolgab/mill-crossplatform
