### ISSUE TITLE
Failure to import Mill project into IntelliJ using Mill/BSP

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#2412]
When I try to load the current Mill `main` branch into IntelliJ using BSP, I get

```
java.net.URISyntaxException: Illegal character in path at index 22: contrib.playlib.worker[(2.6+2.7+2.8)]
```

<img width="1840" alt="Screenshot 2023-04-04 at 1 24 29 PM" src="https://user-images.githubusercontent.com/934140/229694932-4064cbb3-d2d4-4d90-b3ee-641be0adf302.png">

Commenting out the `playlib` part of the build seems to fix it

**Comment by lihaoyi** [comment]
@lefou have you seen this before? Seems to happen consistently. We haven't bumped the Mill version used in the Mill repo yet AFAIK, so it shouldn't have anything to do with the remove-ammonite changes

**Comment by lefou** [comment]
Looks strange and a bit like IJ is representing shared source dirs which end up in multiple BSP buildTargets. What IJ version do you use? The work heavily on BSP and Bazel stuff. Do you use some snapshot or early access build?

**Comment by lefou** [comment]
Do you have generated the `.bsp/mill-bsp.json` file with a development version of Mill, by any chance? You should regenerate it with `mill mill.bsp.BSP/install` just to be sure.

**Comment by lefou** [comment]
You can also look at the `.bsp/mill-bsp.stderr` file.

**Comment by lefou** [comment]
Can you try to open the same project in vscode? I think this is an issue in IntelliJ BSP.

**Comment by lihaoyi** [comment]
VSCode seems to load without reporting errors, but it doesn't seem to be able to jump-to-definition in other modules. Jumping to definition to standard library files (`java.*`, `scala.*`) seems to work. Not sure if that means it's working or not

**Comment by lihaoyi** [comment]
Looking at the error, it seems likely that this has something to do with `playlib` taking a tuple as the cross-version key, rather than a single string.

**Comment by lefou** [comment]
The `URISyntaxException` does not appear in the logs. Also, the requested buildTargetIdentifier (the URI) is never send from the server to the client, so this exception must come from somewhere inside IntelliJ. It's probably a good idea to report it there or ask in their channels.

**Comment by sequencer** [comment]
I encounter this issue as well in chipsalliance/chisel#3045:
```
java.net.URISyntaxException: Illegal character in path at index 6: plugin[(2.12.10+2.12.11+2.12.12+2.12.13+2.12.14+2.12.15+2.12.16+2.12.17+2.12.2+2.12.3+2.12.5+2.12.6+2.12.7+2.12.8+2.12.9)]
```

**Comment by lefou** [comment]
Please open an issue in the IntelliJ Bugtracker and post a link here.

Older versions of IJ, when used in BSP mode, merged shared source folder and displayed them also in a tree entry with an condensed title, containing some regex-like merged module name and  lots of plus symbols. Hence, I think IJ somehow requests a wrong target identifier. This is just an suspicion, but we will not find out, without reporting. It is not reproducible with vscode and the title does not appear in Mill's log file.

**Comment by sequencer** [comment]
I upgrade the Scala plugin. seem it works fine now.
