### ISSUE TITLE
BSP: mill-bsp doesn't publish `build/publishDiagnostics` when there's no diagnostics

### ISSUE THREAD

**Issue by tanishiking** [com-lihaoyi/mill#2426]
- mill v0.10.12
- Java 17
- Metals 0.11.11
- Scala 3.2.2

## Problem

mill-bsp doesn't publish `build/publishDiagnostics` when there's no diagnostics.
As a result, previously published diagnostic won't be cleaned up when error is fixed.

https://user-images.githubusercontent.com/9353584/230577077-377f65db-407c-4a26-a6eb-bdadfe2d62f3.mov

## Expect

mill-bsp should publish `build/publishDagnostics` when error is fixed (bloop and sbt-bsp does)

```json
[Trace - 05:56:44 PM] Received notification 'build/publishDiagnostics'
Params: {
  "textDocument": {
    "uri": "file:///Users/tanishiking/ghq/github.com/tanishiking/metals-playground/HelloWorld/src/main/scala/hello/Foo.scala"
  },
  "buildTarget": {
    "uri": "file:/Users/tanishiking/ghq/github.com/tanishiking/metals-playground/HelloWorld/?id\u003dHelloWorld"
  },
  "diagnostics": [],
  "reset": true
}
```

**Comment by KaranAhlawat** [comment]
I was trying to work on a solution for this today, and came across some very strange results.

In my own simple project, if I use Mill BSP, the empty diagnostics array is not published.
However, when I was working in the `mill` repository itself, the diagnostic *was* being published


```txt
[Trace - 08:28:10 pm] Received notification 'build/publishDiagnostics'
Params: {
  "textDocument": {
    "uri": "file:/home/karan/Secondary/dev/mill-contrib/bsp/worker/src/mill/bsp/worker/BspCompileProblemReporter.scala"
  },
  "buildTarget": {
    "uri": "file:///home/karan/Secondary/dev/mill-contrib/bsp/worker"
  },
  "diagnostics": [
    {
      "range": {
        "start": {
          "line": 56,
          "character": 12
        },
        "end": {
          "line": 56,
          "character": 24
        }
      },
      "severity": 1,
      "source": "mill",
      "message": "value toI is not a member of String"
    }
  ],
  "reset": true
}


[Trace - 08:28:10 pm] Received notification 'build/taskFinish'
Params: {
  "taskId": {
    "id": "332966380"
  },
  "eventTime": 1694876290825,
  "message": "Compiled bsp.worker",
--
[Trace - 08:28:32 pm] Received notification 'build/publishDiagnostics'
Params: {
  "textDocument": {
    "uri": "file:///home/karan/Secondary/dev/mill-contrib/bsp/worker/src/mill/bsp/worker/BspCompileProblemReporter.scala"
  },
  "buildTarget": {
    "uri": "file:///home/karan/Secondary/dev/mill-contrib/bsp/worker"
  },
  "diagnostics": [],
  "reset": true
}


[Trace - 08:28:33 pm] Received notification 'build/taskFinish'
Params: {
  "taskId": {
    "id": "332966380"
  },
  "eventTime": 1694876313543,
  "message": "Compiled bsp.worker",
  "status": 1,
  "dataKind": "compile-report",
  "data": {
    "target": {
      "uri": "file:///home/karan/Secondary/dev/mill-contrib/bsp/worker"
    },
    "errors": 0,
    "warnings": 0
  }
}
```

This is from the `.metals/bsp.trace.json` file.

Any ideas what might be going on?

**Comment by KaranAhlawat** [comment]
Okay, this seems to be a Scala 3 issue specifically.

I noticed that if using Mill BSP in the mill repository itself, the behavior was as expected, you got an empty array for the diagnostics. After looking into it, the `fileVisited` method was being called correctly in this case.

However, it was not being called at all in the Scala 3 minimal test repo.
Changing Scala 3 to Scala 2.13, though, instantly fixed the issue! So something is making it so that `fileVisited` is not being triggered when the version is Scala 3.x.

**Comment by lefou** [comment]
Could this be an issue with zinc or with our integration of zinc?

**Comment by KaranAhlawat** [comment]
I think it might be an issue with the Zinc integration, since SBT also uses Zinc, but they don't really have this issue.

**Comment by tanishiking** [comment]
> Also not sure if this is of relevance, but that behavior doesn't seem to hold in IntelliJ. But not sure if that indicates it's a Metals issue or not

I guess IntelliJ has a different mechanism to clear up the diagnostics, but it's better to send empty diagnostics to reset the client state according to the BSP "standard"

> If the computed set of diagnostic is empty, the server must push an empty array with reset set to true, in order to clear previous diagnostics.
https://build-server-protocol.github.io/docs/specification/#onbuildpublishdiagnostics-notification

(It's a kind of "problem" of Metals since there's only two BSP client AFAIK: Metals + IntelliJ, and IntelliJ can reset the state without empty diagnostics from BSP).

**Comment by KaranAhlawat** [comment]
My debug-foo has not been able to figure out yet why changing the Scala version to 3.x does not work. If someone has any insights, It'd be very helpful in debugging this further 😄
