### ISSUE TITLE
Empty version not substituted  in MillBuildModule (0.11.0-M8)

### ISSUE THREAD

**Issue by jilen** [com-lihaoyi/mill#2457]
version: 0.11.0-M8
Seems pretty much the same as #2360 

https://github.com/com-lihaoyi/mill/blob/0b33d71609328ffa86dc4c1a517f1bc02a910217/scalalib/src/mill/scalalib/bsp/MillBuildModule.scala#L49

**Comment by lefou** [comment]
Thanks for reporting. Issue #2474 is a partial duplicate, but covers also the no longer working `$MILL_PLATFORM`, hence I close this one as duplicate.
