### ISSUE TITLE
`Cross` scaladoc is out of date with new `Cross` API

### ISSUE THREAD

**Issue by lolgab** [com-lihaoyi/mill#2465]
The scaladoc here:
https://github.com/com-lihaoyi/mill/blob/bd64411e912ced92f6077854a573291031d1ccea/main/core/src/mill/define/Cross.scala#L259-L268
has an example using the old syntax.

**Comment by lihaoyi** [comment]
Fixed in https://github.com/com-lihaoyi/mill/commit/bd502f76aa448d260db28b56c107caae068438f4
