### ISSUE TITLE
Document build setup / capabilities / syntax for `example/build.sc` 

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#2479]
Mill can automatically build project under `example/` directory, run them as integration tests with specific build command, and generate documentation from it. This is currently not documented.

**Comment by lefou** [comment]
Systax of example `build.sc` is documented here: https://github.com/com-lihaoyi/mill/blob/87d5b926999633562ae01e4c6c0cb800f5f9ad36/example/src/mill/integration/ExampleTestSuite.scala#L6-L42

**Comment by lihaoyi** [comment]
I'll write something up in the readme
