### ISSUE TITLE
[BSP] Support buildTarget/jvmRunEnvironment

### ISSUE THREAD

**Issue by tgodzik** [com-lihaoyi/mill#2499]
I am not sure what the state of supporting DAP in Mill is, but it would be awesome to at least support `buildTarget/jvmRunEnvironment`, it would allow metals to at least support running without debugging.

Currently, Mill specifies that it supports `buildTarget/jvmRunEnvironment` via `jvmRunEnvironmentProvider`, but in reality it doesn't. So maybe it wouldn't be too much of an effort to support it, but if it is maybe instead `jvmRunEnvironmentProvider` should be set to false.

**Comment by lefou** [comment]
What do you mean by this?

> Currently, Mill specifies that it supports `buildTarget/jvmRunEnvironment` via `jvmRunEnvironmentProvider`, but in reality it doesn't.

We implement the `ch.epfl.scala.bsp4j.JvmBuildServer` interface. Both methods, `jvmRunEnvironment` and `jvmTestEnvironment` should return usable data.

What is missing? Is there an error or exception? Can you please provided more details, so we can fix our implementation?

**Comment by lefou** [comment]
For Support of DAP, there is already an issue

* https://github.com/com-lihaoyi/mill/issues/2225

After the "Scala Debugger" Session at the Scala Tooling Summit in March 2023, we concluded, that Metals will itself start the DAP, based on the data provided by other BSP requests, including the `buildTarget/jvmRunEnvironment`. And IntelliJ, as the other available BSP client, is using it's own debugger anyways. Hence, there is no value in implementing the `debugSession/start` request, is it?

**Comment by lefou** [comment]
We introduced support for the JVM Extension in Mill 0.10.4.

* https://github.com/com-lihaoyi/mill/pull/1849

**Comment by lefou** [comment]
Do you have more details/context to this `org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal error.` issue? You could generate the BSP connection file with debug info, maybe it reveals something. See also: https://com-lihaoyi.github.io/mill/mill/Installation_IDE_Support.html#_if_things_go_wrong

Can we do anything on the Mill side to debug/fix it?

**Comment by tgodzik** [comment]
I think the internal error might thrown if the code didn't compile
```
java.util.concurrent.CompletionException: java.lang.Exception: Failure during task evaluation: MillScalaSeed.compile Compilation failed\n\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)\n\tat java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)\n\tat java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)\n\tat java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)\n\tat mill.bsp.MillBuildServer.$anonfun$completable$1(MillBuildServer.scala:734)\n\tat mill.bsp.MillBuildServer.$anonfun$completable$1$adapted(MillBuildServer.scala:722)\n\tat scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)\n\tat java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)\n\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)\n\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)\n\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)\n\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)\n\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)\nCaused by: java.lang.Exception: Failure during task evaluation: MillScalaSeed.compile Compilation failed\n\tat mill.eval.Evaluator$.$anonfun$evalOrThrow$default$2$1(Evaluator.scala:1006)\n\tat mill.eval.Evaluator$EvalOrThrow.apply(Evaluator.scala:995)\n\tat mill.bsp.MillBuildServer.targetTasks(MillBuildServer.scala:695)\n\tat mill.bsp.MillJvmBuildServer.$anonfun$jvmRunEnvironment$1(MillJvmBuildServer.scala:28)\n\tat mill.bsp.MillBuildServer.$anonfun$completable$1(MillBuildServer.scala:725)\n\t... 8 more\n
```

the same with main classes result. I thought the issue was also when the code was compiling, but it seems we don't see the main class due to a different reason.

**Comment by lefou** [comment]
As the posted logs are from metals, I think this issue should reported there. A link to there issue back here would be nice.

**Comment by tgodzik** [comment]
The stack trace is coming from mill though:
```
java.util.concurrent.CompletionException: java.lang.Exception: Failure during task evaluation: MillScalaSeed.compile Compilation failed
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at mill.bsp.MillBuildServer.$anonfun$completable$1(MillBuildServer.scala:734)
	at mill.bsp.MillBuildServer.$anonfun$completable$1$adapted(MillBuildServer.scala:722)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)\nCaused by: java.lang.Exception: Failure during task evaluation: MillScalaSeed.compile Compilation failed
	at mill.eval.Evaluator$.$anonfun$evalOrThrow$default$2$1(Evaluator.scala:1006)
	at mill.eval.Evaluator$EvalOrThrow.apply(Evaluator.scala:995)
	at mill.bsp.MillBuildServer.targetTasks(MillBuildServer.scala:695)
	at mill.bsp.MillJvmBuildServer.$anonfun$jvmRunEnvironment$1(MillJvmBuildServer.scala:28)
	at mill.bsp.MillBuildServer.$anonfun$completable$1(MillBuildServer.scala:725)
	... 8 more\n

```

The main issue I see here is that Mill is throwing an exception when the code doesn't compile, which doesn't seem like a best way of communicating especially that `jvmRunEnvironment` is the same as previously. I don't plan on fixing anything on the Metals side when it comes to those exception, I don't think there is anything we can do. We could not ask the BSP server when the compilation failed, but it is not that big of a deal.

**Comment by carlosedp** [comment]
Curiously I'm investigating some "stuck errors" in Metals which stay marked even after fixed or commented-out and I saw this in the metals log:

```
2023.06.23 10:40:11 INFO  BSP server: [info] compiling 6 Scala sources to /Users/cdepaula/repos/scala/zio-channel/out/examples/compile.dest/classes ...
2023.06.23 10:40:13 INFO  BSP server: [error] -- [E008] Not Found Error: /Users/cdepaula/repos/scala/zio-channel/examples/src/sample4.scala:22:15 
2023.06.23 10:40:13 INFO  BSP server: [error] 22 |      _   <- s.tap(i => Console.printLine(s"Received $i")).repeat(Schedule.recurs(1))
2023.06.23 10:40:13 INFO  BSP server: [error]    |             ^^^^^
2023.06.23 10:40:13 INFO  BSP server: [error]    |value tap is not a member of Either[zio.channel.ChannelStatus, Int], but could be made available as an extension method.
2023.06.23 10:40:13 INFO  BSP server: [error]    |
2023.06.23 10:40:13 INFO  BSP server: [error]    |The following import might fix the problem:
2023.06.23 10:40:13 INFO  BSP server: [error]    |
2023.06.23 10:40:13 INFO  BSP server: [error]    |  import util.chaining.scalaUtilChainingOps
2023.06.23 10:40:13 INFO  BSP server: [error]    |
2023.06.23 10:40:13 INFO  BSP server: [error] one error found
2023.06.23 10:40:13 INFO  mill-bsp should support `buildTarget/jvmRunEnvironment`, but it fails.
org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal error.
    at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
    at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
    at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
    at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
    at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)
```

Don't know if this `jvmRunEnvironment` and the issue I see are related...

**Comment by lefou** [comment]
Mill BSP has change a lot between 0.10.x and 0.11.0. Also the issue was initially about support for `buildtarget/jvmRunEnvironment`, which we already support, hence it was closed.

I suggest to reproduce the error with a current Mill version and open a new issue, so it's more clear which issue is discussed and which Mill version is affected.

**Comment by tgodzik** [comment]
> Mill BSP has change a lot between 0.10.x and 0.11.0. Also the issue was initially about support for buildtarget/jvmRunEnvironment, which we already support, hence it was closed.

Sure, I understand! I just wanted to explain the actual source of the errors.

>I suggest to reproduce the error with a current Mill version and open a new issue, so it's more clear which issue is discussed and which Mill version is affected.

We've had some issues updating our tests to 0.11.0, so I need to get back to you once we figure that out.

**Comment by lefou** [comment]
> We've had some issues updating our tests to 0.11.0, so I need to get back to you once we figure that out.

Please reach out if you have questions regarding changes in Mill.

**Comment by tgodzik** [comment]
I checked with 0.11.1 and the same exact thing seems to be happening:

```
[Trace - 04:37:26 PM] Received response 'buildTarget/jvmRunEnvironment - (16)' in 364ms
Result: null
Error: {
  "code": -32603,
  "message": "Internal error.",
  "data": "java.util.concurrent.CompletionException: java.lang.Exception: Failure during task evaluation: MillBsp.compile Compilation failed\n\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)\n\tat java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)\n\tat java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)\n\tat java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)\n\tat mill.bsp.worker.MillBuildServer.$anonfun$completable$1(MillBuildServer.scala:670)\n\tat mill.bsp.worker.MillBuildServer.$anonfun$completable$1$adapted(MillBuildServer.scala:658)\n\tat scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)\n\tat java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)\n\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)\n\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)\n\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)\n\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)\n\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)\nCaused by: java.lang.Exception: Failure during task evaluation: MillBsp.compile Compilation failed\n\tat mill.eval.Evaluator.$anonfun$evalOrThrow$default$1$1(Evaluator.scala:41)\n\tat mill.eval.EvaluatorImpl$EvalOrThrow.apply(EvaluatorImpl.scala:66)\n\tat mill.bsp.worker.MillBuildServer.$anonfun$completableTasks$1(MillBuildServer.scala:627)\n\tat mill.bsp.worker.MillBuildServer.$anonfun$completable$1(MillBuildServer.scala:661)\n\t... 8 more\n"
}
```

**Comment by lefou** [comment]
> I checked with 0.11.1 and the same exact thing seems to be happening:
> 
> ```
> [Trace - 04:37:26 PM] Received response 'buildTarget/jvmRunEnvironment - (16)' in 364ms
> Result: null
> Error: {
>   "code": -32603,
>   "message": "Internal error.",
>   "data": "java.util.concurrent.CompletionException: java.lang.Exception: Failure during task evaluation: MillBsp.compile Compilation failed\n\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)\n\tat java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)\n\tat java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)\n\tat java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)\n\tat mill.bsp.worker.MillBuildServer.$anonfun$completable$1(MillBuildServer.scala:670)\n\tat mill.bsp.worker.MillBuildServer.$anonfun$completable$1$adapted(MillBuildServer.scala:658)\n\tat scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)\n\tat java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)\n\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)\n\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)\n\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)\n\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)\n\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)\nCaused by: java.lang.Exception: Failure during task evaluation: MillBsp.compile Compilation failed\n\tat mill.eval.Evaluator.$anonfun$evalOrThrow$default$1$1(Evaluator.scala:41)\n\tat mill.eval.EvaluatorImpl$EvalOrThrow.apply(EvaluatorImpl.scala:66)\n\tat mill.bsp.worker.MillBuildServer.$anonfun$completableTasks$1(MillBuildServer.scala:627)\n\tat mill.bsp.worker.MillBuildServer.$anonfun$completable$1(MillBuildServer.scala:661)\n\t... 8 more\n"
> }
> ```

Thank you for re-checking. I'll open a new issue.
