### ISSUE TITLE
add `ivyWhatDependsOn` command

### ISSUE THREAD

**Issue by shanielh** [com-lihaoyi/mill#250]
Hi!

I've added `reverseTree` capabilities to coursier and I want to add `ivyWhatDependsOn "module"` command, but I'm not sure where to start to upgrade the version of coursier to 1.0.3 (already published to maven).

Thanks.

**Comment by shengc** [comment]
I think `coursier` comes transitively via `ammonite` from [here](https://github.com/lihaoyi/mill/blob/master/build.sc#L72)
