### ISSUE TITLE
`MillBuildRootModule`: Disable the default-use of `<projectDir>/src`

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#2516]
This breaks the _single-source-of-thruth_ concept of Mill.

Instead, we should support importing a directory with either `import $file` or by inventing some new `$`-import type.

**Comment by lolgab** [comment]
`$import file` doesn't seem correct since it is currently used for `.sc` files while the `src` directory contains vanilla `.scala` files.

**Comment by lefou** [comment]
In general, I don't see the big difference, both are source files. But in Mill context, we treat `.sc` files special, e.g. we wrap them and also infer the `.sc` from the import statement, so I agree. We could use `$source`. It has the exact same semantics as `def sources` (but for single path) and is also being watched like `T.source`/`T.sources`.

**Comment by lefou** [comment]
Looks like I misunderstood something when opening this issue. I think it's invalid.
I thought, when compiling the `build.sc`, we also use source files from `<projectDir>/src`, but this is not the case. Instead, we use `<projectDir>/mill-build/src`, which is indeed another topic (#2461).

@lihaoyi About your last comment. I think it is more suited to issue #2461. We should discuss it there.
