### ISSUE TITLE
`millModuleDirectChildren` is not respected when resolving

### ISSUE THREAD

**Issue by lolgab** [com-lihaoyi/mill#2573]
Given this build:

```scala
import mill._
object mod extends Module {
  override lazy val millModuleDirectChildren = Seq.empty[Module]
  object bar extends Module
  object foo extends Module
}
```

`mill resolve mod._`

returns `mod.bar` and `mod.foo` in `0.11.0-M11` while doesn't return anything in `0.10.12`

**Comment by lihaoyi** [comment]
The new resolver aims to avoid instantiating things as far as possible, so it doesn't even look at `millModuleDirectChildren` and just uses the `java.lang.Class` for resolution.

We can make this work again by introducing a marker trait, perhaps `DynamicChildren`, to indicate to Mill that we should actually instantiate the module and look at its children. This would be similar to what we do for `Cross` modules

**Comment by lolgab** [comment]
What I really need is a `def enabled: Boolean = true` in `Module` so users and plugins can dynamically disable modules based on conditions. Redefining `millModuleDirectChildren` was what was possible in Mill `0.10`.
