### ISSUE TITLE
make intellij idea generation easier to call

### ISSUE THREAD

**Issue by antonkulaga** [com-lihaoyi/mill#259]
Generation of idea files is what I have to do all the time when changing my build. However, it is hard to memorize and type without mistakes current:
```
mill mill.scalalib.GenIdeaModule/idea
```
I suggest making the method easier to access. Maybe something like 
```
mill mill.gen.idea
```

**Comment by hepin1989** [comment]
`mill genIdea` or `mill genEclipse`

**Comment by NightMachinary** [comment]
I suggest making an alias in your shell. 
`alias milli="mill mill.scalalib.GenIdeaModule/idea"`

**Comment by lihaoyi** [comment]
In master this is `mill.scalalib.GenIdea`, which helps a bit...

**Comment by MrPowers** [comment]
The latest command is `mill mill.scalalib.GenIdea/idea` in case that wasn't clear.  This is [specified in the README](https://github.com/lihaoyi/mill#intellij-setup).
