### ISSUE TITLE
Internal error response to `buildTarget/scalaTestClasses`

### ISSUE THREAD

**Issue by ckipp01** [com-lihaoyi/mill#2591]
When using Mill as a BSP server with Metals there seems to be some internal errors being thrown. When investigating the failures in our CI [here](https://github.com/scalameta/metals/pull/5320) I tried using 0.11.0 with a fresh minimal Mill project and in the BSP logs I can see the following:

```
[Trace - 05:03:40 pm] Received response 'buildTarget/scalaTestClasses - (13)' in 3ms
Result: null
Error: {
  "code": -32603,
  "message": "Internal error.",
  "data": "java.util.concurrent.CompletionException: scala.MatchError:  (of class mill.runner.MillBuildRootModule$BootstrapModule$build$)\n\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)\n\tat java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)\n\tat java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)\n\tat java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)\n\tat mill.bsp.worker.MillBuildServer.$anonfun$completable$1(MillBuildServer.scala:670)\n\tat mill.bsp.worker.MillBuildServer.$anonfun$completable$1$adapted(MillBuildServer.scala:658)\n\tat scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)\n\tat java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)\n\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)\n\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)\n\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)\n\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)\n\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)\nCaused by: scala.MatchError:  (of class mill.runner.MillBuildRootModule$BootstrapModule$build$)\n\tat mill.bsp.worker.MillScalaBuildServer.$anonfun$buildTargetScalaTestClasses$2(MillScalaBuildServer.scala:98)\n\tat mill.bsp.worker.MillBuildServer.$anonfun$completableTasks$2(MillBuildServer.scala:626)\n\tat scala.collection.immutable.List.map(List.scala:246)\n\tat scala.collection.immutable.List.map(List.scala:79)\n\tat mill.bsp.worker.MillBuildServer.$anonfun$completableTasks$1(MillBuildServer.scala:626)\n\tat mill.bsp.worker.MillBuildServer.$anonfun$completable$1(MillBuildServer.scala:661)\n\t... 8 more\n"
}
```

You can reproduce this by

- Creating a minimal mill project with the following build file:
```scala
import mill._
import mill.scalalib._

object milltest extends ScalaModule {

  def scalaVersion = "2.13.11"

  object test extends ScalaTests with TestModule.Munit {
    def ivyDeps = Agg(
      ivy"org.scalameta::munit::0.7.29"
    )
  }
}
```

- Opening the project with Metals
- Create a `.metals/bsp.trace.json` file
- Close and re-open the project again
- Don't import the build when prompted and instead do a `Metals: Switch build server` command and choose `mill-bsp`
- See the error in the logs

**Comment by julienrf** [comment]
I would like to kindly ping the maintainers about this issue. Do you intend to maintain BSP server implementation? Or should we tell the users to pick the bloop implementation instead? Is #2625 related to this issue? @lefou @lolgab

**Comment by lefou** [comment]
Thanks for the reminder. Yes, we do maintain our BSP server. But we are no robots. Please be aware, that we lack an automated test suite for our BSP server, so we always need some more time to review, reproduce, analyze and fix reported issues. If anybody wants to help out, we are very open to any kind of contributions.

Regarding bloop: There are various known issues with the bloop contrib module too, which is AFAICT in need of a maintainer. Hence I can not recommend to use the bloop contrib module over the built-in BSP server.

I think #2625 is unrelated to this issue.

**Comment by julienrf** [comment]
Thank you for your prompt responses!

> Yes, we do maintain our BSP server. But we are no robots.

I apologize if I sound harsh, I didn’t want to put pressure on you, I am extremely grateful for your work!

> Please be aware, that we lack an automated test suite for our BSP server, so we always need some more time to review, reproduce, analyze and fix reported issues. If anybody wants to help out, we are very open to any kind of contributions.

I see in https://github.com/scalameta/metals/pull/5320 that they seem to have a sort of automated test that caught the regression. Would it be technically possible to include such tests directly here?

**Comment by lefou** [comment]
> Thank you for your prompt responses!
> 
> > Yes, we do maintain our BSP server. But we are no robots.
> 
> I apologize if I sound harsh, I didn’t want to put pressure on you, I am extremely grateful for your work!

Thank you @julienrf! I totally believe that. I guess, the "pressure" is rather self-induced. There is my personal commitment on the one hand, and the perceived rough edges due to a rather hasty release on the other.

> > Please be aware, that we lack an automated test suite for our BSP server, so we always need some more time to review, reproduce, analyze and fix reported issues. If anybody wants to help out, we are very open to any kind of contributions.
> 
> I see in [scalameta/metals#5320](https://github.com/scalameta/metals/pull/5320) that they seem to have a sort of automated test that caught the regression. Would it be technically possible to include such tests directly here?

Thanks for the pointer. I can't tell right now, but I'll add it to the list of ideas I already have, once there is a bit more time.

**Comment by lefou** [comment]
Thank you, @lolgab, for the quick fix!
