### ISSUE TITLE
Cannot start repl

### ISSUE THREAD

**Issue by jilen** [com-lihaoyi/mill#2596]
Version: 0.11.0

Missing dependency `ammonite_2.13.11/3.0.0-M0-6-34034262`

**Comment by lefou** [comment]
Ammonite hasn't yet released a version for Scala `2.13.11`. For details, please read [this section](https://mill-build.com/mill/Scala_Module_Config.html#_using_the_ammonite_repl_scala_console) of the documentation.

There is already a PR for Scala 2.13.11 in the Ammonite repository

* https://github.com/com-lihaoyi/Ammonite/pull/1356
