### ISSUE TITLE
Changes to T.source inputs are ignored

### ISSUE THREAD

**Issue by informarte** [com-lihaoyi/mill#2618]
I am having an issue with `T.source`. Sources marked as such are not listed by `mill inspect` and changes to them are not picked up by mill, only build from scratch works. This is the project: https://github.com/informarte/yuck, branch `dev.`

In particular, the dependencies listed by `./mill inspect corePackage` are correct but incomplete. All the files defined by

```
    def documentation = T.source {millSourcePath / "doc"}
    def miniZincBindings = T.source {millSourcePath / "resources" / "mzn" / "lib" / "yuck"}
    def miniZincSolverConfigurationTemplate = T.source {millSourcePath / "resources" / "mzn" / "yuck.msc.in"}
    def unixStartScriptTemplate = T.source {millSourcePath / "resources" / "bin" / "yuck.in"}
    def winStartScriptTemplate = T.source {millSourcePath / "resources" / "bin" / "yuck.bat.in"}
    def debianControlFileTemplate = T.source {millSourcePath / "resources" / "debian" / "control.in"}
```

are missing.

**Comment by lihaoyi** [comment]
Can you minimize the problem? I'm not sure what the misbehavior is from your description and repo

**Comment by informarte** [comment]
Meanwhile I understood the issue; it's not caused by `mill` but by my build script. For compiling packages, it uses the `os.copy` method which does not replace already existing files by default. So building by scratch works fine and incremental building due to changes to Scala source files, too, but changes to all other files are ignored.
