### ISSUE TITLE
Bloop import doesn't work anymore

### ISSUE THREAD

**Issue by lolgab** [com-lihaoyi/mill#2622]
# Reproduction

Given a mill build like:
```scala
import mill._, scalalib._

object root extends RootModule with ScalaModule {
  def scalaVersion = "3.3.0"
}
```

```scala
mill --import ivy:com.lihaoyi::mill-contrib-bloop:  mill.contrib.bloop.Bloop/install
[build.sc] [48/49] runClasspath 
Cannot resolve external module mill.contrib.bloop.Bloop
```

**Comment by lefou** [comment]
I think the bloop plugin could be changed to inspect the module hierarchy in an evaluator command. Also, the way how the `Evaluator` is retrieved in the current implementation is also rather hack-ish and uses some implementation specific runtime characteristics.

**Comment by lolgab** [comment]
@lefou I don't think the import is the problem. Adding
```
import $ivy.`com.lihaoyi::mill-contrib-bloop:`
```
doesn't change the result.

**Comment by lefou** [comment]
Reviewing the bloop module tests then we must.

**Comment by lihaoyi** [comment]
From the discussion so far, it's not clear to me what the breakage is here yet. It could be in the ammonite removal, in the resolver rewrite, or somewhere else

**Comment by fiadliel** [comment]
This command does currently work, but is not in line with the usual pattern, or documentation.
```
mill --import ivy:com.lihaoyi::mill-contrib-bloop:  mill.contrib.Bloop/install
```

The object `Bloop` seems to be in the wrong package (`mill.contrib` instead of `mill.contrib.bloop`).

**Comment by lolgab** [comment]
Good catch @fiadliel. We broke the package by mistake.
Fixing it in #2628

**Comment by lefou** [comment]
Huh, how does this change slip in? Thanks for you eagle eyes @fiadliel .
