### ISSUE TITLE
Meta-Build is ignored by `GenIdea`

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#2633]
The generated Idea project does not have the necessary source directories under `mill-build/src`.

**Comment by lihaoyi** [comment]
GenIdea doesn't go through the proper bootstrap process, the same way that the 'mill.bsp.BSP` logic does in `State.scala`. It's probably missing a bunch of stuff as a result.

The proper fix would be to make GenIdea go through the proper bootstrap process as well. This might necessitate moving it from `mill.scalalib.GenIdea` to `mill.runner.GenIdea`, so it can properly access the `mill.runner.MillBuildBootstrap` logic

**Comment by lefou** [comment]
A new module is probably the better option, as it not really part of the runner but some IDE integration. We could make it a `contrib`, but that's kind-of degrading its support.

**Comment by lefou** [comment]
Meta-builds now work and code-navigation works even better now than before, where we relied on IntelliJ Ammonite support. If you get asked by IntelliJ IDEA whether you want to enable Ammonite script support for `build.sc` and friends, you can safely say "no".
