### ISSUE TITLE
Extend source file cache invalidation granularity to vanilla `.scala` files

### ISSUE THREAD

**Issue by lolgab** [com-lihaoyi/mill#2636]
Mill's current cache has cache invalidation which has build file granularity.
If you have two files `build.sc` and `other.sc` and `build.sc` imports `other.sc`, changes in `build.sc` don't invalidate caches for targets defined in `other.sc`.
This works only with `.sc` since they explicitly state dependencies via `import $file` imports.
It would be nice to extend this to vanilla Scala files.
[acyclic](https://github.com/com-lihaoyi/acyclic) can track dependencies between vanilla Scala files. We could use something like it to implement the same support we currently have for `*.sc` files to `*.scala` files in the `mill-build/src` directory.

**Comment by lihaoyi** [comment]
Superseded by https://github.com/com-lihaoyi/mill/pull/2417, which implements fine grained method-level code change invalidation that works the same for `.sc` files and `.scala` files alike (and `.java` files too)
