### ISSUE TITLE
make `interp` part of the `Module`

### ISSUE THREAD

**Issue by shengc** [com-lihaoyi/mill#265]
Or at least, make `interp.repositories()` the default choice of `Module.repositories` and `Module.scalaWorker.repositories` _unless_ it is empty. This way if somebody wants to globally reset `repositories`, he/she can specify the custom set in `predef.sc`.

**Comment by lihaoyi** [comment]
This seems reasonable

**Comment by lihaoyi** [comment]
Getting it the default choice for `Module.scalaWorker.repositories` might be hard though; the default `scalaWorker` gets defined globally, while `interp` is scoped to a particular build run.

**Comment by shengc** [comment]
is it possible to build in a macro to rewrite `build.sc` that overrides the `scalaWorker` with `interp.repositories` ?

**Comment by lihaoyi** [comment]
`repositories` has been part of `CoursierModule` for some time now, and https://github.com/com-lihaoyi/mill/pull/2377 makes this moot since there's no more `interp` (except `interp.watchValue` for backwards compat)
