### ISSUE TITLE
Lost ability to install Mill for GHA when build.sc is not at the project root

### ISSUE THREAD

**Issue by davesmith00000** [com-lihaoyi/mill#2660]
Hi,

I have a project that builds with a mix of Mill and sbt (for historical reasons), this means that neither sbt nor Mill live at the repo's root level. This worked fine we tried to upgrade to Mill 0.11.1, but now doesn't due to a recent change:

https://github.com/com-lihaoyi/mill/blob/1e5871a8a0740193b339030b420331dc90bca091/runner/src/mill/runner/MillBuildBootstrap.scala#L71

_(To answer to the question: "No, I'm not, but I will be." :smile:)_

The [setup-mill](https://github.com/jodersky/setup-mill) action can no longer install Mill for us, producing this error:

![image](https://github.com/com-lihaoyi/mill/assets/908709/d99f7fe3-dff7-49d2-b64b-0d23ae491ccb)

I realise that...

1. It will be suggested we use the bootstrap script thingy.
2. I can probably fix this by placing a dummy `build.sc` at the root.
3. This is an edge case, most people don't do this.

But I thought I'd raise the issue in case it was indicative of a wider problem. Feel free to close the issue based on any or all of the above reasons.

**Comment by lefou** [comment]
This should with the merge of #2662, which restores the defunct `version` command. But I think using `mill version` could be replaced by `mill --version` which should return much faster.
