### ISSUE TITLE
Errors stay stuck in Metals on VSCode when using mill-bsp

### ISSUE THREAD

**Issue by carlosedp** [com-lihaoyi/mill#2665]
Using latest Mill and Metals versions on VSCode, sometimes errors stay stuck in VSCode and Problems tab while using Mill BSP.

![image](https://github.com/com-lihaoyi/mill/assets/20382/6858eb6b-acea-430d-a2ef-cfa4e2195ff8)

As seen, the method `nonsensemethod` was added and removed but the error kept showing. After fixing the error usually I need to do a "Restart Build Server".

This is a followup from https://github.com/scalameta/metals/issues/4652 and apparently only happens when using Mill. On Bloop it works fine and the error goes away when fixed.

I've captured a sample on screen here: https://streamable.com/f00gmh

Although the video is a couple weeks old, the error still persists with latest Metals and Mill:

```
Metals Java: 17.0.7 from GraalVM Community located at /Users/cdepaula/Library/Caches/Coursier/arc/https/github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.2/graalvm-ce-java17-darwin-amd64-22.3.2.tar.gz/graalvm-ce-java17-22.3.2/Contents/Home

Metals Server version: 1.0.0+2-3776cef9-SNAPSHOT

Below are listed the build targets for this workspace. One build target corresponds to one classpath. For example, normally one sbt project maps to two build targets: main and test.

Build definition is coming from mill.

Build server currently being used is mill-bsp v0.11.1. ([Reset](command:metals.reset-choice?%5B%22Build+server+selection%22%5D))
```

According to @tgodzik

> Metals needs to get empty diagnostics for a file to clear the errors, so this might be an issue with Mill. Otherwise we would need to keep that information inside Metals, which I would prefer to avoid, since that might cause some unexpected issues.
> 
> If you do another error inside that file does it remove the old one? Does the situation with stale errors happens often when fixing all of them?

And the error goes away when forcing a new error.

Tomasz also mentioned after I sent some logs (attached to that issue):

> I don't see any empty diagnostics being sent, so I think that's the issue with stale errors. When everything is fixed Mill should send empty diagnostics with reset set to true.

**Comment by lefou** [comment]
* Looks related or probably duplicate to https://github.com/com-lihaoyi/mill/issues/2426
