### ISSUE TITLE
printlns interfere with show

### ISSUE THREAD

**Issue by miguel-vila** [com-lihaoyi/mill#2680]
Briefly discussed this in discord 

reproduced at [miguel-vila/mill-issue-repr](https://github.com/miguel-vila/mill-issue-repr)

expected behaviour:

`mill show foo.testTask` to be valid json without the result of any println

works in 0.10.1 , breaks in 0.11.0 and 0.11.1

**Comment by lihaoyi** [comment]
This is a regression, possibly related to https://github.com/com-lihaoyi/mill/pull/2428/files#diff-10fa43b77073c51ec13ec41ca13cf84707d831a39d344acad2d08a6f9bb1ee14. Needs to be fixed so that `show foo >` can work properly again
