### ISSUE TITLE
Target#apply() call cannot use `value ???` defined within the T{...} block

### ISSUE THREAD

**Issue by hmf** [com-lihaoyi/mill#2694]
I am reporting this for Mill 0.11.1.

I am trying to create a method that I can use within  a task. I am considering using an [anonymous tasks](https://mill-build.com/mill/Tasks.html#_anonymous_task). Unfortunately, I keep getting compilation errors. I then used the following code (adapted from the documentation):

```scala
  def anonTask(fileName: String): Task[String] = T.task {
    fileName + "Anon"
  }

  def helloFileData = T { anonTask("hello.txt")() }

  def printFileData(fileName: String) = T.command {
    Console.println(anonTask(fileName)())
  }

  def printFileData0(fileName: String) = T.command {
    val dir = T.dest.toString()
    Console.println(dir)
    // Target#apply() call cannot use `value dir` defined within the T{...} block
    // Console.println(anonTask(dir)())
    //  Target.ctx() / T.ctx() / T.* APIs can only be used with a T{...} block
    //Console.println(anonTask(T.dest.toString())())
  }

  def printFileData1 = T {
    val dir = T.dest.toString()
    Console.println(dir)
    // Target#apply() call cannot use `value dir` defined within the T{...} block
    // Console.println(anonTask(dir)())
    //  Target.ctx() / T.ctx() / T.* APIs can only be used with a T{...} block
    Console.println(anonTask(T.dest.toString())())
  }

``` 

Every time I try to use a variable that requires the `T.ctx` I get one of the following errors:

```
    Target#apply() call cannot use `value dir` defined within the T{...} block
    Target.ctx() / T.ctx() / T.* APIs can only be used with a T{...} block
```

This is strange and seems like a bug because the variables above are used within a `T.command`and a `T`. Is this correct? Do I need do something else to use these variables?

TIA

**Comment by lihaoyi** [comment]
this is a known limitation unfortunately. One workaround is to replace `def anonTask(fileName: String): Task[String]` with `def anonTask: Task[String => String]` and adjust the rest of the code accordingly

**Comment by hmf** [comment]
@lihaoyi My apologies for asking this, but I am not competent enough to solve this on my own. I tried the obvious:

```scala
  def anonTask = T.task {
    s:String => s + "Anon"
  }

 def helloFileData = T { anonTask()("hello.txt") }
```

This failed with:

```
  [error]  found   : String("hello.txt")
  [error]  required: mill.define.Applicative.ApplyHandler[mill.define.Task]
  [error]   def helloFileData = T { anonTask()("hello.txt") }
```

The previous code:

```scala
  def helloFileData = T { anonTask("hello.txt") }
```

fails as expected.  I get:

```  [error] ... no arguments allowed for nullary method apply: ()(implicit handler: mill.define.Applicative.ApplyHandler[mill.define.Task]): String => String in trait Applyable
  [error]   def helloFileData = T { anonTask("hello.txt") }
```
I did a search for `ApplyHandler` in the source code but it did not help me. 

Is there any code I can look at that does this?

TIA.
