### ISSUE TITLE
Generating bogus coordinates?

### ISSUE THREAD

**Issue by tballard** [com-lihaoyi/mill#2721]
In a scala.js module for scala 3.3.0, mill seems to want org.scala-lang:scala3-library_sjs1_3.3:3.3.0, according to ivyDepsTree, which shows it and resolvedIvyDeps which says it can't find it.  I'm guessing it should be generating a 1.3 in the artifact name instead of a 1.3.3, based on what is available online.

**Comment by lefou** [comment]
Can you provide more details, e.g. the concrete Mill output and your `build.sc`?

**Comment by tballard** [comment]
Well, it did it consistently for a couple of hours, and I eventually made it happy by downloading 1.3 local repo files and renaming them to 1.3.3. Today? Works just like yours! I'll be better about capturing data if I see it again.
