### ISSUE TITLE
`runBackground` redirects stdout and stderr to files instead of command line

### ISSUE THREAD

**Issue by lolgab** [com-lihaoyi/mill#2741]
It seems that the problem was introduced in https://github.com/com-lihaoyi/mill/pull/2377
In particular, the change was introduced in this commit: https://github.com/com-lihaoyi/mill/pull/2377/commits/1a43868ad7e50bf5dd480efec2f1bfc9c694a171

Before this PR `stdout` was redirected to mill's `stdout`, after it goes to `os.pwd / "stdout.log"` and `stderr` goes to `os.pwd / "stderr.log"`

**Comment by lihaoyi** [comment]
Probably going to call this a wontfix. The whole point of runBackground is you may have your terminal doing other things after, and so we can't just keep sending logs to the terminal after you call it. So to avoid just losing them, they have to go to log files, and people can tail the logs if necessary
