### ISSUE TITLE
Better scalaVersion handling in `MillBuildRootModule`

### ISSUE THREAD

**Issue by jilen** [com-lihaoyi/mill#2769]
The meta build use a hardcoded `2.13.10` scala version. 
If I want to force it use `2.13.11` (for jdk21),  sure I can create mill-build folder and set that version, but then it will use another recursive meta-build which use `2.13.10` again.

**Comment by jilen** [comment]
Seems already addressed #2768 just now!

**Comment by lefou** [comment]
Fixed. I'll later this day cut a snapshot release.
