### ISSUE TITLE
Publish `mill-scala-compiler-bridge` for Scala `2.13.12`

### ISSUE THREAD

**Issue by lolgab** [com-lihaoyi/mill#2798]

**Comment by lihaoyi** [comment]
If I'm not mistaken, 2.13.12 publishes their own compiler bridge (https://github.com/scala/scala/pull/10472), so we may be able to just reference theirs rather than continuing to publish our own

**Comment by lefou** [comment]
That mean, we need some new logic depending on the Scala version, right?

**Comment by lihaoyi** [comment]
Yes it should involve changing the code a bit

**Comment by lolgab** [comment]
I think that until we integrate with the current official published bridge, it's best to simply publish our `mill-scala-compiler-bridge` `0.0.1` for Scala `2.13.12` (not sure it's possible for just a Scala version) so Mill users can have the best experience as soon as possible.
