### ISSUE TITLE
Suggestion: Allow `clean` command to be used postfix, to be consistent with `compile`

### ISSUE THREAD

**Issue by davesmith00000** [com-lihaoyi/mill#2804]
Currently if you want to compile, test, or run a custom command on a project, you do this (examples from Indigo):

```
./mill demos.campfire.compile
./mill demos.campfire.test
./mill demos.campfire.runGame
```

..but if you want to clean it, you have to do this:

```
./mill clean demos.campfire
```

It would be really nice, if you could additionally use the same syntax as you use for everything else:

```
./mill demos.campfire.clean
```

**Comment by lefou** [comment]
I don't think this is a good idea, as it breaks with the perceived regularity of the hierarchical build structure and the associated CLI arguments. Just from looking at `./mill demos.campfire.clean` I would say clean is a target or command and `demo.campfire` the module, but that wouldn't hold any longer. Also, once we introduce something like that and use it, there is a high risk users are confused about the difference is between them.

**Comment by davesmith00000** [comment]
I suspect that's because you perceive, or know, a [technical] difference between the two.

I don't know, as a user, that there's any difference other than that it's _irregular_ compared to all the other instructions I can issue to a module, and I have to remember that difference, and cleaning the module is a faff. I can't just hit up on my terminal and change compile to clean, I have to remove .compile, move to the start of the line, and insert clean and then hit enter. Doesn't sound like much but.. 😬

Anyway, your call, of course. I guess I can always set up a custom command or something.

**Comment by lefou** [comment]
The `clean` command accepts a target pattern, so you have very fine control what to clean. E.g. you said you need to remove the `.compile` from your command, but if you just want to clean the compilation result, you can and should keep it: `./mill clean demos.campfire.compile` will clean only result of the `demos.campfire.compile` target. You can clean any target, or a pattern. E.g. to clean all compilation results but nothing else (e.g. preserve dependency resolutions), you can run `./mill clean __.compile`.
