### ISSUE TITLE
BUG: Regularly receiving 'Failed to connect to server' while working on build scripts

### ISSUE THREAD

**Issue by davesmith00000** [com-lihaoyi/mill#2805]
Here's a screenshot, this happens every 4-5 builds, and I can recover by doing `rm -fr out`.

![image](https://github.com/com-lihaoyi/mill/assets/908709/e4d35cb6-223a-462b-baff-5991911c2118)

Running using millw, Mill 0.11.4, VSCode + Metals (latest snapshot)

What I'm doing is working on the Mill build scripts and generated classes. My suspicion is that the Metals build import - which also uses millw I just discovered - is competing with my command line builds and one is corrupting or crashing the other (perhaps restarting the build server? Just a guess).

Here is the repo where I was doing the work:

https://github.com/davesmith00000/shaders

**Comment by lefou** [comment]
Are you removing the `out` dir or do you run `mill clean` on the cli?

**Comment by lefou** [comment]
Does your edit and generate process involve some manual removal of files in the `out` directory?

**Comment by davesmith00000** [comment]
Only overwriting generated sources.
