### ISSUE TITLE
BUG: Using `RootModule` does not write `fastLinkJS` `main.js` file

### ISSUE THREAD

**Issue by davesmith00000** [com-lihaoyi/mill#2806]
In the following repo: https://github.com/davesmith00000/shaders

Changing the following line in `build.sc` to use `RootModule` allows you to omit `shaders` from Mill commands - which is great!

```diff
-object shaders extends mill.Module {
+object shaders extends mill.RootModule {
```

So now I can run `./mill demos.campfire.compile` instead of `./mill shaders.demos.campfire.compile`.

However, if you try running `./mill demos.campfire.fastLinkJS`, no `main.js` file is written to `out/demos/campfire/fastLinkJS.dest` (the folder is empty). Changing back to a normal module and running `./mill shaders.demos.campfire.fastLinkJS` works correctly, the `main.js` file can be found in `out/shaders/demos/campfire/fastLinkJS.dest`.

Millw 0.4.7
Mill 0.11.4

**Comment by lolgab** [comment]
Did you also move the code from `shaders/demos/campfire/src` to `demos/campfire/src`?
I can't reproduce the issue, it seems to work fine.
Suggestion: I call my `RootModule` `root` to make it clearer that it's not an actual directory but the root of the project.

**Comment by davesmith00000** [comment]
I did not, that'll be the problem, thank you.

Interesting, that didn't align with my existing understanding / intuition around Mill. I think I'll probably leave it as it to keep my build more regular / consistent, and avoid special casing root, in that case.

Thanks again. :smile:

**Comment by lefou** [comment]
Alternatively, you could overwrite the `millSourcePath` of your root module to `shaders`.
