### ISSUE TITLE
release does not exists: releases/download/0.11.5/0.11.5-12-0d992b

### ISSUE THREAD

**Issue by wiltonlazary** [com-lihaoyi/mill#2841]
curl -L https://github.com/com-lihaoyi/mill/releases/download/0.11.5/0.11.5-12-0d992b

**Comment by lefou** [comment]
Yeah, the documentation currently only targets the latest commit in the `main` branch, whereas you're supposed to either read and use the latest stable version `0.11.5` or one of the published snapshots, which you can find on the release page. We don't publish every commit to be more responsible with Maven Central resources.

See also https://github.com/com-lihaoyi/mill/issues/2455

**Comment by lefou** [comment]
Please either use:
* current latest stable `0.11.5`: https://github.com/com-lihaoyi/mill/releases/download/0.11.5/0.11.5
* current latest snapshot `0.11.5-9-1cd494`: https://github.com/com-lihaoyi/mill/releases/download/0.11.5/0.11.5-9-1cd494
