### ISSUE TITLE
Error: resolution failed for 1 modules. Although COURSIER_REPOSITORIES is set.

### ISSUE THREAD

**Issue by luisvgs** [com-lihaoyi/mill#2854]
Hello, first of all thanks for the hard work that the team behind `mill` is putting on the tool. I wanted to check `mill` today by creating a small hello world program, but I'm getting the following error after running `mill App`:

```
[2/46] mill.scalalib.ZincWorkerModule.classpath 
1 targets failed
mill.scalalib.ZincWorkerModule.classpath 
Resolution failed for 1 modules:
--------------------------------------------
  com.lihaoyi:mill-scalalib-worker_2.13:0.11.0-M0 
	download error: Caught java.net.ConnectException (Connection refused (Connection refused)) while downloading https://packages.corp.com/artifactory/maven/com/lihaoyi/mill-scalalib-worker_2.13/0.11.0-M0/mill-scalalib-worker_2.13-0.11.0-M0.pom
```
After investigation I found this in the documentation: https://mill-build.com/mill/Scala_Module_Config.html#_maven_central_blocked. 

However, although I'm setting the `COURSIER_REPOSITORIES` variable the command's output is still the same. Any idea of what I'm doing wrong? I kindly ask for suggestions. Thanks in advance :-)

**Comment by lefou** [comment]
The URL in the error message (`https://packages.corp.com/artifactory/maven/...`) looks like it's already referring to your configured repository, so it seems you were successful with the setup, but your repository is refusing the connection. Is the URL correct? Have you tried to fetch the URL with another tool like `curl`?

**Comment by luisvgs** [comment]
As a quick update here @lefou, by using `millw` instead of `mill`, I was able to compile my program. 

```shell
~/p/milldemo λ ::->  ./millw helloworld  --mill-version 0.11.4 --disable-ticker version
No mill version specified.
You should provide a version via '.mill-version' file or --mill-version option.
Using mill version 0.11.5
[48/48] helloworld.run 
Hello World
```

**Comment by lefou** [comment]
@luisvgs Thanks for this update. This is very helpful for other. The in-repo `mill` script has no guaranteed support for older Mill versions. This is one of the reasons `millw` exists and is maintained outside of this repo, and why we recommend it in the installation docs.
