### ISSUE TITLE
BSP 'buildTarget/scalacOptions` classpath doesn't contain classses from this build target

### ISSUE THREAD

**Issue by jkciesluk** [com-lihaoyi/mill#2856]
Because of this Metals can't provide features like completions, hover for symbols from this build target.

**Comment by lefou** [comment]
Without looking up the sources and the BSP spec I don't understand the issue you describe and what exactly is missing. Can you elaborate?

**Comment by jkciesluk** [comment]
For example for https://github.com/com-lihaoyi/mill-scala-hello.g8 project, classpath for the build target looks like this
```
"file://.../scala-hello-world/scalaHelloWorld/compile-resources",
"file://.../Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.3.1/scala3-library_3-3.3.1.jar",
"file://.../Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10.jar"
```
But classpath in   `buildTarget/jvmRunEnvironment` for the same build target contains also
```
"file://.../scala-hello-world/scalaHelloWorld/resources",
"file://.../scala-hello-world/out/scalaHelloWorld/compile.dest/classes"
```
Without the last line, presentation compiler created in metals doesn't have information from other classes in the same build target. Adding `"file://.../scala-hello-world/out/scalaHelloWorld/compile.dest/classes"` also to `scalacOptions` response solves the problem.

We could probably work around it in Metals, but maybe it's an easy fix here?

**Comment by tgodzik** [comment]
So it looks like in Bloop and sbt it's put on the classpath when being sent via BSP while not being used for compilation. We can work around it in Metals as you are right in terms of the actual specification.

**Comment by lefou** [comment]
I think we should review the spec and make it clear what's expected to be in the respective requests. I think my interpretation outlined above should be correct, but maybe I'm wrong. returning different values in the same request as you said is done by bloop and sbt is most likely incorrect and should be fixed there and not worked around in Metals (except for compatibility with older versions). Unless I misunderstood. I'm going to close this issue for now, as I have no idea what I can _do_ about it.

**Comment by tgodzik** [comment]
I think it's fine as is. We can have a workaround, it's not a big deal. You are right that Mill is following the spec here.
