### ISSUE TITLE
Doc generation issue causing missing header

### ISSUE THREAD

**Issue by nafg** [com-lihaoyi/mill#2863]
If you go to https://mill-build.com/mill/Builtin_Commands.html#_inspect you see

> While `inspect` also works with the same `_`/`__` wildcard/query syntaxes that [resolve](https://mill-build.com/mill/Builtin_Commands.html#_resolve) do, the most common use case is to inspect one task at a time. == show

That `== show` should be a separate line generating a header but it got munged into the previous paragraph instead.

**Comment by lefou** [comment]
Thanks for reporting! Fixed.
