### ISSUE TITLE
Project structure read incorrectly in `0.11.6`

### ISSUE THREAD

**Issue by Gedochao** [com-lihaoyi/mill#2888]
This is a sequel to https://github.com/com-lihaoyi/mill/issues/2844, really, as it seems that `0.11.6` merely fails in a different way for https://github.com/VirtusLab/scala-cli now.

We tried to upgrade to `0.11.6` here: https://github.com/VirtusLab/scala-cli/pull/2572

It fails on our integration tests definition with:
```
[703/1155] runner[3.0.2].publishLocalNoFluff 
Publishing Artifact(org.virtuslab.scala-cli,runner_3,1.0.7-SNAPSHOT) to ivy repo /Users/pchabelski/IdeaProjects/scala-cli/out/repo/1.0.7-SNAPSHOT
[761/1155] test-runner[3.0.2].publishLocalNoFluff 
Publishing Artifact(org.virtuslab.scala-cli,test-runner_3,1.0.7-SNAPSHOT) to ivy repo /Users/pchabelski/IdeaProjects/scala-cli/out/repo/1.0.7-SNAPSHOT
[825/1155] runner[2.13.12].publishLocalNoFluff 
Publishing Artifact(org.virtuslab.scala-cli,runner_2.13,1.0.7-SNAPSHOT) to ivy repo /Users/pchabelski/IdeaProjects/scala-cli/out/repo/1.0.7-SNAPSHOT
[889/1155] test-runner[2.13.12].publishLocalNoFluff 
Publishing Artifact(org.virtuslab.scala-cli,test-runner_2.13,1.0.7-SNAPSHOT) to ivy repo /Users/pchabelski/IdeaProjects/scala-cli/out/repo/1.0.7-SNAPSHOT
[953/1155] runner[2.12.18].publishLocalNoFluff 
Publishing Artifact(org.virtuslab.scala-cli,runner_2.12,1.0.7-SNAPSHOT) to ivy repo /Users/pchabelski/IdeaProjects/scala-cli/out/repo/1.0.7-SNAPSHOT
[1017/1155] test-runner[2.12.18].publishLocalNoFluff 
Publishing Artifact(org.virtuslab.scala-cli,test-runner_2.12,1.0.7-SNAPSHOT) to ivy repo /Users/pchabelski/IdeaProjects/scala-cli/out/repo/1.0.7-SNAPSHOT
[1154/1155] integration.test.forkWorkingDir 
Unknown ctx of target integration.test.test: millbuild.build$CliIntegration$IntegrationScalaTests$TestHelper@50b4364
```

The important part seems to be the last line:
```
Unknown ctx of target integration.test.test: millbuild.build$CliIntegration$IntegrationScalaTests$TestHelper@50b4364
```

Which seems to be coming from here:
https://github.com/com-lihaoyi/mill/blob/423f174a81867e6bbfea85cbd1ca0a417e508380/main/eval/src/mill/eval/GroupEvaluator.scala#L134

My best guess is that the fix from #2883 doesn't fix it for our case.

`--disable-callgraph-invalidation` seems to make the integration tests pass, but that shouldn't be necessary.

**Comment by lihaoyi** [comment]
This looks like a code problem: you are defining a T.command inside the `class TestHelper`  that does not extend `mill.Module`. 

That is not expected to work: commands must be defined inside modules, and modules must be either `trait`s or `object`s

**Comment by Gedochao** [comment]
Right. So in other words, we've been using syntax that's no longer supported?

**Comment by lefou** [comment]
> This looks like a code problem: you are defining a T.command inside the `class TestHelper` that does not extend `mill.Module`.
> 
> That is not expected to work: commands must be defined inside modules, and modules must be either `trait`s or `object`s

Might be some copy and paste stuff, which I already fixed in `scala-js-cli`. https://github.com/VirtusLab/scala-js-cli/pull/39

**Comment by Gedochao** [comment]
@lefou right, thanks! 
Lemme try to apply your fixes from `scala-js-cli` in `scala-cli` then

**Comment by Gedochao** [comment]
Managed to make it work, thanks for the tips!
