### ISSUE TITLE
False warning in docs

### ISSUE THREAD

**Issue by asarkar** [com-lihaoyi/mill#2906]
https://mill-build.com/mill/Installation_IDE_Support.html#_build_server_protocol_bsp

> As of writing this, Metals 0.11.8 is the latest available version, which is not able to detect the fact, that Mill is already providing SemanticDB data. As a consequence, it reports missing SemanticDB data, although some SemanticDB-based features are already working. This may be fixed eventually in a future release of Metals.

According to [metals#5922](https://github.com/scalameta/metals/issues/5922#issuecomment-1845776710), this is no longer an issue.

**Comment by lefou** [comment]
> I believe they're saying this is not an issue already, and the warning is a false positive. The next Metals release would remove the warning, but the Mill docs could at least mention that the warning can be ignored. I spent few hours trying to get rid of the warning, so, I can see someone else also mislead by it.

I'm myself not a native English speaker, but the documentation is in my opinion exactly reproducing the current situation.

> As of writing this, Metals 0.11.8 is the latest available version, which is not able to detect the fact, that Mill is already providing SemanticDB data. As a consequence, it reports missing SemanticDB data, ...

This means, Metals will report an error

> ... although some SemanticDB-based features are already working. 

and this means, we already provide it.

> This may be fixed eventually in a future release of Metals.

and this means, the false positive reporter error will go away with some future release. 

But, as you currently witnessed, the falsely reported error isn't fixed yet.
