### ISSUE TITLE
Document project structure

### ISSUE THREAD

**Issue by asarkar** [com-lihaoyi/mill#2912]
AFAICT, a recommended project structure for Mill is non-existent. As a new user, I'm faced with the following issues:

1. The [Scala Days talk on YouTube](https://www.youtube.com/watch?v=UsXgCeU-ovI) doesn't demonstrate the use of any package or test directory. 
2. There's a [Hello World](https://alvinalexander.com/scala/mill-build-tool/step-1-hello-world/) project made by Alvin Alexander.
3. There's a [mill-scala-hello](https://github.com/com-lihaoyi/mill-scala-hello.g8) Gitter template.

2 and 3 differ substantially.

The Gitter template generates the following directory structure:
```
foo
├── build.sc
└── foo
    ├── src
    │   └── com
    │       └── example
    │           └── Hello.scala
    └── test
        └── src
            └── com
                └── example
                    └── HelloTest.scala
```

Although the top-level directory and the only Mill module are both named `foo`, it appears that this isn’t a requirement, and the top-level `foo` may contain multiple Mill modules named whatever necessary.

The package is under the `src` directories, and is `com.example` above.

This ticket asks that the following is clarified/documented:

1. **A recommended single-module project structure including unit tests and a non-default package** (i.e. files not directly under `src`). The assumption is that a multi-module project is simply a collection of several single-module (potentially interdependent) projects.
2. **Separation of Java and Scala source code** in a mixed project.
3. **Separation of unit and integration tests** in a multi-module project.
4. **Separation of main and test resources**.

A screenshot from the Scala Days talk is shown below as evidence that it doesn't answer any of the questions above.

![mill](https://github.com/com-lihaoyi/mill/assets/1302775/ab2f7454-f586-4c44-abf6-c5ae53c13c94)

**Comment by lihaoyi** [comment]
The recommended project templates are in the docs. There are quite a number of examples. Anything else is left up in the air, and I don't think there is consensus on a lot of it e.g. the folder layout within src/.

If you wish to discuss it you can open a thread on the discussions forum, but most of the  decisions you brought up are basically out of scope for Mill as of today

**Comment by lihaoyi** [comment]
https://mill-build.com/mill/Scala_Build_Examples.html

**Comment by asarkar** [comment]
I've studied the examples before opening the ticket, and they don't answer the questions posed above. I don't understand how these questions can be out of scope, because the tool would have it's own opinion about the structure. Sure, the structure can be customized, but that, by definition, means deviating from the default, and the default is unclear (to me).
