### ISSUE TITLE
Corrupted classpath for mill 0.11.6

### ISSUE THREAD

**Issue by yakivy** [com-lihaoyi/mill#2914]
I updated mill from `0.11.1` to `0.11.6` and started noticing weird compilation errors, probably wrong classpath order. Here is one I was able to isolate:

### Setup
- modules:
	- `repo1` with modules `service1` and `api1`
	- `repo2` with module `api2`
	- `api2` depends on artifact `api1`
	- `service1` depends on module `api1` and artifact `api2`
- there is a class `A` in `api1` that is changed, but `api2` still depends on old version

### Actual
- `service1` resolves `A` from `api2` instead of new version from module `api1`

### Expected
- `service1` resolves new version of `A` from `api1`

**Comment by yakivy** [comment]
We have mill plugin, so you will not be able to compile it as is, but it should give basic understanding:
- `service1/api1` `build.sc`
```
import $meta._
import $ivy.`com.lihaoyi::mill-contrib-playlib:$MILL_VERSION`
import $ivy.`com.org::mill:0.7.1`
import com.org.mill._
import coursier.maven.MavenRepository
import coursier.Repositories
import mill._
import mill.api.Loose.Agg
import mill.playlib._
import mill.scalalib._

object versions {
    val publish = "2.14.5"

    val scala212 = "2.12.18"
    val scala213 = "2.13.11"
    val scala3 = "3.3.0"

    val api2 = "6.2.1"

    val crossScala2 = Seq(scala212, scala213)
    val crossScala = crossScala2 ++ Seq(scala3)
}

trait BaseModule extends CustomScalaModule

trait LibModule extends BaseModule with CustomPublishModule with CrossScalaModule {
    override def publishVersion = versions.publish

    object test extends CustomPublishTests with ScalaTests
}

object server extends BaseModule with CustomPlayModule {
    override def scalaVersion = versions.scala213
    override def playVersion = versions.play

    override def ivyDeps = T(super.ivyDeps() ++ Agg(
        ivy"com.org::api2:${versions.api2}",
    ))

    override def moduleDeps = Seq(api(versions.scala213))

    object test extends CustomJavaTests with PlayTests
}

object api extends Cross[ApiModule](versions.crossScala)
trait ApiModule extends LibModule {
    override def artifactName = "api1"
}
```
- `api2` `build.sc`
```
object api extends Cross[ApiModule](versions.crossScala)
trait ApiModule extends BaseModule with CustomPublishModule with CrossScalaModule {
    override def publishVersion = versions.publish
    override def artifactName = "api2"

    override def ivyDeps = T(super.ivyDeps() ++ Agg(
        ivy"com.org::api1:${versions.api1}",
    ))
    object test extends BaseTests with CustomPublishTests
}
```

**Comment by lefou** [comment]
I still find it (too) hard to get your setup. Can you add a directory listing and also describe, how these projects depend on each other? Do you run a `publishLocal` or something like that?

**Comment by lefou** [comment]
Also, if you have a Mill plugin, make sure it declares it's dependencies to Mill jars via `compileIvyDeps`, otherwise you risk to bring multiple colliding Mill jars into the classpath.

**Comment by yakivy** [comment]
@lefou here is a setup that reproduces an error: https://github.com/yakivy/mill-issue-2914

**Comment by yakivy** [comment]
@lefou I put them into the same build.sc just for simplicity, these are two different projects in the real scenario. This issue can be solved with proper classpath ordering, I mean we can guarantee that module version should always have precedence over lib version. And 0.11.1 behaviour is consistend with SBT and Gradle behaviour, I'm surprised that you closed the issue.
Would it be ok if I fix it myself and create PR or is it something fundamentally wrong for you?

**Comment by lefou** [comment]
That all being argued, there are some special cases, which require more control over the classpath. If you're sure you'r in such situation and be ready to deal with the consequences (downstream!), you can override `compileClasspath` or any other classpath target and reorder it. IMHO, in contrast to the other build tools you names, Mill is very flexible in that regard. Do yourself a favor an put rich documentation to that hack and avoid to publish the library to a mainstream repository.

**Comment by yakivy** [comment]
> If you find a way to fix your issue by patching Mill, it would be of certain interest to me, how this looks like.

Ok, I'll try.

> once you publish such library, your downstream users will have a hard time

Probably you misunderstood the issue a bit, there should be no problem if you publish such library. If you depend on `service1:0.0.2` as a library that indirectly depends on `api1:0.0.2` and `api2:0.0.2` that indirectly depends on `api1:0.0.1`, only last version of `api1` will be used. The issue is only about interaction between libraries and modules, specifically about their order in classpath.

**Comment by lefou** [comment]
> Probably you misunderstood the issue a bit, there should be no problem if you publish such library. If you depend on `service1:0.0.2` as a library that indirectly depends on `api1:0.0.2` and `api2:0.0.2` that indirectly depends on `api1:0.0.1`, only last version of `api1` will be used. The issue is only about interaction between libraries and modules, specifically about their order in classpath.

That is a best case scenario! What if you delete some class, but have it still available on the compile classpath due to the older version of the same API? You risk to still depend on it. It's just one example of the unnoticed issues you may end up with. (Especially with an incremental compiler, that needs some consistence for it's own book keeping.) A library, that requires the new version of the API but some old API as well. There are ways to deal with it, discipline, tooling, ..., but IMHO you better invest the time to resolve the issues from the beginning. E.g. by excluding the transitive older version from `ivyDeps` (`ivy"com.github.yakivy::api2:0.0.1".exclude("com.github.yakivy_3" -> "api1")`).

**Comment by lefou** [comment]
> E.g. by excluding the transitive older version from `ivyDeps` (`ivy"com.github.yakivy::api2:0.0.1".exclude("com.github.yakivy" -> "api1_2")`).

I think it would make a nice feature request to support an `Artifact` as `exclude` parameter.

Then you could write:

```scala
def ivyDeps = Agg(
  // ...
).map(_.exclude(api1.publishSelfDependency()))
```

**Comment by yakivy** [comment]
> What if you delete some class, but have it still available on the compile classpath due to the older version of the same API?

This is not a case if you depend on `service1:0.0.2` as a library, there will be no `api1:0.0.1` in classpath at all. But I agree that this is valid issue during module to lib interaction when they both are in the classpath (i.e. on `0.11.1`).

> _.exclude(api1.publishSelfDependency())
You red my thoughts, this is exactly I wanted to suggest you as a default behaviour:
```
def ivyDeps = Agg(
  // ...
).map(_.excludeAll(moduleDeps.map(_.publishSelfDependency())))
```
this is pseudo code, but you should get the idea. What do you think? Is it valid as default?

**Comment by lefou** [comment]
It might make a good check and warn, but as a default I find it too invasive.
