### ISSUE TITLE
`T.input`s are evaluated twice

### ISSUE THREAD

**Issue by lolgab** [com-lihaoyi/mill#2946]
## Reproduction

```scala
import mill._

def foo = T.input{ println("bla") }
```

## Current behavior

```
mill foo
[1/1] foo 
bla
bla
```

## Expected behavior

It should print `bla` once:

```
mill foo
[1/1] foo 
bla
```

**Comment by lefou** [comment]
_Without any investigation of any kind, I remember some strange Scala behavior back from the 2.x times (where x < 10), that resulted in the compiler (?) executing a closure prematurely at definition time to get the actual return type. This is some dark memory, and I may totally reproduce it wrong, but I wanted to mention it at least once. If I find any reference to that issue, I will add it later..._
