### ISSUE TITLE
Add ability to alias Modules (specially external modules)

### ISSUE THREAD

**Issue by caeus** [com-lihaoyi/mill#299]
In the spirit of [issue 259](https://github.com/lihaoyi/mill/issues/259), wouldn't it be nice to give Mill the capability to alias commands and/or (external?) modules?
So if someone working creating an External Module with a long package name can therefore call an easy to remember alias than the whole package name plus slash plus target.

**Comment by uosis** [comment]
As a workaround, something like this can be added to the `./mill` wrapper script:

```shell
if [ "$1" = "bloop" ] ; then
  exec $MILL_EXEC_PATH mill.contrib.Bloop/install
elif [ "$1" = "idea" ] ; then
  exec $MILL_EXEC_PATH mill.scalalib.GenIdea/idea
else
  exec $MILL_EXEC_PATH "$@"
fi
```
A bit better than global shell alias.

**Comment by carlosedp** [comment]
Nice that this is "built-in" and documented but just a heads-up that my plugin allows one to define an alias that calls a sequence of other modules or commands.
