### ISSUE TITLE
Silent failures when calling helpermodule.run from tasks

### ISSUE THREAD

**Issue by swaldman** [com-lihaoyi/mill#3010]
In the spirit of https://mill-build.com/mill/Extending_Mill.html#_using_scalamodule_run_as_a_task (Thanks @lihaoyi!), I've tried to call the `run` task on a helper module from a task in my main module.

My build compiles, and my main-module task seems to succeed, but the call to helper-module's task.run() seemed silently to be ignored. Messing around, the call to run seems to succeed if it is the last instruction in (or constitutes the result of) its task, but silently fails otherwise.

Here's a minimal reproduction (mill v0.11.6):

**build.sc:**
```scala
import mill._, scalalib._

object helpermod extends JavaModule {}

object mainmod extends JavaModule {
  override def moduleDeps = Seq( helpermod )

  def runHelper = T {
    println("Before run()")
    helpermod.run()
    //println("After run()")
    //PathRef(T.dest)
  }
}
```

**helpermod/src/pkg/Main.java:**
```java
package pkg;

class Main {
    public static void main( String[] argv ) {
        System.out.println("Hello!");
    }
}
```

Like this, everything works beautifully:

```plaintext
% mill mainmod.runHelper
[build.sc] [49/53] compile 
[info] compiling 1 Scala source to /Users/swaldman/development/playpen/mill-wont-run-submodule/out/mill-build/compile.dest/classes ...
[info] done compiling
[build.sc] [53/53] methodCodeHashSignatures 
Before run()
[24/38] helpermod.compile 
[info] compiling 1 Java source to /Users/swaldman/development/playpen/mill-wont-run-submodule/out/helpermod/compile.dest/classes ...
[info] done compiling
[37/38] helpermod.run 
Hello!
[38/38] mainmod.runHelper 
% mill mainmod.runHelper
[37/38] helpermod.run 
Hello!
```

But if you comment in either or both of `//println("After run()")` or `//PathRef(T.dest)`, the call to helper module run seems silently to be ignored.

```plaintext
% rm -rf out            
% mill mainmod.runHelper
[build.sc] [49/53] compile 
[info] compiling 1 Scala source to /Users/swaldman/development/playpen/mill-wont-run-submodule/out/mill-build/compile.dest/classes ...
[info] done compiling
[1/1] mainmod.runHelper 
Before run()
After run()
```

I'm pretty sure the helper module code is not being run. It's not just a streams-getting-swallowed issue. I've tried having the Java code write a file. The file appears when the call to run is the last instruction, does not appear otherwise.

You can also see the issue in `mill plan`. When the call to `helpermod.run()` is the last instruction, a lot of steps are planned. When either of the subsequent lines are uncommented, it's just...

```plaintext
% mill plan mainmod.runHelper
[build.sc] [49/53] compile 
[info] compiling 1 Scala source to /Users/swaldman/development/playpen/mill-wont-run-submodule/out/mill-build/compile.dest/classes ...
[info] done compiling
[1/1] plan 
mainmod.runHelper
```

I've also tried letting `math.random()` be the final line of the task, for fear that somehow the constant task result misleads `mill` to skip the task. `mill` also fails to plan or execute `helpermod.run()` if `math.random()` is the result of `mainmod.runHelper`.

**Comment by swaldman** [comment]
Thanks @lolgab!

I needed an extra set of parentheses after the call to `run()`.

**Comment by lefou** [comment]
As a rule of thumb: __To call a target you always need one pair of parenthesis more, than the definition of the target has.__

`Target`s and `Input`s are defined with zero parens, so you need one pair. `Command`s have one parameter list, so when called you need to use two. `Task`s (anonymous task) may have any count or parameter lists. The extra pair of parentheses ( `()` ) are the actual target application `.apply()`, which will return the result.

**Comment by swaldman** [comment]
@lefou Thank you! This is very helpful.

There are aspects of all this that still confuse me -- the fact that the arguments to run have to be an anonymous task, `T` is not in scope in arguments for e.g. `T.dest` but `T.task(...)` is in scope remains a bit obscure to me. But, despite my not-quite-full understanding of things, mimicking the example in the docs, things seem to be working now!

My weird three-levels-of-code-generation via `ant` for a library initially built in 2002 is now much more concisely and simply reproduced in `mill`. It might become practical for me to maintain this library again.

Thanks again @lefou @lolgab @lihaoyi!

**Comment by lefou** [comment]
> There are aspects of all this that still confuse me -- the fact that the arguments to run have to be an anonymous task, `T` is not in scope in arguments for e.g. `T.dest` but `T.task(...)` is in scope remains a bit obscure to me.

Unfortunately, I'm not quite sure what you mean here. Anonymous tasks also have a context that gives you access to a `dest`. The essential point is, that anonymous tasks will be executed in the context of their outer cached task, in your case the command. So, `T.dest` of an anonymous task you use in a `Command` will be identical to the `T.dest` of that command.

**Comment by swaldman** [comment]
_What follows is me responding by making an exercise of answering all my own questions! Please don't feel like you have to devote any time to this. I did manage to answer most of my questions. Only the last two paragraph contains stuff that does continue to puzzle me, mysteries of `mill` internals._ 

_Thank you for all of your help!_

---

Oh, my confusion was naive, I can answer my question myself just by reviewing the definition of [`object Target`](https://github.com/com-lihaoyi/mill/blob/3335d2a2f7f33766a680e30df6a7d0dc0fbe08b3/main/define/src/mill/define/Task.scala) to which `val T` [is assigned](https://github.com/com-lihaoyi/mill/blob/3335d2a2f7f33766a680e30df6a7d0dc0fbe08b3/main/src/mill/package.scala). Reviewing the methods of `object Target`, I can see that `T.dest` (or `Target.dest`) requires an implicit `ctx`, while `T.task` does not, requires only an explicit `=> U` (that will be implicity converted to [`Result[U]`](https://github.com/com-lihaoyi/mill/blob/3335d2a2f7f33766a680e30df6a7d0dc0fbe08b3/main/api/src/mill/api/Result.scala).)

But this was the first time I'd called a command from a task, so things seemed a bit weird!

1. At first I did not realize that I was defining a dependency of my task, not just executing instructions in-line within my task
2. Once I did get that, I understood why stuff life `T.dest(...)` didn't work.
3. But, naively, I was thinking of task context not in terms of the actual-but-invisible implicit `ctx`, but in some sense having access to utilities of `T`. Stepping back this is dumb: I write `T{}` or `T.persistent {}` or `T.command {}` at top-level all the time. Nevertheless, what surprised me, struck me as weird, as that I did not have access to `T.dest` where I did have access to `T.task`. Again, this was dumb of me, but perhaps I'm not alone in this kind of mishypothesis. This was the first time I've ever used `T.task` to create an anonymous task, so it wasn't intuitive to me whether `T.task` was like `T.perisistent`, callable at top level, of `T.dest`, only accessible within a context. Since the reason I needed `T.task` was because I couldn't write `T.dest`, it surprised me that this other `T.` resource worked.

This is all pretty clear to me now. Part of your explanation still is not, because the role of anonymous tasks is still new to me.

> Anonymous tasks also have a context that gives you access to a dest. The essential point is, that anonymous tasks will be executed in the context of their outer cached task, in your case the command.

I make an anonymous `Task[Args]` object, effectively at top-level even though syntactically it's nested within a `Task`. That's fine and necessary, and users of mill should get that tasks within task-ish things — `Target` calls — are upstream dependencies, not ordinary function calls in sequence.

(Sometimes I wonder if `apply()` was the right choice, rather than some more explicit `def !` or something. The looks-like-just-a-function-call is comforting perhaps to first-glancers, but maybe a bit misleading?)

So I have a `Task[Args]` which I defined logically at top-level, independently of any task. I simply provide that to `JavaModule.run(args: Task[Args])`, which is straightforward enough.

(A bit surprisingly straightforward! I actually expected a bit more magic here. I expected I'd be able to use the same pattern to call a `runMain` either with just `Task[Args]` or with `(String, Task[Args])`, and was surprised only `run()` works. I guess `runLocal` would too, since it is defined as accepting `Task[Args]`, but no `runMain` variations, which are defined as accepting `(String, String*)`.)

How does this `Task[Args]` object, constructed in advance and simply passed as an argument, inherit some outer task's context?

Writing this out, I can almost answer that for myself. Anonymous tasks like other tasks are given effect only when that effect-giving `def apply()(implicit handler : ApplyHandler[Task])`. So conceptually, I think, I should think that an anonymous task inherits its task context from the task in which `apply()` is invoked upon it, right?

The [`ApplyHandler`](https://github.com/com-lihaoyi/mill/blob/3335d2a2f7f33766a680e30df6a7d0dc0fbe08b3/main/define/src/mill/define/Applicative.scala) logic confuses me, because I think we'd want to capture a `Task[T]` but it looks to me like it unwraps that to just `T`? And the implicit `ApplyHandler[Task]` exists as a `@compileTimeOnly` construct, but then calling the effect-giving `apply()` requires a concrete `ApplyHandler[Task]` to call `def apply[T](t: M[T]): T`, an abstract method which as far as I can find is never defined by a concrete implementation?

It is here I am finally out of my depth, even when I try to walk myself carefully through the source code!

**Comment by lefou** [comment]
The `@compileTimeOnly` is used to provide a nice error message where some `T`-API used in inappropriate locations, e.g. a `T.dest` outside of an `T{ }`.

Since the concept of the `ApplyHandler` is something that's only used in the macro code, you won't find any referenced to this code elsewhere. It's a while since I studied the macro code, and unfortunately, there are no comments explaining what's going on, so currently, I can only guess myself, but I think the `ApplyHandler` stuff is unrolled in the macro and replaced by something else.
