### ISSUE TITLE
Module resource folder is ignored or overriden by another module dependency

### ISSUE THREAD

**Issue by domagojlatecki** [com-lihaoyi/mill#3012]
Mill version: `0.11.3`
OS: `Darwin (macOS) 14.2.1 23C71`
Java: `openjdk version "17" 2021-09-14`

I was updating Mill from `0.11.1` to `0.11.7` (later I found that problem occurs from `0.11.3` onwards) and I noticed that some of my tests have started failing because of database connection issues.

After further investigation I figured out that the problem is that tests are not using the `application.conf` provided in the resource folder of the tests, but `application.conf` from the main resources folder. The simplified build structure is something like this:

`buildSrc/Common.sc`:

```
trait MyScalaModule extends mill.scalalib.ScalaModule with ScalafmtModule with ScoverageModule with Bloop.Module {
  outer =>

  private def path = {
    val segments = super.millSourcePath.segments.toList
    os.root / segments.init / "src" / segments.last
  }

  override def scalaVersion       = T(Versions.Compiler.Scala)
  override def scoverageVersion   = T(Versions.Tools.Scoverage)
  override def scalacOptions      = T(Settings.Compiler.ScalacOptions)
  override def millSourcePath     = path / "main"
  override def intellijModulePath = millSourcePath
  override def sources            = T.sources(millSourcePath / "scala")
  override def resources          = T.sources(millSourcePath / "resources")

  trait Tests extends ScalaTest with ScalafmtModule with ScoverageTests with Product {
    override def millSourcePath       = outer.path / productPrefix
    override def intellijModulePath   = millSourcePath
    override def sources              = T.sources(millSourcePath / "scala")
    override def resources            = T.sources(millSourcePath / "resources")
    override def defaultCommandName() = "test"

    override def ivyDeps = Agg(
      ivy"org.scalatest::scalatest:${Versions.Dependencies.Test.ScalaTest}",
      ivy"org.typelevel::cats-effect-testing-scalatest::${Versions.Dependencies.Test.CatsEffectTesting}"
    )

    override def runIvyDeps = outer.runIvyDeps
  }

  case object unitTest extends Tests

  case object integTest extends Tests {
    override def moduleDeps = Seq(unitTest)
    override def ivyDeps    = Agg(
      ivy"org.testcontainers:testcontainers:${Versions.Dependencies.Test.TestContainers}",
      ivy"org.testcontainers:postgresql:${Versions.Dependencies.Test.TestContainers}"
    )
  }

  case object apiTest extends Tests {
    override def moduleDeps = Seq(integTest)
    override def ivyDeps    = Agg(
      ivy"org.http4s::http4s-ember-client:${Versions.Dependencies.Http4s}"
    )
  }
}
```

`build.sc`:

```
import $file.buildSrc.Common, Common.ScalaModule

object app extends MyScalaModule {
  override def mainClass = T(Some(Settings.Project.MainClass))
}
```

So basically I have 3 test sets inside `app` module: `unitTest`, `integTest` and `apiTest`. `integTest` depends on `unitTest` and `apiTest` depends directly on `integTest` and transitively on `unitTest`.

After upgrading Mill version, `apiTests` are failing. This is happening because classpath of `apiTest` for some reason does not use `app/apiTest/resources/application.conf` but it uses `app/main/resources/application.conf` instead. Furthermore, if I put `application.conf` into `app/unitTest/resources/` then it works again as intended. So it seems that for some reason `apiTest` resources are either ignored or overriden by other resources.

This was working okay before I upgraded MIll version, without any changes in my project structure. I did some more investigating and found that on Mill version `0.11.2` it works fine but stops working on `0.11.3`. Looking at the code changes in `0.11.3` I managed to find what was causing the problem.

[This](https://github.com/com-lihaoyi/mill/compare/0.11.2...0.11.3#diff-e82bdaaa8eb3c540c1998b0b2837203d619551cbc7345733f5593ef2a3559d59R424-R426) is the change that I found is causing the issue that I have. When I add
```
override def runClasspath =
   localClasspath() ++ upstreamAssemblyClasspath()
```
to `buildSrc/Common.sc` inside `apiTest` object, the `application.conf` resource from `apiTest` is correctly resolved.

So I don't understand if I did something wrong in my setup or is there some other issue here? When I run `mill show app.apiTest.resources` I see:
```
[
  "ref:v0:b8a0b120:/Users/domagoj/Projects/finance-manager-backend/src/app/apiTest/resources"
]
```

`mill show app.apiTest.runClasspath`:

```
[
  ...,
  "ref:v0:c984eca8:/Users/domagoj/Projects/finance-manager-backend/src/app/integTest/compile-resources",
  "ref:v0:c984eca8:/Users/domagoj/Projects/finance-manager-backend/src/app/integTest/resources",
  "ref:v0:f308ff48:/Users/domagoj/Projects/finance-manager-backend/out/app/integTest/compile.dest/classes",
  "ref:v0:c984eca8:/Users/domagoj/Projects/finance-manager-backend/src/app/unitTest/compile-resources",
  "ref:v0:1447bcf6:/Users/domagoj/Projects/finance-manager-backend/src/app/unitTest/resources",
  "ref:v0:a0306386:/Users/domagoj/Projects/finance-manager-backend/out/app/unitTest/compile.dest/classes",
  "ref:v0:c984eca8:/Users/domagoj/Projects/finance-manager-backend/src/app/main/scoverage/compile-resources",
  "ref:v0:51f0f36b:/Users/domagoj/Projects/finance-manager-backend/src/app/main/resources",
  "ref:v0:15c071dd:/Users/domagoj/Projects/finance-manager-backend/out/app/buildInfoResources.dest",
  "ref:v0:aabc4b67:/Users/domagoj/Projects/finance-manager-backend/out/app/scoverage/compile.dest/classes",
  "ref:v0:c984eca8:/Users/domagoj/Projects/finance-manager-backend/src/jooq/main/compile-resources",
  "ref:v0:39c2e644:/Users/domagoj/Projects/finance-manager-backend/src/jooq/main/resources",
  "ref:v0:b349e1c3:/Users/domagoj/Projects/finance-manager-backend/out/jooq/compile.super/mill/scalalib/ScalaModule/compile.dest/classes",
  "ref:v0:c984eca8:/Users/domagoj/Projects/finance-manager-backend/src/app/apiTest/compile-resources",
  "ref:v0:b8a0b120:/Users/domagoj/Projects/finance-manager-backend/src/app/apiTest/resources",
  "ref:v0:b9e148cc:/Users/domagoj/Projects/finance-manager-backend/out/app/apiTest/compile.dest/classes"
]
```

`mill show app.apiTest.compileClasspath`:

```
[
  ...,
  "ref:v0:c984eca8:/Users/domagoj/Projects/finance-manager-backend/src/app/integTest/compile-resources",
  "ref:v0:f308ff48:/Users/domagoj/Projects/finance-manager-backend/out/app/integTest/compile.dest/classes",
  "ref:v0:c984eca8:/Users/domagoj/Projects/finance-manager-backend/src/app/unitTest/compile-resources",
  "ref:v0:a0306386:/Users/domagoj/Projects/finance-manager-backend/out/app/unitTest/compile.dest/classes",
  "ref:v0:c984eca8:/Users/domagoj/Projects/finance-manager-backend/src/app/main/scoverage/compile-resources",
  "ref:v0:aabc4b67:/Users/domagoj/Projects/finance-manager-backend/out/app/scoverage/compile.dest/classes",
  "ref:v0:c984eca8:/Users/domagoj/Projects/finance-manager-backend/src/jooq/main/compile-resources",
  "ref:v0:b349e1c3:/Users/domagoj/Projects/finance-manager-backend/out/jooq/compile.super/mill/scalalib/ScalaModule/compile.dest/classes",
  "ref:v0:c984eca8:/Users/domagoj/Projects/finance-manager-backend/src/app/apiTest/compile-resources"
]
```

**Comment by lefou** [comment]
So, did I read correctly? You have multiple `application.conf` on the classpath, but depend on the order of them, as you just read the first?

**Comment by domagojlatecki** [comment]
That is correct, but now that you mentioned it I realise that I should probably not rely on load order of `application.conf` resources. I should change my application setup and name the test file differently.

**Comment by lefou** [comment]
Exactly. If you depends on ordering, even if it works when locally testing, it might suddenly stop working at production or on another machine.

**Comment by domagojlatecki** [comment]
Thank you for pointing this out. I managed to fix the problem by renaming the main `application.conf` to `reference.conf` - that way I can keep using `application.conf` in the tests and it also covers the production case when `application.conf` needs to be loaded from outside the app.
