### ISSUE TITLE
IntelliJ BSP does not mark `out/` and `.idea/` folders as excluded (500USD Bounty)

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#3015]
---

**From the maintainer Li Haoyi**: I'm putting a 500USD bounty on this issue, payable by bank transfer on a merged PR implementing this.

---

This causes search and indexing to often waste large amounts of time digging through generated files in those folders when I really only care about the source code

Somehow `.bsp/` is marked as excluded but the other two aren't

**Comment by lefou** [comment]
How have you checked? Also, isn't it the responsibility of IntelliJ IDEA to ignore folders itself manages like `.idea`? Mill isn't creating it in BSP mode. Also, it would be in general a good idea to ignore paths that are in `.gitignore` and likewise repository configuration files.

Is there some way to even tell a BSP client, to ignore some resources? In the end, BSP should be all about what to include in some search, as it explicitly is about sources and resources, and not what to exclude. I'm tempted to say, this isn't an issue in Mill at all. At least, nothing Mill could or should control.

**Comment by lihaoyi** [comment]
It's visible in the file tree. Excluded folders are red, e.g. `.bsp/` below:

<img width="284" alt="Screenshot 2024-02-19 at 9 04 25 AM" src="https://github.com/com-lihaoyi/mill/assets/934140/9ca98fa1-32d0-4747-a9aa-14ff03ec8760">


We used to mark `out/` as excluded back in the `mill.scalalib.GenIdea` days:

https://github.com/com-lihaoyi/mill/blob/4a65cea4dceaddf1db663b77589817e016eb57f3/idea/src/mill/idea/GenIdeaImpl.scala#L715-L717

But I don't see that happening today using `mill.scalalib.GenIdea`, so we might have dropped it accidentally at some point. 

BSP import marks `.bsp/` as excluded, but not `out/` or `.idea/`

I don't know which system is at fault here, and marking it excluded manually is not a huge hardship. But given we used to be able to make this work, and now it doesn't, I think having an issue here is reasonable

**Comment by lihaoyi** [comment]
Looks like there's been prior discussion on this w.r.t. IntelliJ and BSP, and it should be supported as of about 18 months ago

https://github.com/build-server-protocol/build-server-protocol/issues/205

**Comment by pawelsadlo** [comment]
I will try to get it done

**Comment by pawelsadlo** [comment]
Isn't it a bug that mill build module is showing only build.sc in content?
and name is "mill-build_" instead of "mill-build"

<img width="881" alt="image" src="https://github.com/user-attachments/assets/e4c43726-01d1-417e-9a30-3f080551a838">

If I import mill repo, its content root is a directory where mill file is located.
<img width="1012" alt="image" src="https://github.com/user-attachments/assets/3fdc758f-b28e-4ce7-9549-fa9a5c84c6f4">


@lihaoyi

**Comment by lihaoyi** [comment]
@pawelsadlo we just ned to make sure navigation and jump to sources work in both the build files and application code. The exact layout of the intellij module metadata doesn't really matter

**Comment by lefou** [comment]
Yeah, ideally, we would want to use the directory containing the `build.sc` as source directory, but it's also containing all the sub-modules, which IDEA can't handle. So what you see is lots and lots of workaround found the hard way by try and error to map our project structure into the limited world IntelliJ IDEA understands.
