### ISSUE TITLE
Non-bootstrapped tests might fail when building mill against java9  

### ISSUE THREAD

**Issue by Baccata** [com-lihaoyi/mill#302]
Here's a minimal example that allows to reproduce the problem (make sure you're compiling using JDK 9) https://github.com/lihaoyi/mill/compare/master...Baccata:bootstrapping-issue?expand=1

Running `mill main.test` eventually yields to the following error : 

```
interpBridge.sc:7: not found: value x
extends mill.define.BaseModule(ammonite.ops.Path("..."), x = 1)
```

The problem was found in this PR : https://github.com/lihaoyi/mill/pull/291. 

I'll try and investigate further when time permits it.

**Comment by Baccata** [comment]
Referencing an arbitrary new class in the code wrapper rather than referencing a new field of a new existing class succeeds.

**Comment by Baccata** [comment]
@lihaoyi, from what I gather, when`mill main.test` is called, the output of `runClasspath`gets fed to a ScalaWorker which starts as a subprocess, which in turn loads the tests and runs them in its own JVM. 

The classpath appears to be propagated correctly in Java9, so I suspect some difference of behaviour in the classloader between java8 and java9. 

Here's my question : the `worker` depends on `main`, so when the ScalaWorker runs the tests, it's bound to load some classes from `main` from the installed mill, before it starts loading the classpath from the mill being built/tested. How do you make sure the classes from the `built` mill actually get loaded and override the already loaded one ?

**Comment by lihaoyi** [comment]
`ScalaWorker` is meant to run tests in an isolated classloader with minimal leakage (basically only the SBT test interface)

https://github.com/lihaoyi/mill/blob/master/scalalib/src/mill/scalalib/Lib.scala#L210

could it be the way isolated classloaders work in Java 9 has changed?

**Comment by Baccata** [comment]
I think I found the cause :  https://github.com/lihaoyi/mill/blob/8bd438bf84c1b221bcc122b3abe5d4ec37495071/core/src/mill/util/ClassLoader.scala#L47

To be honest I don't know what an appropriate solution would be, my knowledge of classloaders and the differences between 8 and 9 being very limited..

**Comment by lihaoyi** [comment]
Probably gonna call this fixed, since we run all tests against JVM 17 nowadays, most against JVM 8 as well, and it seems to work
