### ISSUE TITLE
Tasty files are not deleted

### ISSUE THREAD

**Issue by lolgab** [com-lihaoyi/mill#3068]
When deleting a class in Scala `3.4.0`, the depending files don't stop seeing the deleted class.
Checking the `out/compile.dest/classes` directory inside I noticed that the class files are deleted while the tasty files are still there.

### Reproduction
```scala
// build.sc
import mill._
import scalalib._

object root extends RootModule with ScalaModule {
  def scalaVersion = "3.4.0"
}
```

```scala
// src/file1.scala
def foo = 1
```

```scala
// src/file2.scala
def bar = foo
```

Run:
```
mill -w compile
```

Delete or comment `file1.scala`

The compilation succeeds.

Switching to Scala `3.3.3` the compilation fails as it should be.

**Comment by lefou** [comment]
Sounds like an upstream issue in zinc to me.

**Comment by lolgab** [comment]
Sbt works fine though.

**Comment by lefou** [comment]
That's surprising, since Mill isn't handling any kind of class file removal based on source fies. All it does is ensuring the classes directory exists when invoking zinc API with a target path (dir for class files or JAR file) and zinc is managing it's state. Also, the same code path in Mill is used for compilation with Scala 3.3.3 and 3.4.0, so it should behave equally with both.

**Comment by lefou** [comment]
> Sbt works fine though.

@lolgab Which sbt version, which zinc version?

**Comment by lefou** [comment]
It could be related to the fact, that we are including the current compilation output directory in the classpath we feed to the compiler. Don't know whether this is supposed to be the correct invocation, but it worked for a long time.

**Comment by lolgab** [comment]
Wow, that was a very good catch!
Removing `++ Some(classesDir)` fixes the problem 😲 
👏

**Comment by lefou** [comment]
Would be interesting to check how others invoke zinc.

**Comment by lefou** [comment]
It's worth to mention that class file removal worked as expected. It's only the `tasty` file(s), which don't get deleted since scalac 2.4.0.

Compilation with `file1.scala`:

```
scratch-3068-class-removal/out/compile.dest/classes/
scratch-3068-class-removal/out/compile.dest/classes/file2$package.class
scratch-3068-class-removal/out/compile.dest/classes/file1$package.tasty
scratch-3068-class-removal/out/compile.dest/classes/file1$package$.class
scratch-3068-class-removal/out/compile.dest/classes/file1$package.class
scratch-3068-class-removal/out/compile.dest/classes/file2$package$.class
scratch-3068-class-removal/out/compile.dest/classes/file2$package.tasty
11:19:14 ⏚ lefou:~/work/opensource/mill main(+1/-1)+* ± find scratch-3068-class-removal/out/compile.dest/classes/
```

After incremental compilation with a blank `file1.scala`:

```
scratch-3068-class-removal/out/compile.dest/classes/
scratch-3068-class-removal/out/compile.dest/classes/file2$package.class
scratch-3068-class-removal/out/compile.dest/classes/file1$package.tasty
scratch-3068-class-removal/out/compile.dest/classes/file2$package$.class
scratch-3068-class-removal/out/compile.dest/classes/file2$package.tasty
```

**Comment by lefou** [comment]
Looks like we have two issues here:

One is the fact, that with scalac 2.4.0, the compilation no longer failes with the blank `file.scala`. I assume some internal change, which no longer associates the input classpath files with the output files. We seem to fix this one with PR #3071.

The other it the removal of the tasty files, which is what the title of this issue is about. This still persists after PR #3071.



Compilation with `file1.scala`:

```
out/compile.dest/classes/
out/compile.dest/classes/file2$package.class
out/compile.dest/classes/file1$package.tasty
out/compile.dest/classes/file1$package$.class
out/compile.dest/classes/file1$package.class
out/compile.dest/classes/file2$package$.class
out/compile.dest/classes/file2$package.tasty
```

After incremental compilation with a blank `file1.scala`:

```
out/compile.dest/classes/
out/compile.dest/classes/file1$package.tasty
out/compile.dest/classes/file2$package.tasty
```

**Comment by lefou** [comment]
Also with scalac 3.3.3, tasty files don't get removed.

**Comment by lolgab** [comment]
Zinc has a setting `auxilaryClassFiles` which is set by Sbt to the tasty files so they are handled by Zinc:
https://github.com/sbt/sbt/blob/48c23761dc5ffe191a79424ba830dafcd2ec7631/main/src/main/scala/sbt/Defaults.scala#L963
I'm working on a PR to use it properly.

**Comment by lolgab** [comment]
The problem exists also for Scala Native with `*.nir` files and Scala.js with `*.sjsir` files.
My PR #3072 fixes them as well.
