### ISSUE TITLE
mill init does not work with Windows PowerShell in an enterprise environment

### ISSUE THREAD

**Issue by jarosmpost** [com-lihaoyi/mill#3089]
**Prompt**

```
PS C:\work\test> .\mill.bat -i init com-lihaoyi/mill-scala-hello.g8 --name=example
[build.sc] [49/53] compile
[info] compiling 1 Scala source to C:\work\test\out\mill-build\compile.dest\classes ...
[info] done compiling
[1/1] init > [1/1] mill.scalalib.giter8.Giter8Module.init | Downloading [2/2] artifacts (~0/0 bytes)
```

**Result**
Nothing is created.

**Environment**
mill version: 0.11.7
mirror.propertes points to our internal Artifactory, which works for the builds.

**Comment by jarosmpost** [comment]
@lefou : Do you need information to reproduce the bug?

**Comment by lefou** [comment]
What is `mill.bat`? Which version? Can you show the output when run with `--debug` option?

**Comment by jarosmpost** [comment]
`mill.bat` is a copy of `https://github.com/lefou/millw/blob/main/millw.bat` but with some changes for our environment.
With --debug it gives the same result:

> [1/1] init > [1/1] mill.scalalib.giter8.Giter8Module.init | Downloading [2/2] artifacts (~0/0 bytes)

The problem seems to be that I cannot load data from the Internet (`com-lihaoyi/mill-scala-hello.g8`), only from our internal  Artifactory. But it should at least return an error message.

**Comment by lefou** [comment]
So, this is likely an issue with the community-maintained contrib plugin [`mill-contrib-artifactory`](https://mill-build.com/mill/contrib/artifactory.html).

**Comment by jarosmpost** [comment]
In the latest version of Mill (0.12.1) I got a clear exception that the download of `org/foundweekends/giter8/giter8_2.13/0.14.0/giter8_2.13-0.14.0.pom` is not possible (was not whitelisted in our repository). With this exception I was able to solve the problem.

**Comment by lefou** [comment]
We reworked our input/output stream management and most likely fixed the swallowing of error messages that way. Thanks for your feedback.
