### ISSUE TITLE
Bumped Mill from 0.11.6 to 0.11.7 and my Jmh project doesn't accept arguments anymore

### ISSUE THREAD

**Issue by carlosedp** [com-lihaoyi/mill#3105]
Just bumped some deps and Mill from 0.11.6 to 0.11.7 and suddenly Jmh doesn't accept command line arguments (like `-rf json` to generate Json output).

https://github.com/carlosedp/zio-channel/actions/runs/8514471705/job/23320245671

```
❯ ./mill benchmarks.runJmh -h
[build.sc] [49/53] compile
[info] compiling 1 Scala source to /Users/cdepaula/repos/scala/zio-channel/out/mill-build/compile.dest/classes ...
[info] done compiling
[build.sc] [53/53] methodCodeHashSignatures
Unknown argument: "-h"
Expected Signature: runJmh
  args <str>...
```

Reverting to 0.11.6 this doesn't happen.

**Comment by carlosedp** [comment]
My bad, bumping to latest snapshot works (0.11.7-50-9a734a).

Closing this.

**Comment by lefou** [comment]
Duplicate of https://github.com/com-lihaoyi/mill/issues/3004
