### ISSUE TITLE
BSP: `MatchError` when a `TestModule` is used in isolation

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#3110]
> So I tried defining additional test without an real language module,  [this line in mill](https://github.com/com-lihaoyi/mill/blob/main/bsp/worker/src/mill/bsp/worker/MillBuildServer.scala#L215) will throw a MatchError as the additional test module does not inherent `JavaModule`.

_Originally posted by @chikei in https://github.com/com-lihaoyi/mill/issues/3064#issuecomment-2042031938_

**Comment by lefou** [comment]
In PR #3111 I think I fixed the `MatchError`, but haven't tested it, due to a missing test suite and spare time. @chikei If you want to give it a try, I'm happy to get your feedback.

**Comment by chikei** [comment]
Just tried IJ bsp import, I think the PR fixed the issue.
