### ISSUE TITLE
Support Scala native 0.5.0

### ISSUE THREAD

**Issue by thesamet** [com-lihaoyi/mill#3121]
When trying to upgrade utest to scala-native 0.5.0, I came across the following error:

```
1 targets failed
utest.native[2.13.10].resolvedIvyDeps
Resolution failed for 1 modules:
--------------------------------------------
  org.scala-native:scalalib_native0.5_2.13:0.5.0
	not found: /home/thesamet/.ivy2/local/org.scala-native/scalalib_native0.5_2.13/0.5.0/ivys/ivy.xml
	not found: https://repo1.maven.org/maven2/org/scala-native/scalalib_native0.5_2.13/0.5.0/scalalib_native0.5_2.13-0.5.0.pom
--------------------------------------------

For additional information on library dependencies, see the docs at
https://mill-build.com/mill/Library_Dependencies.html
```

It looks like the name patterns of the artifacts have changed, and there's an artifact for each version of scala:
https://repo1.maven.org/maven2/org/scala-native/scalalib_native0.5_2.13/2.13.9+0.5.0/

**Comment by lihaoyi** [comment]
The unstable version [0.11.7-29-f2e220](https://github.com/com-lihaoyi/mill/releases/download/0.11.7/0.11.7-29-f2e220) seems to have the necessary changes included. I'll try to use it to cut a utest release
