### ISSUE TITLE
url pattern need update

### ISSUE THREAD

**Issue by He-Pin** [com-lihaoyi/mill#3167]
1 targets failed
mill.idea.GenIdea.idea Failure during resolving modules: cssparse.native[3.3.3].resolvedIvyDeps
Resolution failed for 1 modules:
--------------------------------------------
  org.scala-native:scala3lib_native0.5_3:0.5.1
        not found: C:\Users\hepin\.ivy2\local\org.scala-native\scala3lib_native0.5_3\0.5.1\ivys\ivy.xml
        not found: https://repo1.maven.org/maven2/org/scala-native/scala3lib_native0.5_3/0.5.1/scala3lib_native0.5_3-0.5.1.pom

the url should be:

https://repo1.maven.org/maven2/org/scala-native/scala3lib_native0.5_3/3.3.3+0.5.1/scala3lib_native0.5_3-3.3.3+0.5.1.pom

**Comment by He-Pin** [comment]
![image](https://github.com/com-lihaoyi/mill/assets/501740/f7241cb1-3eea-4fdd-9680-19d8156ac17f)

**Comment by He-Pin** [comment]
@lefou Hi, is there any plan to have this fixed in 0.11.8:), I want to do some contribution in fastparse, but this seems a blocker to me, I have to comments out the native module.

**Comment by lefou** [comment]
I think so. It should be already fixed in `main` and the last snapshot releases. We could also cut a new release, but I probably won't find the time to do it in the next days.

**Comment by He-Pin** [comment]
Thanks @lefou , no hurry.
