### ISSUE TITLE
Add support in import IDEA scala plugin?

### ISSUE THREAD

**Issue by He-Pin** [com-lihaoyi/mill#3186]
Motivation:

Currently, when import projects using mill, have to invoke the `mill mill.idea.GenIdea/idea` and `build.sc` lack of highligthing in IDEA too.
It would be nice to support it directly just as `sbt`.

Expection:
Works smoothly as sbt in IDEA.

**Comment by lefou** [comment]
I think the correct project for this feature requets is https://github.com/JetBrains/intellij-scala
