### ISSUE TITLE
Windows CI seems to be broken on newer versions of Mill (500USD)

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#3283]
---

**From the maintainer Li Haoyi**: I'm putting a 500USD bounty on this issue, payable by bank transfer on a merged PR implementing this.

---

Ever since https://github.com/com-lihaoyi/mill/commit/126f57476ff9b7ab3f797e41e8880ace81b85362, the various Windows CI jobs seem to be finishing in ~1min, rather than the 10-30min they used to. Something's probably wrong and they're not actually testing anything. We should figure out what, fix it, and ensure Windows CI is able to pass on the current latest version of Mill built from HEAD

**Comment by lefou** [comment]
This PR only fixed the Windows batch script but doesn't raise the Mill version, yet it shows the same test failure:

* https://github.com/com-lihaoyi/mill/pull/3284 

We should compare the two binary sources Github releases and Maven Central as well as the batch script `mill.bat` which is a copy of https://github.com/lefou/millw.

**Comment by lefou** [comment]
* [ ] #3290

**Comment by sake92** [comment]
@lihaoyi thanks! I've sent you an email.
