### ISSUE TITLE
The `run` command for ScalaJSModule does not pass along the provided args

### ISSUE THREAD

**Issue by DamianReeves** [com-lihaoyi/mill#3324]
The `run` command for ScalaJSModule does not pass along the provided args.

The issue seems that we should be passing `args` to the `jsEnvConfig`. 
```scala
  override def run(args: String*) = T.command {
    finalMainClassOpt() match {
      case Left(err) => Result.Failure(err)
      case Right(_) =>
        ScalaJSWorkerExternalModule.scalaJSWorker().run(
          scalaJSToolsClasspath().map(_.path),
          jsEnvConfig(),
          fastLinkJS()
        )
        Result.Success(())
    }

  }
```

**Comment by lefou** [comment]
The `args` argument is ignored, which is wrong and needs to be fixed.

From looking at the code, I can see that every known instance of `JsEnvConfig` has an `args` parameter, but it looks like it's used to pre-configure some environment specific arguments.

IMHO, the best solution would be to just add a new `args` parameter to the various `run` methods in the worker. It needs some API additions but could be done in a binary compatible way. We could also add it to the `JsEnvConfig` arguemnt directly, but this would also require either some API additions or some (redundant) pattern matching, and it just feels wrong.

@lolgab WDYT?

**Comment by lolgab** [comment]
This is not supported by Scala.js itself, so cannot be fixed by mill.
The workaround is to create a custom task and call `node` yourself.

**Comment by lefou** [comment]
We should use `T.log.error` with exactly that message when `args` is non-empty.

**Comment by DamianReeves** [comment]
It would be nice if we had tool support for calling `node` similar to what we have with the `Jvm` utils
