### ISSUE TITLE
Add Java Checkstyle Plugin (1000USD Bounty)

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#3332]
---

**From the maintainer Li Haoyi**: I'm putting a 1000USD bounty on this issue, payable by bank transfer on a merged PR implementing this.

---

Checkstyle is a common Java linter, and we should support it as a `contrib/` module to better support Java projects. We should support all common configuration options, and provide it as an `CheckstyleModule` to allow usage on `JavaModule`s and `ScalaModule`s (which can contain Java sources). This needs to come with a reasonable set of unit tests, docs, and at least one example test that can be included in the documentation

Can possibly be adapted from https://github.com/etsy/sbt-checkstyle-plugin

**Comment by brbrown25** [comment]
I’m going to try and look at this one this week

**Comment by ajaychandran** [comment]
@lihaoyi 
A usecase like a CI build would require the build to fail if Checkstyle errors were found.
I will add a task that checks the error count. Is there a naming convention for such tasks?
