### ISSUE TITLE
Add Java Jacoco Plugin

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#3333]
Jacoco is the most common Java Code Coverage Reporter, and we should support it to better support Java projects

Can probably be adapted from https://github.com/sbt/sbt-jacoco

**Comment by lefou** [comment]
This already exists: https://mill-build.com/mill/Thirdparty_Plugins.html#_jacoco_code_coverage

**Comment by lihaoyi** [comment]
Ah thanks for the pointer, didn't notice that one
