### ISSUE TITLE
[RFC] Rename `T{...}` and `T[_]` to `task{...}` and `Task[_]`, standardize "Task"/"Target" terminology around "Task"

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#3338]
`T{...}` and `T[_]` syntaxes are kind of weird. They are concise, but I don't think the conciseness they bring pays for the weirdness. And the weirdness does get noticed, e.g. [recently on Reddit](https://www.reddit.com/r/programming/comments/1ea400h/comment/lekoohw/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button). I notice it too. Part of the reason it's there is that `Target[_]` and `Target{...}` is too verbose, but maybe that's fixable

This proposal would be to leave the `T` aliases in place but deprecated, add a new `task` alias for the expressions:

* `T{...}` -> `task{...}`
* `T.command{...}` -> `task.command{...}`
* `T.task{...}` -> `task.anon{...}`
* `T.dest` -> `task.dest`, ...)
* `T[_]` -> `Task[_]` 

`Task[_]` and `task{...}` are maybe short enough (compared to `Target`) that we can do without the `T` alias

This would make the codebase a lot more approachable for folks not used to weird Scala DSLs

There's some messiness around how the `Task`/`Target` hierarchy is arranged right now that may require a breaking change to make this work well.e.g. `Target` may need to become `Task`, if we want to use the `Task` terminology everywhere instead of `T`. But then `Task` would need to be renamed to avoid confusion (`BaseTask`?). This would basically be cleaning up some of the messiness that we failed to totally resolve earlier in https://github.com/com-lihaoyi/mill/pull/2402, as the status quo today the terminology of whether we should call things *tasks* or *targets* is still a bit muddled.

e.g. we may need to go from today's:

- `Task`
    - `Task.Sequence`, `Task.TraverseCtx`, `Task.Mapped`, `Task.Zipped`, `T.task`, etc.
    - `NamedTask`
        - `Command`
        - `Worker`
        - `Target`
            -  `TargetImpl`
                - `PersistentImpl`
            - `InputImpl`
                - `SourceImpl`
                - `SourcesImpl`

To something like

- `BaseTask`
    - `Task.Sequence`, `Task.TraverseCtx`, `Task.Mapped`, `Task.Zipped`, `T.task`, etc.
    - `NamedBaseTask`
        - `Command`
        - `Worker`
        - `Task`
            -  `TargetImpl`
                - `PersistentImpl`
            - `InputImpl`
                - `SourceImpl`
                - `SourcesImpl`

That would allow us to consistently use the term `Task` everywhere, with `BaseTask` and `NamedBaseTask` being niche interfaces that are mostly interesting only for advanced users.

**Comment by lefou** [comment]
There is a high change to produce collisions hard to resolve in older external code bases or projects. 

E.g. 

> * `T[_]` -> `Task[_]`

is ambiguous, since today we already have a `Task` type.

I'm also not so sure whether `task.command{...}` is better than `Task.command{...}`. For the lower-case version I would expect it being a inherited `def`, maybe inside `Module`. But anonymous tasks can also be defined outside of `Module`. The upper-case version is easier to comprehend, since I just need to find `Task` and inspect it.

**Comment by Ichoran** [comment]
I would tend to just leave it alone.  `Target` is only six characters; any argument you have going from one character to four will apply even better going from four to six.  The only reason to change it would be if `Target` really ought to always have been called `Task`.

**Comment by lefou** [comment]
That's a good point. `Target{..}` or `Target.command{..}` isn't that worse than `Task{..}`.

And since `T` is just an alias to `Target`, users can already write `Target{..}` instead of `T{..}`.

**Comment by lihaoyi** [comment]
I'd like to push on this just a bit more: It's not just that one random guy on r/java, folks on r/scala have called Mill [alien](https://www.reddit.com/r/scala/comments/1ejmbt3/comment/lgkpjki/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) and [cryptic](https://www.reddit.com/r/scala/comments/1ejmbt3/comment/lghw4tt/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) as well. Obviously as maintainers we do not feel the same since we are 100% comfortable with living and breathing Mill, but I'd like to consider if we can do better.

What is cryptic or alien about Mill code for Scala developers? Although Mill looks mostly like normal Scala code - method calls, blocks, etc. - I can list a few things:

1. `Agg` rather than `Seq`. This is already something I brought up in the other thread https://github.com/com-lihaoyi/mill/discussions/3209, and I plan to remove in 0.13.0 (we can leave aliases `type Agg[+T] = Seq[T]; val Agg = Seq` for source compatibility)

2. `T { ... }` and `T.foo`. Sure there is precedence: Lift used `S.foo`, FastParse uses `P` and `P.foo`. But Lift and FastParse are very much on the more-cryptic/alien part of the Scala style spectrum. Some Java code also uses single-letter variables for convenience (e.g. I've seen `Foo.v()` to reference to `Foo`'s singleton), but I'd argue that while that exists it's also on the more-cryptic side of the Java coding style.

3. Having to juggle `def foo(x: ???) = T.task { ... }`s: calling them with `foo(???)()` or operating on them with various combinators `T.sequence(...)()`, `T.traverse(...)()`, etc.. Not super cryptic for Scala folks used to juggling monads, but definitely cryptic for anyone coming from Java. We'll never get rid of this completely because sometimes you do need to operate on the task graph, but I hope to relegate this to mostly advanced use cases, and have been trying to get them out of "common" use cases like in https://github.com/com-lihaoyi/mill/pull/3330

Other than these things listed above, Mill code looks exactly like vanilla Scala code: function calls taking blocks, calling methods with `()`, etc.. (1) and (3) are already being addressed, and IMO it would be great if we could address (2). `T { ... }` thing isn't the end of the world, but IMO it would be _really_ nice if people could write `def foo = task { ... }`. Especially for folks coming to Mill for the first time, `def foo = task { ... }` would be immediately familiar with people coming from other build tools (e.g. Gradle's `task.named("foo"){ ...}`, Rake's `task :foo do ... end`).

----

In most of the docs, we use the term `task`s. Sure there is some subtlety around `task` vs `target`, and `task` vs `input` and so on, but it would be very nice if the most common term people see in the docs `task` is also what people see in their code: `def foo = task { ... }`. We _could_ tell people to use `def foo = Target { ... }`, but I think that adds some confusion that should be mostly avoidable. e.g. my experience with Bazel, which has both `Target`s and `Action`s, is that this adds considerable confusion. 

This whole `T` alias is a bit of a wart semantically, even ignoring the syntax and spelling. `T` stands for `Target`, but you also use it to spawn `T.command`s and `T.worker`s which are not targets, and access `T.dest` which isn't unique to targets. Semantically `T` should really stand for `Task`, with `T { ... }` or `Task { ... }` being a factory `apply` method that constructs the default type `Target`, but whose other factory methods construct other subtypes like `Command` or `Worker`. The only reason `T` looks reasonable today is because it is ambiguous whether it is short for `Task` or `Target`, but if we started spelling out `Target.command` or `Target.dest` that becomes totally nonsensical given the class hierarchy.

As of now, `Task` as an abstraction is mostly used inside Mill internals, while `Target` is used in user-facing code, but `task` is used in most of the documentation because it makes a lot more sense to a newcomer (e.g. every build tool has tasks, only Bazel has targets) and for many user-facing purposes non-target tasks are treated the same as target tasks. 

I don't think I have a full solution to propose here yet. But I'd like to discuss this and see if this can go anywhere.

**Comment by lefou** [comment]
I agree, that mentally `T` stands for `Task`. I really wish all those `apply`-like methods would be defined in `Task` and not `Target`, so I'm in the same boat already. It's then up to some user preference to use `Task.command` or `T.command`, and I'm comfortable with using the longer version if that helps co-workers.

I also see all those Mill projects and plugins in the wild and really fear a rough migration path paired with frustration. Since we run the normal Scala compiler, pure compiler error messages is what our users face once they hit a changed API. We need to make that experience smooth. I've seen abandoned older Mill plugin projects on GitHub and trying to get them to work in newer Mill versions was rather frustrating, even for me how really knows the Mill API. Once you have an old `build.sc` you sometimes even don't known which Mill version was supposed to properly handle it, so we should limit the guess game to a minimum.

Improving for new users is great, but we should not leave existing users behind.

**Comment by lefou** [comment]
What always bugged me it the fact that a `T` produces a `T` but a `T.worker` produces a `Worker`. From a consistency standpoint, we want to produce either a `T.worker` or we want to rename the factory to `Worker`. (At least in documentation or in chats, whenever I said "you need a `T.command`", I thought, damn, that's not the type she wants.)

So, wouldn't it make sense to move some types like `Worker` and `PersistentImpl` into the `T` (or `Task` or whatever we come up with) comanion. 

```scala
def worker: Task.Worker[Work] = Task.Worker { .. }
def persistent: Task[String] = Task { .. }
def anon: Task.Amon[String] = Task.Anon { .. }
```

We could also make it lower case, but it would be alien to have lower case class names, wouldn't it?

```scala
def worker: Task.worker[Work] = Task.worker { .. }
def persistent: Task[String] = Task { .. }
def anon: Task.amon[String] = Task.anon { .. }
```

**Comment by lihaoyi** [comment]
For migration, there are things we can do since this is such a core API. e.g. 

1. A longer deprecation cycle: 1 big release without warnings, 1 release turning on warnings, before removal. If we do one big release every year, that gives people 3 years to update

2. We can `@compileTimeOnly` the removed APIs before full removal. That would give people a good error message when the APIs stop working, so they don't just hit a brick wall.

3. Given how core these APIs are, I would be honestly fine leaving them deprecated forever. Doesn't cost us much, but allows backwards compat forever

Migration is definitely a concern, especially for such core APIs, but I think we can do something reasonable to address it

**Comment by lefou** [comment]
The existing `T.command` / `Command[R]` always played a special role, since it's some factory for tasks, based on their parameters. Its "constructor" accepts a task and mentally, it's more some wrapping around a task with some user convenience. To re-use or override a command programmatically, special precautions need to be taken, e.g. making all argument itself tasks. To support CLI parsing, special `@mainargs` annotations and limitations need to be considered. Binary-compatible evolution and overloads are hard or impossible.

So here is my question. Can we simplify it's design or make it more principled? Since it's at it's core two components, an anonymous task and a CLI module wrapping it, maybe we should make it either two `def`s or a class?

**Comment by lihaoyi** [comment]
Took another pass at this at https://github.com/com-lihaoyi/mill/pull/3356. I think I'm pretty happy with the result. It does make some tradeoffs, but I think the improvement in user experience is worth it. 

For `T.command`s, I think there is something we can do there, but it would require more involved work. 

1. Splitting it into a task/entrypoint pair is possible, but would add a lot of boilerplate to the definition sites
2. Another possibility would be to use a compiler plugin or annotation macro to automatically wrap the arguments in `Task[_]`s and automatically wrap the use sites in `()`. I think this could work and be really nice to use.

I think (2) could work and be a pretty seamless experience. Worth exploring

**Comment by lihaoyi** [comment]
Calling this done; half done in 0.12.0 standardizing on `Task` for factories and helpers, and the term "task" over "target. We can follow up with the type-hierarchy re-organization in https://github.com/com-lihaoyi/mill/pull/3356
