### ISSUE TITLE
Documentation for `0.11.10` not found

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#3342]
Selecting other versions work, but when I select `0.11.10`, I get a `Page Not Found`.

![image](https://github.com/user-attachments/assets/cd925e2f-31ad-446a-b2b9-8c3bb1f4a069)

**Comment by lihaoyi** [comment]
Strangely it seems to work for every page except the landing page

**Comment by lefou** [comment]
This is not an issue for `0.11.11` and `0.11.12`. We could just remove documentation for `0.10.10`.

**Comment by lefou** [comment]
Could be that the intro page `Java_Intro_to_Mill` does not exists in `0.11.10` since it was only added in `0.11.11`. But switching over to `0.10.x` works too, although the intro page is named differently. So, I assume an issue with this concrete version, which could be fixed in a branch, but probably not worth it.

**Comment by lihaoyi** [comment]
This has been fixed since 0.11.13 was released
