### ISSUE TITLE
Warning: @deprecated("Use JavaTests instead", since = "Mill 0.11.10")

### ISSUE THREAD

**Issue by james-s-w-clark** [com-lihaoyi/mill#3371]
I just upgraded to mill 0.11.11, and see a warning for `trait JavaModuleTests in trait JavaModule is deprecated` even though our project isn't using that deprecated trait (`JavaModuleTests`).

I also saw this warning in a recent issue (https://github.com/com-lihaoyi/mill/issues/3359#issuecomment-2282284235), so I figured the warning may come from mill itself. 

I think it's coming from the first line here:
```
  type JavaTests = JavaModuleTests
  @deprecated("Use JavaTests instead", since = "Mill 0.11.10")
  trait JavaModuleTests extends JavaModule with TestModule {
```
https://github.com/com-lihaoyi/mill/blob/main/scalalib/src/mill/scalalib/JavaModule.scala#L39-L41

It can be reproduced on `main` with e.g. `./mill -i dev.run anything`, even if you update all `JavaModuleTests ` to `JavaTests`.

I had a try with some @nowarns on the non-deprecated type in the repo, and removing references to the deprecated JavaModuleTests, but didn't manage to fix it. It looks like it could help though (quick check in Scastie), but no luck trying it in the actual repo:

![image](https://github.com/user-attachments/assets/7e3d1369-bf6a-4164-9b3d-32bf39b2fa11)

![image](https://github.com/user-attachments/assets/23f01197-f126-4874-b9fc-b2eedefcf591)

(Tangent: somehow our -Xfatal-warnings aren't triggered by the warning, so that's good - but we might just have something misconfigured :sweat_smile: )

**Comment by tculshaw** [comment]
Same here. I reverted to 0.11.9 for now.
