### ISSUE TITLE
Link to the bootstrap script doesn't exist

### ISSUE THREAD

**Issue by asarkar** [com-lihaoyi/mill#3384]
```
curl -L https://github.com/com-lihaoyi/mill/releases/download/0.12.0-M0/0.12.0-M0 > mill && chmod +x mill
echo 0.12.0-M0 > .mill-version
```

https://mill-build.org/mill/Scala_Installation_IDE_Support.html#_bootstrap_scripts

The link to the bootstrap script doesn't exist. This is because there's no release `0.12.0-M0`, only a tag.

**Comment by lihaoyi** [comment]
Should be fixed by https://github.com/com-lihaoyi/mill/commit/0e9b7cd0b952e89cd619636a6f16657202a2eed4 I think, should go live on the website in the next hour or so

**Comment by lihaoyi** [comment]
Thanks for the report!
