### ISSUE TITLE
`package.mill` support should require explicitly enablement

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#3409]
Currently, Mill is always scanning for `module.sc` files. We already discussed and agreed on the enablement of sub-modules through `module.sc` files via an `$`-import in PR https://github.com/com-lihaoyi/mill/pull/3213. 

What could be a good name for the import? One of the candidates was `submodules`:

```scala
import $submodules._
```

**Comment by lihaoyi** [comment]
`import $submodules._` works for me. Eventually we may have some other way of passing flags, but for now this will do
