### ISSUE TITLE
Support ErrorProne for Java (1000USD Bounty)

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#3447]
---

**From the maintainer Li Haoyi**: I'm putting a 1000USD bounty on this issue, payable by bank transfer on a merged PR implementing this.

---

ErrorProne is a common Java linter, and we should support it as a `contrib/` module to better support Java projects. We should support all common configuration options, and provide it as an `ErrorProneModule` to allow usage on `JavaModule`s and `ScalaModule`s (which can contain Java sources). This needs to come with a reasonable set of unit tests, docs, and at least one example test that can be included in the documentation

May be able to adapt something from https://github.com/google/error-prone/issues/291

**Comment by lefou** [comment]
Implemented in https://github.com/com-lihaoyi/mill/pull/3460
