### ISSUE TITLE
Support `mill init` from an existing Maven project (1500USD Bounty)

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#3449]
---

**From the maintainer Li Haoyi**: I'm putting a 1500USD bounty on this issue, payable by bank transfer on a merged PR implementing this.

---

We should be able to run `./mill init` to do a best effort conversion of an existing Maven project to Mill: 

* Code-generate a `build.mill` containing a `MavenModule`for the root `pom.xml`, the `package.mill` for any subfolder `pom.xml`s
* Convert the main and test dependencies on third-party libraries to `ivyDeps`
* Convert inter-subproject dependencies to `moduleDeps`
* Set any necessary `javacOptions`
* Implement `PublishModule` with relevant metadata
* Support POM inheritance, dependency management, etc.

Such a conversion will never be 100%, but if we can automate 80% of the conversion that will already be a huge help for people migrating to Mill or even just trying it out

Some prior art that can be used as reference:

* Gradle's Maven Importer https://docs.gradle.org/current/userguide/build_init_plugin.html#sec:pom_maven_conversion
* SBT's POM Reader Plugin https://github.com/sbt/sbt-pom-reader

**Comment by arturaz** [comment]
Is there any infrastructure for this already? For example, does `mill init` entry point exists?

**Comment by lihaoyi** [comment]
@arturaz `mill init` already exists, and uses giter8 to initialize a repo based on some github URL:

https://github.com/com-lihaoyi/mill/blob/7732b0fa1588d7e6b4dd70a5016458ac193fa222/main/src/mill/main/MainModule.scala#L403

It should be pretty easy to add logic to check if there's an existing `pom.xml` in the project root and initialize based on that instead

**Comment by arturaz** [comment]
I'll try to implement this :)

**Comment by lihaoyi** [comment]
@arturaz go for it!

**Comment by llvee** [comment]
@arturaz Is this completed? If not do you mind if I give this a try 24 hours from now?

**Comment by arturaz** [comment]
I am working on it right now. Could you give me a couple of days? 🙂






---- On Mon, 23 Sep 2024 03:29:37 +0300 ***@***.*** wrote ----



@arturaz Is this completed? If not do you mind if I give this a try 24 hours from now?

**Comment by llvee** [comment]
@arturaz Would you like some help with completing it?

**Comment by arturaz** [comment]
> @arturaz Would you like some help with completing it?

I'm not sure how that'd work, at least right now, but I will keep that in mind!

**Comment by llvee** [comment]
@arturaz Bounty percentages seem like a reasonable option if you're interested in receiving help & sharing some bounty percentage.

**Comment by ajaychandran** [comment]
@lihaoyi 
Would it be okay if `mill.init` package depended on `mill.scalalib`?

This allows for patterns like
```scala

  // Build DSL

  // usage: extends[mill.Module]
  def `extends`[T](implicit T: ClassTag[T]): Build =
    `extends`(T.runtimeClass.getCanonicalName)

  // usage: extends("mill.Module")
  def `extends`(supertype: String): Build =
    ???
```
