### ISSUE TITLE
First Party Support for the Kotlin language (2000USD)

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#3451]
---

**From the maintainer Li Haoyi**: I'm putting a 2000USD bounty on this issue, payable by bank transfer on a merged PR implementing this.

---

https://github.com/lefou/mill-kotlin/ exists, but it is a standalone project without many examples, and not enough for a newbie to pick up and begin using Mill with Kotlin. This ticket is to do the following:

1. In-source https://github.com/lefou/mill-kotlin/ into the Mill repo as a `kotlinlib` submodule
2. Write Kotlin versions of the `example/javalib/{basic,builds,module,testing}` example integration tests, where reasonable
3. Flesh out whatever missing functionality is needed to do the above (I'm sure we'll hit things!)

As this ticket is large, I am splitting the bounty into two parts:

1. 1000USD to get the `mill-kotlin` in-sourced and the `example/javalib/basic` examples converted to Kotlin and included on the docsite
2. 1000USD to get the remaining examples in  `example/javalib/{builds,module,testing,publishing}` converted to Kotlin and included on the docsite

The end result is that we have a suite of tested example documentation demonstrating how to use the Mill build tool to build a large variety of Kotlin projects mirroring the example documentation for Java and Scala projects.

Some code may be adaptable from https://github.com/rife2/bld-kotlin. ChatGPT (or claude or whatever) would probably also be a great help translating the examples; I used it heavily when setting up the Java example tests, but in the end the human still needs to debug things and polish it up so it's presentable for pedagogical purposes

**Comment by githubbin765** [comment]
If I claim this, can others also claim or start work on the bounty?

**Comment by lihaoyi** [comment]
@githubbin765 As mentioned in https://github.com/orgs/com-lihaoyi/discussions/5, bounties remain open until completed. 

In this case I (just) broke up the bounty into two phases so it's not such a big all-or-nothing ticket, and I can break it up further if you think it would be useful. 

But fundamentally there is no locking of bounties, so others can pick it up as well, and first PR wins (at my discretion)

**Comment by githubbin765** [comment]
Have you considered changing this to where developers can claim the bounty since non claiming potentially means multiple people working on bounties without any guaranteed compensation?

**Comment by lihaoyi** [comment]
I have. It's ultimately a tradeoff. Multiple people
racing on each bounty has not been a problem so far, but i understand it may change as the scope of the biunty grows. Maybe I'll try a locking policy next round

**Comment by githubbin765** [comment]
I see, that makes sense. Changing the bounty rules based on specific participation seems like a good idea potentially.  Ok I seem to have identified how to in-source the library may be able to complete translating remaining examples today for the first part of this. I will create two separate PRs one for the in-sourcing, another for examples.

**Comment by lihaoyi** [comment]
@githubbin765 sounds good! looking forward

**Comment by lihaoyi** [comment]
I would suggest doing everything in (1) above in one PR: both the insourced library and the translated `example/javalib/basic`. Easier to review together with the example tests validating that the insourcing works

**Comment by lihaoyi** [comment]
no preference, in the wnd we squash everything down anyway

**Comment by githubbin765** [comment]
@lihaoyi True. I will follow the existing branching patterns.

**Comment by githubbin765** [comment]
Today hasn't been that productive. 

It started later than I would have liked. 

I would like to complete this quickly, be as helpful as I can be initially. 

If I don't submit a PR in the next six hours then I will aim to submit a PR in the next 24 hours.

**Comment by lihaoyi** [comment]
Take your time. As i said in the announcement, these bounties are bigger because i expect them to be a lot owf work, especially for someone new to the codebase.

**Comment by githubbin765** [comment]
Ok I haven´t forgotten about this. I did need to work on local configuration before continuing for best results.

**Comment by githubbin765** [comment]
# Introduction to Using Mill with Kotlin
Mill is a modern build tool for Scala and Java, but it also provides support for Kotlin projects. This guide will walk you through setting up and using Mill to create and manage Kotlin projects effectively.

# Getting Started
Mill is designed to be a simple and efficient build tool. For Kotlin projects, Mill offers a straightforward way to manage dependencies, build configurations, and test setups. Below are the steps to create and manage a Kotlin project using Mill.

## 1. Install Mill
First, you need to install Mill. You can download it from the official Mill website or use Homebrew on macOS:

```
sh
Copy code
brew install mill
Alternatively, download Mill manually:
```

```
sh
Copy code
curl -L -o mill https://github.com/com-lihaoyi/mill/releases/download/0.11.12/0.11.12
chmod +x mill
```

## 2. Create a New Kotlin Project
Create a new directory for your Kotlin project and navigate into it:

```
sh
Copy code
mkdir my-kotlin-project
cd my-kotlin-project
Initialize a basic Mill project structure:
```
```
sh
Copy code
mill init
```

## 3. Configure Mill for Kotlin
To use Kotlin with Mill, you need to configure your project to include Kotlin dependencies and plugins. Create or edit the build.sc file in the root of your project with the following content:

```
scala
Copy code
import mill._, mill.scalalib._
import mill.define.Cross
import mill.scalalib.ScalaModule

object myKotlinProject extends ScalaModule {
  def scalaVersion = "2.13.8" // Adjust this version as needed

  object test extends Tests {
    def ivyDeps = Agg(
      ivy"org.jetbrains.kotlin:kotlin-test-junit:1.6.21" // Kotlin testing dependency
    )
  }

  // Apply Kotlin plugin and configure dependencies
  override def millSourcePath = millSourcePath / 'src / 'main
  override def compile = super.compile
}

object myKotlinTests extends ScalaModule {
  def scalaVersion = "2.13.8" // Adjust this version as needed

  object test extends Tests {
    def ivyDeps = Agg(
      ivy"org.jetbrains.kotlin:kotlin-test-junit:1.6.21" // Kotlin testing dependency
    )
  }

  // Apply Kotlin plugin and configure dependencies
  override def millSourcePath = millSourcePath / 'src / 'test
}
```

## 4. Add Kotlin Source Files
Create directories for your source files and tests:

```
sh
Copy code
mkdir -p src/main/kotlin
mkdir -p src/test/kotlin
Add your Kotlin source files to src/main/kotlin and your test files to src/test/kotlin.
```

## 5. Build Your Kotlin Project
To compile your Kotlin project, use the following Mill command:

```
sh
Copy code
mill myKotlinProject.compile
```

##6. Run Tests
To run the tests in your Kotlin project, use:

```
sh
Copy code
mill myKotlinTests.test
```

## 7. Example File Structure
Your project directory should be structured like this:

```
bash
Copy code
my-kotlin-project/
├── build.sc
├── mill
├── src/
│   ├── main/
│   │   └── kotlin/
│   │       └── (your Kotlin source files)
│   └── test/
│       └── kotlin/
│           └── (your Kotlin test files)
```

## 8. Additional Configuration
Mill supports advanced configurations and customizations. You can define additional modules, set up multi-project builds, and integrate with other tools. For more advanced use cases, refer to the Mill documentation for further details.

#### Summary
Using Mill with Kotlin involves installing Mill, configuring your project with Kotlin dependencies, adding Kotlin source and test files, and running build and test commands. Mill's simplicity and efficiency make it a great choice for managing Kotlin projects.

For more information and detailed documentation on Mill, visit the Mill documentation website.

This guide should help you get started with Kotlin projects using Mill, highlighting the necessary setup and commands. Adjust the configuration according to your project's specific needs and dependencies.

**Comment by githubbin765** [comment]
Apologies for the delay, working on local configuration has been taking longer than desired. I have shared some progress above. Is this to your liking?

**Comment by lihaoyi** [comment]
Why are you giving me chatgpt output?

**Comment by githubbin765** [comment]
The above isn't ChatGPT output. You also suggested using ChatGPT in the first post in order to help resolve this bounty.  I shared the above because you stated wanting  the example/javalib/basic examples converted to Kotlin and included on the docsite so I created a docsite format using Markdown. For the docsite, does the above look ok to you?

**Comment by lihaoyi** [comment]
@githubbin765 I don't think the output you gave above is relevant to the bounty at hand. I'm going to clean up the thread to make space for any further discussion that may occur. Feel free to open a PR when you have the working examples and we can take it from there

**Comment by githubbin765** [comment]
@lihaoyi I see. I will do that.  I will open a second PR for the second bounty with the doc site code.

**Comment by 0xnm** [comment]
@lihaoyi I may look into Part 2 as well. Do you have any ideas/suggestions about Kotlin libraries/frameworks you would like to see there?

**Comment by lihaoyi** [comment]
@0xnm most of the rest of the `kotlinlib/` examples are roughly mechanical translations of the `javalib/` examples re-arranging the stuff you already have in `kotlinlib/basic/`, but there are a few things that are worth calling out. Let me go through the folders below:

* `kotlinlib/builds/` should be pretty mechanical and not require anything new. It's mostly just a few different re-arrangements of the `basic/` examples

* `kotlinlib/module/` should be mostly mechanical as well, except `compilation-execution-flags` should include some example showing off Kotlin compiler flags (I assume they have some?) and `6-annotation-processors` should be replaced by some example showing a kotlin compiler plugin

* `kotlinlib/publishing/` is just one example and should be a mechanical conversion.

* `kotlinlib/testing/` should be mostly mechanical re-arrangements of stuff you already have in the test suite of the `basic/` examples

* `kotlinlib/linting/` has a lot more flexibility in what we want to put in there. Let's have an example using an autoformatter (maybe https://github.com/facebook/ktfmt ?) and some linter (maybe https://github.com/pinterest/ktlint ?)

* `kotlinlib/web/` is also similarly flexible; maybe a hello world and todomvc example using https://github.com/ktorio/ktor ? There are a few examples online like https://github.com/jamowei/fritz2-ktor-todomvc that we may be able to adapt like I did for the Java micronaut/springboot todomvc examples in `javalib/web/`. A Kotlin-JS example would also certainly be nice, but I'd call that a nice to have and not really core

**Comment by lihaoyi** [comment]
TBH the list of stuff above seems like a lot. I'd be ok if you skipped the `web/` folder and did all the other stuff. We can pick up the web stuff later in a separate ticket

**Comment by llvee** [comment]
Are both of the above complete? If so is there anyway for someone like myself to verify that bounties are being paid upon completion of issues? 

What is the biggest pressing need with the codebase? Is it a bounty task? I also noticed there is no clear avenue for creating documentation which was asked for in the task description, when I created, shared a version of the documentation specficially for Kotlion you mentioned not understanding that, removed it. Why was that? 

Regarding the above if I have solutions for the missing parts in the other commits, can I be rewarded with a partial bounty for those?

**Comment by lefou** [comment]
I think the compile plugin stuff is essential. Showcasing usage of `kotlinx.serialization` might be a good candidate.

**Comment by llvee** [comment]
@lefou 
Is that wanted in the documentation? 

Anyone else notice that the GH Issues UI creates text overflow when resizing browser windows?

**Comment by lihaoyi** [comment]
@llvee Please open a PR if you have one that satisfies the bounty requirements, otherwise there isnt that much to continue discussing here
