### ISSUE TITLE
Integrate `./mill init` with the example projects (500USD Bounty)

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#3548]
---

**From the maintainer Li Haoyi**: I'm putting a 500USD bounty on this issue, payable by bank transfer on a merged PR implementing this.

---

Mill's `example/` folder projects are all zipped up and published for download with every release, and form a far more comprehensive and richly documented set of project templates than is available on giter8. We should update `./mill init` to prioritize using these examples as getting started templates for users using `./mill init`. We can continue to support giter8 if we want, but I expect the built in example templates will be what people want 99% of the time and render external giter8 templates largely unnecessary.

Success criteria:

* When you run `./mill init` without any argument, it shows the user a list of all the Mill `example/` projects, grouped and organized in some meaningful way
* The user can then select one of those example projects (e.g. by typing in its number in the list, or its path e.g. `javalib/basic/1-simple`) and Mill will download the project from the Mill Releases page and unpack it into the local directory
* The user can also pass in the path of the example as an argument, and as long as it matches one of the accepted example paths, Mill will download and unpack the example zip rather than use giter8

The list of valid examples can vary between Mill versions, and should be computed at build time as a resource generator and bundled together with Mill during creation of its `dist.assembly`.

**Comment by pawelsadlo** [comment]
does it need to run interactively, prompting example number just like init is working now?
or its ok to ask user to run `./mill init [number or path of example]`

**Comment by lihaoyi** [comment]
@pawelsadlo no need interactivly for now, AFAIK `mill init` today is non interactive:

```bash
$ ./mill init
Creating a new project...
Error: Missing argument <template>
Try --help for more information.
```

I think it would be fine just to print out a big list of potential templates and then ask the user to copy paste the one they want for now. Once all the example templates are all wired up and in place, we can separately look at tweaking the CLI experience

**Comment by pawelsadlo** [comment]
Ah right , the g8 template generation is interactive, not the init command. 
Anyway can mill command even be interactive without running creating a subprocess?

**Comment by lihaoyi** [comment]
`./mill -i` does allow interactive stuff, like `console`. Even without a subprocess you can do the same thing and read/write from stdin/stdout

**Comment by lefou** [comment]
For the purpose of copy-and-paste in tutorials and readmes, it would be nice with `mill init` can be used non-interactively.

**Comment by llvee** [comment]
@pawelsadlo 
Did you complete this? If not maybe I will attempt this in 24 hours from now.

**Comment by pawelsadlo** [comment]
@llvee 
it's done ,I'm just adding some tests

**Comment by llvee** [comment]
@pawelsadlo let me know if you'd like some help with test writing.

**Comment by lefou** [comment]
I think accepting a `--mill-version` option to choose the version from which we take the examples from might be a good idea. This can be helpful in cases where the Mill version isn't exactly the one providing the wanted examples.
