### ISSUE TITLE
BSP Support for Kotlin modules

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#3606]
Splitting this out of https://github.com/com-lihaoyi/mill/issues/3397

We now support `kotlinlib` built in to Mill, so we should support Kotlin modules via IntelliJ BSP as well. AFAIK the Kotlin community is mostly on IntelliJ, so we don't need to worry about VSCode for now. And since `kotlinlib` is now bundled with Mill, we don't need to worry about making the BSP server extendable (https://github.com/com-lihaoyi/mill/issues/2598), and can just hard-code support for `KotlinModule` for now

I'm not sure what exactly will need to be done to make Mill/BSP/IntelliJ/Kotlin work. It seems we have `MillJavaBuildServer.scala` and `MillScalaBuildServer.scala`, so likely we will need a corresponding `MillKotlinBuildServer.scala` file. We may also need changes on the IntelliJ side to allow the IntelliJ BSP client to generate Kotlin modules, if it doesn't already support that

**Comment by lihaoyi** [comment]
@alexarchambault could you look into this when you're done with the current tickets you're working on?

**Comment by alexarchambault** [comment]
Sure, I was actually in the midst of adding basic BSP integration tests (that would have caught BSP issues in the current state of #3599, and were needed for future BSP developments anyway, I think)

**Comment by lihaoyi** [comment]
I think we can close this, because it seems to work now. Thanks @alexarchambault !
