### ISSUE TITLE
Add javalib examples on using `jlink`, `jpackage`, and producing JPMS modules (500USD Bounty)

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#3638]
---

**From the maintainer Li Haoyi**: I'm putting a 500USD bounty on this issue, payable by bank transfer on a merged PR implementing this.

---

These are newer Java tools that we should have documented/tested golden paths to using. The examples should go in `example/javalib/module` with `/** Usage */` tests and textual explanations of what the examples are doing and how they relate to the underlying tools and concepts (with links to the relevant upstream documentation pages)

**Comment by lefou** [comment]
* https://github.com/com-lihaoyi/mill/pull/3201

**Comment by ayewo** [comment]
Hi @lihaoyi 
I've just opened a PR.

When you have a moment, would appreciate it if you could take a look.
