### ISSUE TITLE
New ticker/prompt in 0.12 causing CPU load on terminal emulator

### ISSUE THREAD

**Issue by farnoy** [com-lihaoyi/mill#3658]
Testing `0.12.0-RC2-38-029986`, Windows 11 x64 with [millw.bat](https://github.com/lefou/millw/blob/main/millw.bat).

When running `mill -w someTask`, the CPU load on my terminal emulator (alacritty) is increased when compared to `mill --disable-prompt -w someTask`. This is best seen when the task finishes executing and is in idle/waiting state monitoring for any inputs to change. The system is otherwise idle but it seems the prompt is producing a lot of updates to update the time counter (?), causing unnecessary load on the terminal emulator. It can use up to 50% of one core, so the overhead is significant (and my laptop ramps up because of it)

The increased CPU load is the same if I run my desktop at 60Hz or 240Hz, which I think means the load on the terminal emulator is the same and caused by Mill (the producer of this output).

**Comment by lihaoyi** [comment]
@farnoy could you hook up jprofiler to the process to see what its doing? or send me the profile so i can take a look

**Comment by farnoy** [comment]
The CPU usage is not in the mill process, but the terminal emulator. I can't reproduce this on the Windows Terminal, so it may be an issue with alacritty. Is there some non-standard output by Mill, or is it just outputting `\r$newContent` every second?

**Comment by lihaoyi** [comment]
If I'm not mistaken it does a bit more than that due to the multi line prompt: it does LEFT_9999 UP_PromptHeight and redraws the prompt 10 times a second. This can probably be optimized. I wonder if the 9999 is causing issues

**Comment by lihaoyi** [comment]
@farnoy I don't have a windows machine handy, but if you do you can try changing this `9999` (https://github.com/com-lihaoyi/mill/blob/e0a2c93bfbc7bf68a71ddbc0c52afbb14e73e6f2/main/util/src/mill/util/PromptLogger.scala#L291) to `999` or something, use `./mill installLocal` to create a new binary, and seeing if it exhibits the same issue

**Comment by farnoy** [comment]
I couldn't reproduce this with the latest tip, and in fact RC3 has already fixed it. I bisected RC2 against RC3 (based on tags in git, RC2 shows up as something like RC2-38-xxx in Mill itself).

The first commit that fixed this as far as I can tell is 49a28110a6153b0f77ca71c3538c325b5d7cdd17. So no new issue after all, I'm just upgrading my project to use RC3 (ty for publishing)

**Comment by farnoy** [comment]
Rather, the issue still exists as the new progress prompt is placing extra load on this specific terminal emulator, but after that commit, at least it's not draining cycles when it's idle and waiting for inputs to change.
