### ISSUE TITLE
Main Page shows graph notation instead of rendered picture

### ISSUE THREAD

**Issue by gamlerhart** [com-lihaoyi/mill#3699]
The main mill-build.org page suddenly doesn't render the graph anymore, but shows the raw graph notation:

![image](https://github.com/user-attachments/assets/4c610aa6-9d92-4547-84bf-b6c87ba050d2)

**Comment by lihaoyi** [comment]
thanks for the reort, should be fixed by https://github.com/com-lihaoyi/mill/pull/3698

**Comment by lihaoyi** [comment]
Should be fixed by https://github.com/com-lihaoyi/mill/pull/3700
