### ISSUE TITLE
Error: Unresolved Reference (Kotlin Android Jetpack Compose)

### ISSUE THREAD

**Issue by himanshumahajan138** [com-lihaoyi/mill#3735]
## Issue
**Error: Unresolved Reference (Kotlin Android Jetpack Compose)**

### Description
**Error:**  `Unresolved Reference` (This Issue comes out when we are trying to implement androidx libraries related to issue: #3550 and pr: #3696)

### Steps to Reproduce

1. Cherry Pick the commits of Pr: #3696 
2. Run the Command `./mill -i -j3 -k example.kotlinlib.android[2-jetpack-compose-hello-world].__.local.testCached`
3. After running it will get _unresolved reference error for andoridx libraries_ 

### Expected Behavior
It should compile and build the application using jetpack compose 

### Actual Behavior
Getting unresolved reference error which should not come in general coz we are using aar and jar files both and following rules.

### Logs
Actual Error: https://github.com/com-lihaoyi/mill/pull/3696#issuecomment-2405827244

CompileClasspath(before converting aar to jar): https://github.com/com-lihaoyi/mill/pull/3696#issuecomment-2407513779

CompileClasspath(after converting aar to jar): https://github.com/com-lihaoyi/mill/pull/3696#issuecomment-2408521905

### Additional Information
This issue is raised to get some attention regarding the issue #3550 part 4th and i think current issue needs to be solved first

Please help out, if anyone can solve this or guide me for this...

**Comment by lihaoyi** [comment]
Please do not open additional issues, we already have the pull request thread for discussion

**Comment by himanshumahajan138** [comment]
Actually @lihaoyi Sir, as pull request #3696 is in draft mode so no one was replying on updates so for that i thought we should discuss this issue in separate but no worries i think we can continue in #3550 issue and extend the conversation there 

thanks !!!
