### ISSUE TITLE
`assembly` task fails with exception if `resources` contain direct path to file

### ISSUE THREAD

**Issue by megri** [com-lihaoyi/mill#374]
It seems like assembly assumes that every file is jar: https://github.com/lihaoyi/mill/blob/c7c91451435a113f61f3324eeb5024cb51e0afd2/main/src/mill/modules/Assembly.scala#L85

**Comment by rockjam** [comment]
@megri What could be the other option? Actually, it takes directories into account too: https://github.com/lihaoyi/mill/blob/c7c91451435a113f61f3324eeb5024cb51e0afd2/main/src/mill/modules/Assembly.scala#L84

**Comment by rockjam** [comment]
It would be awesome to have more of context here. Why assuming that every file is a jar file is a bad thing? Do you have a specific use-case where this breaks?

**Comment by rockjam** [comment]
I guess the reasoning is here: https://gitter.im/lihaoyi/mill?at=5b20cb8aa0161836cb16f90e , right?

**Comment by megri** [comment]
@rockjam Yes, sorry I should have been more specific. I'm still not sure if it is working as intended but @lihaoyi's reaction indicated that it wasn't.

**Comment by benjaminfrank** [comment]
I agree that it would be nice if we could add individual files to resources instead of only folders.
Use case would be the generation of resources/assets where the generation creates more then just the final files, e.g. temp files. in this case simply adding the containing folder would also add the temp files or the task has to clean up.

**Comment by lihaoyi** [comment]
It seems reasonable to be able to add individual files to an assembly. Two constraints:

- We need some way of differentiating files added as their jar-contents and files added as individual files. Looking for a `.jar` suffix would be a naive way of doing it, but would make it impossible to include a `.jar` file as a file inside another jar (e.g. maybe you don't want it on your classpath but want to serve up that jar as a resource)

- For individual files, we need some way of specifying what path they get assigned in the assembly. Many existing JVM CLI tools simply put them at `/file-name.ext`, but I personally find that pretty unsatisfactory.

It seems we may need to change `createAssembly` to take some sort of `items: Seq[Either[PathRef, (String, PathRef)]]` to let people specify these things (`Left` would be folders & jar-contents, `Right` would be individual files together with their assigned path). If someone wants to try making this not-ugly and put together a PR that would be great

**Comment by lihaoyi** [comment]
Also, it would be nice to get rid of `createJar` and unify that code path with `createAssembly`, since they basically do the same thing except `createAssembly` can take upstream jars

**Comment by megri** [comment]
Would it make sense to have a separate task like `stageArtifacts` that puts "everything" in a place where it can later be picked up by stuff like `createAssembly`/`createJar`? Maybe it's still too coarse-grained to work reliably for every situation — it feels as if it would call for something like the configuration axes SBT uses to differentiate between various use-cases, if that makes any sense...

**Comment by lihaoyi** [comment]
Probably going to call this a wontfix
