### ISSUE TITLE
`runIvyDeps` should be transitive for consistency with Maven resolution

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#3761]
### Discussed in https://github.com/com-lihaoyi/mill/discussions/3722

<div type='discussions-op-text'>

<sup>Originally posted by **megri** October 12, 2024</sup>
Let's say we have the modules `A <- B <- C` where `<-` denotes a "depends on" relationship

```scala
// running with mill version 0.11.12
import mill._, mill.scalalib._

trait BaseModule extends ScalaModule {
  def scalaVersion = "3.5.1"
}

object C extends BaseModule {
  def ivyDeps = Agg(
    ivy"org.slf4j:slf4j-api:2.0.16"
  )
}

object B extends BaseModule {
  def moduleDeps = Seq(C)

  def runIvyDeps = Agg(
    ivy"ch.qos.logback:logback-classic:1.5.10"
  )
}

object A extends BaseModule {
  def moduleDeps = Seq(B)
}
```

So `C` introduces slf4j and `B` a logging implementation. `mill A.ivyDepsTree --withRuntime` shows

```
[build.sc] [54/59] compile 
[info] compiling 1 Scala source to /Users/martin/dev/mill-deps-test/out/mill-build/compile.dest/classes ...
[info] done compiling
[26/26] A.ivyDepsTree 
├─ org.scala-lang:scala3-library_3:3.5.1
│  └─ org.scala-lang:scala-library:2.13.14
└─ org.slf4j:slf4j-api:2.0.16
```

While the example may seem a little contrived—why not define the runtime dependency in the A module?—this has consequences with for instance assemblies. At work we have a project of several Spark applications (as separate modules) that are packaged into one single assembly for easy shipping. These modules have different but non-conflicting [runtime] dependencies, and the assembly won't collect the runtime parts without overriding for instance `transitiveIvyDeps` (which solves one level of transitivity—it has to be overridden in all modules to include "deep" runIvyDeps.)

Aside from backwards compatibility, would making runIvyDeps transitive be an issue? </div>

**Comment by megri** [comment]
I think I can implement this, but I'd like us to map out which parts need to be touched and expected outcomes.
Today we basically have no transitivity and the runtime dep doesn't end up in packaged artefacts. This change would make it so that

- modules inherit runtime dependencies through something akin to `transitiveIvyDeps`
- runtime deps are included in packaged jars and Pom-files.

What else?
