### ISSUE TITLE
Enforce ScalaFmt/PalantirJavaFormat/KtLint on example doc/test suites (500USD Bounty)

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#3829]
---

**From the maintainer Li Haoyi**: I'm putting a 500USD bounty on this issue, payable by bank transfer on a merged PR implementing this.

---

Currently managing the formatting for this is manual, and sometimes inconsistencies slip through. We should really just automate enforcement and compliance.

We should as much as possible re-use the infrastructure Mill has already built around these autoformatters, to dogfood it. This would mean doing the autoformatting as part of Mill's own Mill build, using the various `ScalaFmtModule`/`PalantirJavaFormatModule`/`KtLintModule`s as necessary

**Comment by LevisNgigi** [comment]
Hello interesting but I think this might not be beginner friendly for someone new to the project.Will be on the lookout for other issues.

**Comment by Sailsman63** [comment]
In this context, what does "Automate enforcement and compliance" look like?

- Just surface the errors in the build script CI, block PRs on fixing them
- Automatically apply and commit fixes on merge
- Other?

**Comment by lihaoyi** [comment]
> Just surface the errors in the build script CI, block PRs on fixing them

Just this, with some manual command that can be run to fix them locally. Same as the current workflow.

**Comment by myyk** [comment]
I'm going to see if I can figure this one out tomorrow

**Comment by lihaoyi** [comment]
@myyk some pointers if you're going to look into this:

1. This should be purely a change in the `build.mill`/`package.mill` files, shouldn't need any application code changes

2. The default `mill.scalalib.scalafmt.ScalafmtModule` defaults to [looking for `__.sources`](https://github.com/com-lihaoyi/mill/blob/d5d56b5d55d59972bbe8bef2cb647e4c5f96fdd3/scalalib/src/mill/scalalib/scalafmt/ScalafmtModule.scala#L77-L99), so the easiest thing to do would be to hook into that by defining a `sources` in `ExampleCrossModule` that points to `testRepoRoot` so it can get picked up by `ScalafmtModule/formatAll` and `checkFormatAll`

3. To make this work for Java sources as well, we would need to run `PalantirFormatModule`  in addition to `ScalafmtModule` in CI [here](https://github.com/com-lihaoyi/mill/blob/d5d56b5d55d59972bbe8bef2cb647e4c5f96fdd3/.github/workflows/run-tests.yml#L155)

4. The example tests rely on comments being formatted in specific ways to be parsed and used as test commands. We may need to tweak add [`docstrings.style = keep`](https://scalameta.org/scalafmt/docs/configuration.html#docstringsstyle--keep) to our `.scalafmt.conf` to preserve them as is

**Comment by myyk** [comment]
Thanks! I was trying to piece together 2, that helps a lot. That all makes sense.

**Comment by myyk** [comment]
Hooking up the [`PalantirFormatModule`](https://mill-build.org/mill/0.12.1/javalib/linting.html#_autoformatting_with_palantir_java_format) is not straight forward.

In `example/package.mill` there's `ExampleCrossModuleJava` which extends `ExampleCrossModule` which extends `build.integration.IntegrationTestModule` which has:

`def moduleDeps: Seq[`package`.MillScalaTests]`

While I think I need to add `ExampleCrossModuleJava extends PalantirFormatModule` which has:

`def moduleDeps: Seq[JavaModule]` from `PalantirFormatModule extends JavaModule`

There's a lot going on here and I'm not sure why Java/Scala Modules can't be combined. So I'm not sure if I should be splitting up the Scala/Java code in these `.mill` files more to get this all to work? Or if that's the wrong line of thinking.
