### ISSUE TITLE
Assembly.defaultRules should exclude well-known temp files

### ISSUE THREAD

**Issue by raskam** [com-lihaoyi/mill#383]
In my case, when I tried to assembly fatjar on my station, Mill included `.DS_Store` in the fatjars. It probably comes from project `resources` folder. Obviously this would not happen during production build on server, but the issue is probably more generic. Maybe only resources tracked by VCS should be added to the final fat-jar?

**Comment by lihaoyi** [comment]
I probably won't want to tie Mill to a VCS for now; maybe just filter out `.DS_STORE` from `resources/` yourself for now?

**Comment by raskam** [comment]
This is what I'm doing now. Do you want to include `.DS_STORE` and other commonly ignored files into the Mill codebase or should each end-project define it? There are already some default exclusions (.dsa, .rsa, ...) so it may be worth including others as well (e.g. taken from https://github.com/github/gitignore)

**Comment by smarter** [comment]
How about excluding all hidden files by default ? (Does sbt-assembly do that?)

**Comment by lihaoyi** [comment]
Should be done, we now use these set of default assembly rules
```scala
  val defaultRules: Seq[Rule] = Seq(
    Rule.Append("reference.conf", separator = "\n"),
    Rule.Exclude(JarFile.MANIFEST_NAME),
    Rule.ExcludePattern(".*\\.[sS][fF]"),
    Rule.ExcludePattern(".*\\.[dD][sS][aA]"),
    Rule.ExcludePattern(".*\\.[rR][sS][aA]")
  )
```
