### ISSUE TITLE
Add Mill+Scala.js+WASM example (500USD Bounty)

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#3837]
---

**From the maintainer Li Haoyi**: I'm putting a 500USD bounty on this issue, payable by bank transfer on a merged PR implementing this.

---

Scala.js now supports WebAssembly output (https://www.scala-js.org/news/2024/09/28/announcing-scalajs-1.17.0/). We should have an example doc-test in `example/scalalib/web/` exercising the hello-world Scala.js webassembly dev workflow using Mill and include it in `scalalib/web-examples.adoc` as documentation.

**Comment by Quafadas** [comment]
To be honest, I'll likely have a look at this for my own curiosity in the coming days if no-one were to pick it up beforehand. 

I think the key question, is whether the scope of the example includes a "live reload" solution?

**Comment by lihaoyi** [comment]
> I think the key question, is whether the scope of the example includes a "live reload" solution?

No, I just want a hello-world setup. Nothing fancy, just showing off that we can create a WASM output file and run it through some WASM interpreter or runtime

**Comment by lihaoyi** [comment]
We don't have a browser in the example test suite, so you'll need to find some CLI wasm runtime to replace it

**Comment by Quafadas** [comment]
> We don't have a browser in the example test suite, so you'll need to find some CLI wasm runtime to replace it

Hmmm, right, I hear you. The other option could be to wheel in playwright? Doesn't need an answer now. I'll explore it.

**Comment by yadavshubham01** [comment]
hey @lihaoyi look quite interesting working on it

**Comment by lihaoyi** [comment]
Go for it, bounties remain open until they are closed with a merged PR

**Comment by Quafadas** [comment]
@yadavshubham01 

i guess for the avoidance of conflict - it’s all yours for a few days :-).

**Comment by yadavshubham01** [comment]
hey @lihaoyi checkout this pr #3839
