### ISSUE TITLE
Add an example Python Support case study (500USD bounty)

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#3862]
---

**From the maintainer Li Haoyi**: I'm putting a 500USD bounty on this issue, payable by bank transfer on a merged PR implementing this.

---

This would be similar to the example Typescript support case study we have in https://mill-build.org/mill/0.12.1/extending/new-language.html, but instead of typescript/npm/tsc/rollup we would use python/pip/mypy/pex (or equivalent). We should take care to make sure things are installed in the dest folders using virtualenvs or whatever, rather than globally as python traditionally defaults to

Doesn't need to be production ready, just complete enough for educational purposes illustrating the various Mill features

**Comment by himanshumahajan138** [comment]
@lihaoyi i have a great knowledge of python and now for mill too (after your guidance and merged pr's) i would like to work around this i know bounties are open until merged pr but i just want to get a safe apart from clash so i commented 

Hope you understand !

**Comment by c0d33ngr** [comment]
@lihaoyi  wouldn't it be better structure like this

```
newlang/
  typescript/
    ...
  python3/
    ...
```

**Comment by c0d33ngr** [comment]
@himanshumahajan138 looked through your PR and you have already gone far. Lucky for you, I'll just let you move ahead with the issue. I don't want to do any catching up, after all there are other bounties that need to be resolved.

Goodluck

**Comment by himanshumahajan138** [comment]
@c0d33ngr Buddy, there is one Kotlin PR of Mine actually its almost done 95% and only support of aar file needs resource compilation and merging 

If you want to taste bounty you can try that just Chery pick my commits and then start working ahead of it...

Best of luck...

**Comment by c0d33ngr** [comment]
> @c0d33ngr Buddy, there is one Kotlin PR of Mine actually its almost done 95% and only support of aar file needs resource compilation and merging
> 
> If you want to taste bounty you can try that just Chery pick my commits and then start working ahead of it...
> 
> Best of luck...

I don't understand the last line

**Comment by himanshumahajan138** [comment]
Actually cherry picking is just like cloning a part of the repo like the updates till a commit...
More you can find on google 🙃
