### ISSUE TITLE
`methodCodeHashSignatures` throw a `os.ResourceNotFoundException`

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#3874]
Just before the build failure, I deleted the `tests` object from a Scala source file under `mill-build/src` (see below). I did not change the Mill version.

```
> mill --version
Mill Build Tool version 0.12.1-7-d8bbe5
Java version: 21.0.4, vendor: Eclipse Adoptium, runtime: /opt/openjdk-bin-21.0.4_p7
Default locale: de_DE, platform encoding: UTF-8
OS name: "Linux", version: 6.1.90-gentoo-x86_64, arch: amd64
```

This is probably related to
* https://github.com/com-lihaoyi/mill/pull/3849

Here's the stack trace:

```
1 tasks failed
methodCodeHashSignatures os.ResourceNotFoundException: java.net.URLClassLoader@1450ee23/comfisbuild/BuildTemplate$tests$.class
    os.ResourcePath.getInputStream(ResourcePath.scala:21)
    os.read$inputStream$.apply(ReadWriteOps.scala:245)
    mill.codesig.ExternalSummary$.load0$1(ExternalSummary.scala:55)
    mill.codesig.ExternalSummary$.$anonfun$apply$6(ExternalSummary.scala:48)
    scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
    scala.collection.mutable.HashMap.getOrElse(HashMap.scala:451)
    mill.codesig.ExternalSummary$.load$1(ExternalSummary.scala:48)
    mill.codesig.ExternalSummary$.$anonfun$apply$9(ExternalSummary.scala:69)
    mill.codesig.ExternalSummary$.$anonfun$apply$9$adapted(ExternalSummary.scala:69)
    scala.collection.immutable.BitmapIndexedSetNode.foreach(HashSet.scala:951)
    scala.collection.immutable.HashSet.foreach(HashSet.scala:958)
    mill.codesig.ExternalSummary$.apply(ExternalSummary.scala:69)
    mill.codesig.CodeSig$.compute(CodeSig.scala:17)
    mill.runner.MillBuildRootModule.$anonfun$methodCodeHashSignatures$2(MillBuildRootModule.scala:173)
    mill.define.Task$TraverseCtx.evaluate(Task.scala:215)
```

This project has a meta-build which defines some `trait`s to be used in the `build.sc`. 

Here is a sketch of the relevant parts of the project:

```scala
// file: build.sc
package build

object `package` extends RootModule with comfisbuild.BuildTemplate 
```

```scala
// file: mill-build/src/BuildTemplate.scala
package comfisbuild

trait BuildTemplate extends Module {

  // this one I deleted just before the os.ResourcesNotFoundException
  object tests extends TaskModule {
    override def defaultCommandName(): String = "tests"
    /** Prints a test summary for each passed test task. */
    def tests(@mainargs.arg(positional = true) testTasks: mill.main.Tasks[(String, Seq[TestResult])]): Command[Unit] = T.command {
      val res = T.sequence(testTasks.value)()
      T.log.outputStream.println(ComfisUtil.formatTestSummary(res))
    }
  }
}
```

**Comment by lihaoyi** [comment]
Interesting. This suggests that the issue isn't specifically related to changing Mill version, but is a more general issue with changes in the mill-build classpath

**Comment by lihaoyi** [comment]
@lefou did you manage to zip up the classfiles in `out/mill-build/compile.dest/` to look at? So we can see which class is still referencing `BuildTemplate$tests$.class` and causing Mill to try and load it

**Comment by lefou** [comment]
Yeah, the only references to the deleted object `BuildTemplate$tests` came from files in the `millbuild` package, which I think where generated by Mill itself. 

```
> find out/mill-build/compile.dest/classes/millbuild/ 
out/mill-build/compile.dest/classes/millbuild/
out/mill-build/compile.dest/classes/millbuild/build$package$.class
out/mill-build/compile.dest/classes/millbuild/MiscInfo_build$.class
out/mill-build/compile.dest/classes/millbuild/build.class
out/mill-build/compile.dest/classes/millbuild/MiscInfo_build.class
out/mill-build/compile.dest/classes/millbuild/build$.class

> LC_ALL=C grep "BuildTemplate\$tests" out/mill-build/compile.dest/classes/millbuild/*
grep: out/mill-build/compile.dest/classes/millbuild/MiscInfo_build$.class: binary file matches
grep: out/mill-build/compile.dest/classes/millbuild/build$package$.class: binary file matches
```

**Comment by lefou** [comment]
```
> javap -c out/mill-build/compile.dest/classes/millbuild/build\$package\$.class | grep "BuildTemplate\$tests"
  public comfisbuild.BuildTemplate$tests$ tests();
       1: getfield      #261                // Field tests$module:Lcomfisbuild/BuildTemplate$tests$;
      12: getfield      #261                // Field tests$module:Lcomfisbuild/BuildTemplate$tests$;
```

```
> javap -c out/mill-build/compile.dest/classes/millbuild/MiscInfo_build\$.class | grep "BuildTemplate\$tests"
  public static final mill.define.Command $anonfun$millBaseModuleInfo$11(comfisbuild.BuildTemplate$tests$, scala.collection.immutable.Seq);
      11: invokevirtual #1368               // Method comfisbuild/BuildTemplate$tests$.tests:(Lmill/main/Tasks;)Lmill/define/Command;
```

**Comment by lihaoyi** [comment]
I wonder if its an incremental undercompilation problem, possibly due to the package object (in 0.11.x) or due to the discover macro (in both versions). It seems the package object class still has a field pointing at the deleted module object even after the module object has been removed.

From your output, the issue occurred in Mill 0.11.x. If you can get a it to occur after switching to 0.12.x, I'd be interested in seeing whether the javap has a similar pattern

**Comment by lefou** [comment]
So this must be a stale issue in my project lying around, since I didn't switch the version for a while. It only occurred when I deleted the object. 

Undercompilation is also what I think is the real reason. So the best handling would be to invalidate the incremental compile state. But the compile task is already finished, so we might need some backtracking to fix it.

Since my attempt to fix this issue in PR #3849 does not invalidate the compile cache, it probably results in a too inefficient change detection until the next full clean of the compile state.

Maybe, we can just always do a full compile in `MillRootBuildModule` when the Mill version changes. This may result in a slower compile but ideally, the code hash signature logic should be able to still figure out the smallest invalidation impact.

**Comment by lihaoyi** [comment]
> Maybe, we can just always do a full compile in MillRootBuildModule when the Mill version changes. This may result in a slower compile but ideally, the code hash signature logic should be able to still figure out the smallest invalidation impact.

Isn't this issue a case where the problem happened without a Mill version change? I'm not sure if I'm mis-understanding.

We could definitely add a try-catch the class loading to just ignore missing files, but I wonder if it'll just end up transforming this up-front error into an error down the line. If we're getting classfiles with references to non-existent classes, I assume all sorts of things can go wrong

**Comment by lefou** [comment]
> > Maybe, we can just always do a full compile in MillRootBuildModule when the Mill version changes. This may result in a slower compile but ideally, the code hash signature logic should be able to still figure out the smallest invalidation impact.
> 
> Isn't this issue a case where the problem happened without a Mill version change? I'm not sure if I'm mis-understanding.

You said yourself that the stale classfiles are left overs from when this project was build with an older version of Mill. So, my assumption is, that because we just did an incremental compile at Mill version switch time, we ended up with left over classfiles in the first place. If we always cleanup old classfiles with a version change, we don't have to deal with them later.

**Comment by lihaoyi** [comment]
Got it. Yes doing a clean compile on version change seems reasonable

**Comment by lefou** [comment]
I've opened #3884 which should fix these kind of issues. It simply does a full recompile when the Mill version has changed. This will fix all potential issues due to under-compilation and left-over class files. It might be slower on a version change, but will keep optimization downstream, since our `methodCodeHastSignatures`-task doesn't break on missing class files.
