### ISSUE TITLE
Calling an exclusive command from a non-interactive command results in a `NoSuchElementException`

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#3875]
When running the following command:

```scala
def cleanClient(ev: Evaluator) = Task.Command {
  clean(ev, "appClient")()
}
```

Mill errors out with the following error:

```
> mill cleanClient
...
An unexpected error occurred
Exception in thread "MillServerActionRunner" java.util.NoSuchElementException: key not found: Labelled(clean,Segments(List(Label(clean))))
```

If the `cleanClient` command `interactive = true`, the error goes away.

```scala
def cleanClient(ev: Evaluator) = Task.Command(exclusive = true) {
  clean(ev, "appClient")()
}
```

```
> arturaz@razor:~/work/chqmate> ./mill cleanClient
[build.mill-57/61] compile
[build.mill-57] [info] compiling 1 Scala source to /home/arturaz/work/chqmate/out/mill-build/compile.dest/classes ...
[build.mill-57] [info] done compiling
[build.mill-57] [info] compiling 3 Scala sources to /home/arturaz/work/chqmate/out/mill-build/compile.dest/classes ...
[build.mill-57] [info] done compiling
[1/2] clean
[2/2] cleanClient
[2/2] =================================================================================== cleanClient ================================================================================= 7s
```

**Comment by lihaoyi** [comment]
I guess this makes sense; the evaluator hardcodes the assumption that all exclusive commands run after the non-exclusive stuff, and so when the non-exclusive command tries to look up the exclusive upstream task in the list of non-exclusive upstream task it fails to find it.

It feels like the correct thing to do here is to raise a proper error when a non-exclusive task depends on an exclusive task

**Comment by lefou** [comment]
Another resolution could be to not necessarily run exclusive tasks at the end but only isolated (non-parallel to any other) but still before all its dependencies.

**Comment by lefou** [comment]
As a side note, in `sbuild`, I had two different ways to express concat task dependencies, `a ~ b` to have two dependencies that can resolve in parallel and `a ~~ b` which meant that `a`needs to finish before `b`. This is only necessary in the context of commands, e.g. when I want to have a clean build in a single CLI invocation, I need to be able to express, that the `clean` command needs to be run before I even start to fulfill dependencies of the actual build. 

If we could have isolated commands not only in the end but also anywhere in the middle of the execution plan we could also run clean builds in Mill with a single run. E.g. `mill clean ++ __.compile` which could guarantee that `clean` is run before any other dependency of `__.compile`.

**Comment by lihaoyi** [comment]
Yeah having some way to order commands would be nice, so `clean` can run first rather than in some random order

**Comment by lihaoyi** [comment]
Just add a nice error message for now, more involved changes like allowing exclusive commands to run earlier or adding syntax for explicit sequencing of tasks can come later

**Comment by lefou** [comment]
* https://github.com/com-lihaoyi/mill/issues/3898
