### ISSUE TITLE
Evaluator commands duff `out/mill-chrome-profile.json` 

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#3879]
Evaluator commands make the `out/mill-chrome-profile.json` un-useful since they seem to overwrite it.

Here is an example, where `idea` is a customized derivate of `mill.idea.GenIdea/idea`.

While the command is still running, I can see a partially filled `out/mill-chrome-profile.json` with lots of details:

![image](https://github.com/user-attachments/assets/467cd7e7-d4c4-424b-b7bb-a83ecb5e75f5)

But after the command finishes, the `out/mill-chrome-profile.json` looks less useful:

![image](https://github.com/user-attachments/assets/f358db49-41e7-4a19-8b64-c99044bdc2fe)

**Comment by lihaoyi** [comment]
Maybe every time we open `mill-chrome-profile.json`, we should check if one exists, and if one does then open `mill-chrome-profile-2.json`  `mill-chrome-profile-3.json` etc.. We can wipe out all `mill-chrome-profile*.json`s at the start of each run. This would ensure that all profiles are saved, even if multiple evaluation runs are started re-entrantly

The same should probably be done for the other `mill-*` debug files

**Comment by lefou** [comment]
I think this is because evaluator command use there dedicated evaluator instances which don't use the outer profile logger. Instead, we could pass the profile logger around.

**Comment by lihaoyi** [comment]
oh yeah that's also an option. Then the same profile would show tasks from all evaluations, which would be even better
