### ISSUE TITLE
The compiler bridge output should be invalidated in more cases

### ISSUE THREAD

**Issue by smarter** [com-lihaoyi/mill#389]
Right now the compiler bridge generation is controlled by:
https://github.com/lihaoyi/mill/blob/436e5e21f526a8e9758bd11c8b9b221253d50663/scalalib/worker/src/mill/scalalib/worker/ScalaWorker.scala#L34-L36

There's several things missing compared to sbt here:
- The bridge is cached based only on the scala version, this isn't enough: for correctness, it should also include the classfile version (otherwise the user will get an error if he switches to an older Java version) and the compiler bridge version (otherwise when mill upgrades the compiler-bridge version it's running, nothing will happen on existing projects), see https://github.com/sbt/zinc/blob/1.x/internal/zinc-ivy-integration/src/main/scala/sbt/internal/inc/ZincComponentCompiler.scala#L228-L247
- If the compiler bridge compilation fails, it will never be retried because we only check the existence of the directory where the compilation output should be. (By the way, I've observed than when the compiler bridge compilation fails with an exception, this exception is never shown to the user).

**Comment by lihaoyi** [comment]
> otherwise when mill upgrades the compiler-bridge version it's running, nothing will happen on existing projects

this should bust all caches, due to https://github.com/lihaoyi/mill/blob/7898368fe809779e73ef1cd909f1b2e5de84e6c1/core/src/mill/eval/Evaluator.scala#L383

**Comment by lefou** [comment]
Is this still relevant?

**Comment by lefou** [comment]
Closing this, as I think we have meanwhile a pretty robust handling of the compiler bridge. Please comment, if you think there are still cases where we miss an opportunity to invalidate the compile bridge.
