### ISSUE TITLE
RevApi support (500USD Bounty)

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#3929]
---

**From the maintainer Li Haoyi**: I'm putting a 500USD bounty on this issue, payable by bank transfer on a merged PR implementing this.

---

This has come up in both Netty and Mockito case studies, so we should properly support it with a built in Mill plugin

Will likely end up looking similar to our support for linters like ErrorProne and Checkstyle, as well as @lolgab's mill-mima plugin

**Comment by lefou** [comment]
https://revapi.org/revapi-site/main/index.html
