### ISSUE TITLE
Scalafmt doc link is broken.

### ISSUE THREAD

**Issue by counter2015** [com-lihaoyi/mill#3959]
see: https://scalameta.org/scalafmt/docs/installation.html#mill

There is a link to mill doc about configuring scalafmt: https://com-lihaoyi.github.io/mill/page/configuring-mill.html#reformatting-your-code

It seems the link is broken.

Is there any plan to publish example of setting scalafmt on mill ? I found there are some examples here: https://github.com/com-lihaoyi/mill/blob/5eebf62111e921b125582ffe7a9036e207970b9a/example/scalalib/linting/1-scalafmt/build.mill

**Comment by lihaoyi** [comment]
The current URL for the scalafmt example is https://mill-build.org/mill/scalalib/linting.html#_autoformatting_with_scalafmt.

You probably need to send a PR upstream to the scalafmt docsite
