### ISSUE TITLE
Add Kotlin Spring-Boot examples (500USD Bounty)

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#3963]
---

**From the maintainer Li Haoyi**: I'm putting a 500USD bounty on this issue, payable by bank transfer on a merged PR implementing this.

---

These should live in `example/kotlinlib/web/6-hello-spring-boot` and `example/kotlinlib/web/7-todo-spring-boot`, basically a kotlin version of `example/javalib/web/2-hello-spring-boot` `example/javalib/web/3-todo-spring-boot` but using Kotlin instead of Java 

No need for any KotlinJS or other fancy stuff, just a vanilla spring boot web app with server side templates and some vanilla CSS and javascript

**Comment by himanshumahajan138** [comment]
Working on this ✨
