### ISSUE TITLE
Running "fix" on an empty module fails

### ISSUE THREAD

**Issue by HilcoWijbenga** [com-lihaoyi/mill#4006]
A project with _just_ this `build.mill` (using Mill `0.12.2`) dies on `./mill __.fix`.

```
package build

import $ivy.`com.goyeau::mill-scalafix::0.4.2`
import com.goyeau.mill.scalafix.ScalafixModule
import mill.scalalib.SbtModule

object main extends SbtModule with ScalafixModule {
    def scalaVersion = "2.13.15"
}
```

It might seem strange not to have any sources in a module but I have a couple of "aggregation" modules that simply list other modules that they depend on. This used to work fine (pre `0.12`).

Adding a single source file makes the problem go away ... but then I have a useless source file. :-)

**Comment by HilcoWijbenga** [comment]
Mmm, this might actually be an issue with Mill's ScalaFix plugin. I also see the problem with Mill `0.11.5` when upgrading to `0.4.2`.

**Comment by lihaoyi** [comment]
CC @joan38 , do you know if this behavior is intended? I think we work around this a few places in Mill's own build via `def fix(args: String*): Command[Unit] = Task.Command {}`, but it would be nice if it worked out of the box

**Comment by joan38** [comment]
Ah I was not aware of this issue.
We should fix this issue in mill-scalafix!

**Comment by lihaoyi** [comment]
Closing this in favor of https://github.com/joan38/mill-scalafix/issues/213
