### ISSUE TITLE
Deadlock when worker JVM cannot be started

### ISSUE THREAD

**Issue by rhyskeepence** [com-lihaoyi/mill#405]
I've just started porting a sbt build to mill. From what's I've seen so far, it is awesome. However I noticed when I upgraded from 0.2.0 to 0.2.6 that my build began to deadlock, at mill.main.client.MillClientMain.run(MillClientMain.java:118). 

Looking 'out/mill-worker-1/logs', the root cause appears to be that -XX:VMOptionsFile is not supported by oracle's java 8.

It would be nice if:
- java 8 is supported, by removing vmoptionsfile
- or, don't support oraclejdk1.8, and fail fast

**Comment by bledari** [comment]
I was following the getting started and this issue made me see the logs

**Comment by Claus1** [comment]
on Windows after renaming 0.3.3 downloaded file to mill.bat as proposed I got      Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Unrecognized VM option 'VMOptionsFile=C:\MyProjects\test\out\mill-worker-1\vmoptions'

out\vmoptions contains only a string:
-DMILL_VERSION=0.3.3-1-ff45d2

**Comment by lefou** [comment]
See #781

**Comment by sake92** [comment]
@rhyskeepence @Claus1 @bledari please try with latest "0.6.1-121-3f10a4-assembly"

**Comment by sake92** [comment]
Fixed in #791
