### ISSUE TITLE
Rewrite basic docs, without ExampleCrossPythonModule

### ISSUE THREAD

**Issue by jodersky** [com-lihaoyi/mill#4054]
In light of the discussion here, https://github.com/com-lihaoyi/mill/pull/4042, we should re-write the example docs of `pythonlib/basic`, with a plain ExampleCrossModule

**Comment by jodersky** [comment]
Would you mind taking a shot at this, @himanshumahajan138?

**Comment by himanshumahajan138** [comment]
@jodersky ya for sure i will add docs

**Comment by himanshumahajan138** [comment]
also should we make this inheritable(means we can inherit these docs later for other examples based on same pattern) or simple ??

**Comment by jodersky** [comment]
I would suggest we keep it as simple as possible to start.

Python support is a brand new feature, and while of course we want to implement a fully functional user experience, we also need to acknowledge that the first version will be no where near as polished as the scala and java support mill currently has. All to say, there will most likely be refactoring work to be done, and we can look into how we can extract common doc behavior when that time comes. Before is probably premature
