### ISSUE TITLE
Support for webpack in Scala.js modules.

### ISSUE THREAD

**Issue by crimzie** [com-lihaoyi/mill#410]
Some libraries targeting Scala.js require the 'sbt-scalajs-bundler' sbt plugin in dependent projects, because they themselves depend on npm packages. To use this kind of libraries with mill one has to bundle those javascript dependencies by either applying webpack by hand, or by writing some automation, and both ways that takes deep knowledge of npm, webpack, and scala.js intricacies.

It would be nice if mill handled this by default.

**Comment by lihaoyi** [comment]
Feel free to send a PR adding such a module to `contrib/`!

**Comment by crimzie** [comment]
👌

**Comment by MarkusA380** [comment]
For anyone coming from Google, error messages like:

```scalajsenv.js:26 Uncaught ReferenceError: exports is not defined```

are related to this. Once the PR is completed these issues [should be resolved].(https://github.com/scalacenter/scalajs-bundler/issues/193#issuecomment-352534260).

**Comment by lefou** [comment]
The related PR #410 which has unresolved review comments was closed due to inactivity.

Is anyone working on this right now or has some working solution to share?

**Comment by nafg** [comment]
I posted a gist there of what I got working within a project of mine. I think it works correctly but I haven't tested it heavily. I'll post it here as well:

https://gist.github.com/nafg/edb39f43daf2cd7ca8300b4252ace709

**Comment by nafg** [comment]
Another option: https://github.com/iterative-works/mill-webpack

**Comment by lefou** [comment]
> Another option: https://github.com/iterative-works/mill-webpack

Looks unmaintained to me. Last commit is from May 2020 and it's still using Mill 0.6.x. A lot has changing is Scala.js land since then.

**Comment by lolgab** [comment]
There is https://github.com/nafg/mill-bundler which solves this very problem.
I think this issue can be closed.

**Comment by lefou** [comment]
https://mill-build.com/mill/Thirdparty_Plugins.html#_bundler
