### ISSUE TITLE
Issue template refers to expired Discord link

### ISSUE THREAD

**Issue by asarkar** [com-lihaoyi/mill#4101]
Please don't open issues for questions, but ask in our Discussions forum at https://github.com/com-lihaoyi/mill/discussions or Discord channel at https://discord.gg/xJCYRVMS

Mill installations via `coursier` or `cs` are unsupported.

**Comment by lihaoyi** [comment]
Updated it to remove the discord link; Github discussions should be enough

**Comment by lihaoyi** [comment]
thanks for the report!
