### ISSUE TITLE
Document the system design and components

### ISSUE THREAD

**Issue by asarkar** [com-lihaoyi/mill#4114]
The mill documentation is mainly from a user's point-of-view, i.e. how to use the tool. I'd like to see a breakdown of the design that is now all in the maintainers' heads in the form of tribal knowledge. For example, what are the main concepts/classes like `T`, `Task`, etc., how are these related, what are the build components and their relationships, especially now that multi-file builds are supported. For example, here's an example of [Gradle Build Lifecycle](https://docs.gradle.org/current/userguide/build_lifecycle.html). There's also Gradle API for developers.

Having such documentation would tremendously encourage people to make new contributions, since they would have a place to start, and not have to drudge through the codebase just to make simple changes.

I hope the ticket makes sense; let me know if you need more clarification/information.

**Comment by lihaoyi** [comment]
https://mill-build.org/mill/main-branch/depth/evaluation-model.html and https://mill-build.org/mill/main-branch/depth/design-principles.html are meant to cover these topics, but they can definitely be fleshed out. Will leave this ticket open until I have time to give that part of the docs an overhaul

**Comment by lihaoyi** [comment]
Here's another page https://mill-build.org/mill/main-branch/depth/process-architecture.html
