### ISSUE TITLE
Importing projects fails on VSCode and IntelliJ on Windows

### ISSUE THREAD

**Issue by UtilFunction** [com-lihaoyi/mill#4161]
**Steps to reproduce:**

1. Download [sample project](https://github.com/com-lihaoyi/mill/releases/download/0.12.4/0.12.4-example-scalalib-basic-1-simple.zip)
2. Import on IntelliJ or VSCode

IntelliJ Error:
```
Executing C:\Users\user\project\sc\mill.bat -i mill.bsp.BSP/install
 
                                                                                 
	at io.github.alexarchambault.windowsansi.WindowsAnsi.setup(WindowsAnsi.java:34)
	at mill.runner.MillMain$.$anonfun$main$1(MillMain.scala:72)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at mill.api.SystemStreams$.withTopLevelSystemStreamProxy(SystemStreams.scala:125)
	at mill.runner.MillMain$.main(MillMain.scala:41)
	at mill.runner.MillMain.main(MillMain.scala)
```

VSCode Error:
```
2024.12.18 08:58:45 ERROR Mill command failed: C:\Users\user\project\sc\.metals\millw.bat -i --import ivy:com.lihaoyi::mill-contrib-bloop: mill.contrib.bloop.Bloop/install
2024.12.18 08:58:52 INFO  running 'C:\Users\user\project\sc\.metals\millw.bat -i --import ivy:com.lihaoyi::mill-contrib-bloop: mill.contrib.bloop.Bloop/install'
2024.12.18 08:58:53 INFO  Exception in thread "main" java.io.IOException: Failed to get console mode: D e r   V o r g a n g   w u r d e   e r f o l g r e i c h   b e e n d e t . 
2024.12.18 08:58:53 INFO   
2024.12.18 08:58:53 INFO                                                                                   
2024.12.18 08:58:53 INFO  	at io.github.alexarchambault.windowsansi.WindowsAnsi.setup(WindowsAnsi.java:34)
2024.12.18 08:58:53 INFO  	at mill.runner.MillMain$.$anonfun$main$1(MillMain.scala:72)
2024.12.18 08:58:53 INFO  	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
2024.12.18 08:58:53 INFO  	at mill.api.SystemStreams$.withTopLevelSystemStreamProxy(SystemStreams.scala:125)
2024.12.18 08:58:53 INFO  	at mill.runner.MillMain$.main(MillMain.scala:41)
2024.12.18 08:58:53 INFO  	at mill.runner.MillMain.main(MillMain.scala)
2024.12.18 08:58:52 INFO  time: ran 'mill bloopInstall' in 0.53s
2024.12.18 08:58:53 ERROR Mill command failed: C:\Users\user\project\sc\.metals\millw.bat -i --import ivy:com.lihaoyi::mill-contrib-bloop: mill.contrib.bloop.Bloop/install
```

Windows 11 24H2
OpenJDK 23.0.1
Metals 1.44.0
IntelliJ 2024.3 (Scala Plugin ver. 2024.3.574)
Mill 0.12.4

**Comment by lihaoyi** [comment]
@UtilFunction are you on ARM windows? I wonder if it's related to https://github.com/com-lihaoyi/mill/issues/4055

**Comment by UtilFunction** [comment]
@lihaoyi strangely it works if I set the absolute path in the VSCode Metals settings and point it to `"C:\Users\user\project\sc\.metals\millw.bat"`

**Comment by lihaoyi** [comment]
@UtilFunction that's a bit unusual, i thought i merged millw.bat into mill.bat recently, so they should be the same. Could you compare both files and see if they are indeed the same?

**Comment by UtilFunction** [comment]
@lihaoyi this is the only difference between the files:
![Code_0VHOTTyotc](https://github.com/user-attachments/assets/e1738fc8-bf20-411e-9a1a-4c2b9dcc3ccb)

**Comment by lihaoyi** [comment]
@UtilFunction got it, looks like it's the same then. I don't have my windows laptop with me now but I can try next time I have it

**Comment by alexarchambault** [comment]
Maybe that error could be silently trapped, or reported, but then ignored by Mill. That call is meant to enable ANSI output in windows terminals. It's only a nice-to-have, it doesn't need to make Mill crash.

**Comment by UtilFunction** [comment]
Update:
It seems to work with JDK 21.0.5+11 but not with 23.0.1+11.

**Comment by nartamonov** [comment]
I have the same problem. It only occurs when importing BSP project by IntelliJ IDEA. Current workaround: create file `.mill-jvm-opts` in the project root with the following content:

```
-Djdk.console=java.base
```

It seems to me that this is a bug in the [alexarchambault/windows-ansi](https://github.com/alexarchambault/windows-ansi) library, which is not compatible with the latest changes in JDK. In particular, JDK has [changed](https://inside.java/2023/07/31/quality-heads-up/) the behavior of the method `System.console()`:

> In JDK 22, System.console() has been changed to return a Console with enhanced editing features that improve the experience of programs that use the Console API. In addition, System.console() now returns a Console object when the standard streams are redirected or connected to a virtual terminal. Prior to JDK 22, System.console() instead returned null for these cases. This change may impact code that checks the return from System.console() to test if the JVM is connected to a terminal. **If required, the -Djdk.console=java.base flag will restore the old behavior** where the console is only returned when it is connected to a terminal. Starting JDK 22, one could also use the new Console.isTerminal() method to test if the console is connected to a terminal.

**Comment by alexarchambault** [comment]
Got to take `System.console()` change into account in all my apps (and some libraries) basically
