### ISSUE TITLE
Share build cache between mill and mill --repl

### ISSUE THREAD

**Issue by smarter** [com-lihaoyi/mill#417]
In the mill build, if I run `mill main.compile` in a clean state I get:
```scala
Compiling (synthetic)/ammonite/predef/interpBridge.sc
Compiling /home/smarter/opt/mill/ci/shared.sc
Compiling /home/smarter/opt/mill/ci/upload.sc
Compiling /home/smarter/opt/mill/build.sc
```

And when I subsequently run `mill -i` I get:
```scala
Compiling (synthetic)/ammonite/predef/replBridge.sc
Compiling (synthetic)/ammonite/predef/DefaultPredef.sc
Compiling /home/smarter/opt/mill/ci/shared.sc
Compiling /home/smarter/opt/mill/ci/upload.sc
Compiling /home/smarter/opt/mill/build.sc
```

It should be possible to reuse the compilation output of the common compiled files, according to @lihaoyi on Gitter:

> it just currently uses a different codepath for repl mode that would need to be unified with non-repl

**Comment by lefou** [comment]
We plan to remove `--repl` mode, so it's rather unlikely we will implement this.
