### ISSUE TITLE
environment variables on `repl` command.

### ISSUE THREAD

**Issue by vic** [com-lihaoyi/mill#424]
The `repl` command should be able to use `forkEnv` or similar to send environment variables to the interactive subprocess.

I noticed the code for repl is actually ready for this, it's just currently not sending any `envArgs`.

At the moment I'm overriding it on my project with something like: 

```scala

  override def repl(replOptions: String*) = T.command{
    if (T.ctx().log.inStream == DummyInputStream){
      Result.Failure("repl needs to be run with the -i/--interactive flag")
    } else {
      Jvm.interactiveSubprocess(
        mainClass = "ammonite.Main",
        classPath = ammoniteReplClasspath().map(_.path),
        mainArgs = replOptions,
        workingDir = pwd,
        envArgs = forkEnv.toMap[String,String]   /// <---- currently no envArgs is sent to the process
      )
      Result.Success()
    }
  }
```

Does it make sense to use `forkEnv` ? 

I'd be happy to work on a patch for this if this looks like desirable.

**Comment by lihaoyi** [comment]
sure it makes sense, send a pr

**Comment by lihaoyi** [comment]
This appears to be fixed by https://github.com/com-lihaoyi/mill/pull/1209
