### ISSUE TITLE
modules not defined on `mill -i` when using multiple compilation units on build.sc.

### ISSUE THREAD

**Issue by vic** [com-lihaoyi/mill#431]
Running `mill -i` should let you autocomplete and be able to invoke tasks on your project modules. This however only seems to work on the first compilation unit inside the the `build.sc` file.

For example, having the following build.sc file:

```scala
import mill._
object bar extends Module

@

import mill._
object foo extends Module
```

and then when running `mill -i`, `bar` is available but `foo` is not. I think either both should be available or at least the modules from the last compilation unit (ie, foo). 

My primary use case is I've been adding some built time dependencies on the first compilation unit and actually define my project modules on the second, like:

```scala
// adding some repos and ivy dependencies that define new module types for the build itself (eg, docker, scalaxb), eg: 
// class FooModule extends Module {}
@
// define project modules
// object foo extends FooModule
```

Is this something that makes sense to fix? If so, I'd be happy to digg a bit on the code and discuss implementation.

**Comment by lihaoyi** [comment]
This is moot since https://github.com/com-lihaoyi/mill/pull/2377 remove the ability to have multiple compilation units in a single build.sc
