### ISSUE TITLE
Should T.sources enforce uniqueness?

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#432]
Currently it's defined as

```scala
class Sources(t: Task[Seq[PathRef]],
              ctx0: mill.define.Ctx) extends Input[Seq[PathRef]
```

We could remove duplicates automatically by changing it to `extends Input[Loose.Agg[PathRef]`, or blow up on duplicate values via `extends Input[Strict.Agg[PathRef]`.

One of these seems like a reasonable way to enforce the uniqueness constraint; I don't think anyone needs duplicate source paths in their sources list, and if they really-truly need it they can always fall back to `T.input`

This is the root cause of https://github.com/lihaoyi/mill/issues/430

**Comment by lefou** [comment]
If we do that, we should make it automatically, as the way it can be used (involving inherited `super`-calls) may make it quite cumbersome and boilerplate-y to ensure uniqueness.

**Comment by lefou** [comment]
Changing `Sources` to extend `Input[Loose.Agg[PathRef]]` sounds reasonable to me.

**Comment by lihaoyi** [comment]
I think the conclusion is probably not since I'm planning on getting rid of `Agg` in 0.13.0 (and leaving it as an alias for `Seq` for compatibility)
