### ISSUE TITLE
feature request/discussion: add war file assembly support

### ISSUE THREAD

**Issue by bbarker** [com-lihaoyi/mill#447]
Unless my grepping failed me, it doesn't appear to be supported. This isn't something I immediately need, but would be good to have at some point. Perhaps code from sbt can be ported?

**Comment by nightscape** [comment]
There was a PR for it, the original author mentioned that there will be a new PR:
https://github.com/lihaoyi/mill/pull/321

**Comment by benjaminfrank** [comment]
yes, I have a working student that created code for war files and distzip but I will needs to go over the code before I can open a proper PR here.
I hope I will be able to do it this weekend

**Comment by lihaoyi** [comment]
Given there's no immediate need, let's close this issue and move discussion to gitter

**Comment by lefou** [comment]
Some kind of duplicate to #321
