### ISSUE TITLE
Make Cross modules work with traits rather than classes

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#465]
Currently, `Cross` modules are the only place where you must define a module as a class. This is confusing, as everywhere else you *must* use traits, and also verbose since you need the boilerplate `(val crossScalaVersion: String)` everywhere.

We should be able to make the macro smart enough to let us define cross modules as traits, by having the macro fill in the `crossScalaVersion` abstract `def` rather than just passing in a constructor param

**Comment by lefou** [comment]
This has the issue that the holder (`crossScalaVersion`) of the cross parameter is fixed. And would collide with most use cases in which more than one cross axis is involved. Also it may transport the wrong meaning if the module is not a cross scala module.

**Comment by lihaoyi** [comment]
Fixed by https://github.com/com-lihaoyi/mill/pull/2427
