### ISSUE TITLE
Add setting to temporarily disable checksums

### ISSUE THREAD

**Issue by smourapina** [com-lihaoyi/mill#493]
When the published checksum (sha1 or md5 hash) for a repository is different from the checksum computed for a downloaded artifact (jar or pom.xml) there is an error like `checksum format error`.

In this instance, and as a temporary workaround, it would be good to have the possibility to allow disabling the checksums done by Coursier. 

`sbt` has this feature (`checksums in update := Nil`).

**Comment by lefou** [comment]
This is probably a feature we don't want to implement.
