### ISSUE TITLE
Make `mill inspect` work on commands without arguments provided

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#503]
This currently doesn't work:
```scala
lihaoyi mill$ mill inspect path
[1/1] inspect
1 targets failed
inspect Missing arguments: (--src: String, --dest: String)

Arguments provided did not match expected signature:

path
  --evaluator  mill.eval.Evaluator
  --src        String
  --dest       String

```

Even without arguments, it should be possible to provide the some subset of the inspect metadata (e.g. filename, line number, description).

**Comment by lefou** [comment]
In addition, an automatic help/usage should be rendered from the accepted command arguments
