### ISSUE TITLE
Hyphens in task names and argument names

### ISSUE THREAD

**Issue by saksmt** [com-lihaoyi/mill#521]
#166 for unclear reasons was only about module names, but not about task names and/or argument names for commands. Sample code:

```scala
def `task-with-hyphen`() = T.command(())
def task(`with-hyphen-in-args`: String) = T.command(())
```

Actually arguments concern me a lot more than tasks since it is really more useful, for ex. it is reasonable to have task `release` with option `--dry-run` to ensure that all checks pass before actually making release.

**Comment by jkstrauss** [comment]
I tried making a task with hyphens, and I had no problem. Arguments looks like something that is failing right now, but could be remedied.

**Comment by lihaoyi** [comment]
Should be fixed by https://github.com/com-lihaoyi/mainargs/pull/13 when we pull the new version of mainargs into Mill

**Comment by lefou** [comment]
Reopened, as we haven't not yet switched to that version.

**Comment by lihaoyi** [comment]
This is now fixed in `main`
```
lihaoyi mill$ ./mill -i dev.run scratch resolve _
[90/647] de.tobiasroeser.mill.vcs.version.VcsVersion.vcsState
[156/647] main.core.compile
[info] compiling 1 Scala source to /Users/lihaoyi/Github/mill/out/main/core/compile/dest/classes ...
[info] done compiling
[647/647] dev.run
Compiling /Users/lihaoyi/Github/mill/scratch/build.sc
[1/1] resolve
all
bar-baz
clean
foo
inspect
par
path
plan
resolve
show
shutdown
shutdown
version
version
visualize
visualizePlan
lihaoyi mill$ ./mill -i dev.run scratch -w bar-baz --qux- 123
[90/647] de.tobiasroeser.mill.vcs.version.VcsVersion.vcsState
[647/647] dev.run
[1/1] bar-baz
123
Watching for changes to 2 paths... (Ctrl-C to exit)
```
