### ISSUE TITLE
JavaModule.assembly produces invalid or corrupt jar file (was: publishLocal as altenative to jars : which are corrupt often and at random)

### ISSUE THREAD

**Issue by siddhartha-gadgil** [com-lihaoyi/mill#528]
I am getting a lot of corrupt jars, even though I have cleared/checked everything in sight several times. This happens to fat jars in sbt too, but there we have the alternative (for use in Jupyter, for example) of publishLocal. Can _mill_ provide such an option?

**Comment by lihaoyi** [comment]
Mill already supports `.publishLocal`

**Comment by lefou** [comment]
@siddhartha-gadgil So, what exactly is your issue? What is corrupt? And how did this happen?

**Comment by siddhartha-gadgil** [comment]
Firstly, I have set up _publishLocal_ and this is working fine for the case
I needed now (Jupyter Notebooks with Almond). In my work desktop, but not
my home laptop, the output of assembly was corrupted for some modules. This
meant that executable binaries would crash with "mainClass ... not found"
and if I loaded in ammonite using `import $cp.myjar` subsequent commands
would not find the contents. I found online that I should try `jar tf`, and
this indeed confirmed cooruption.

Presumably some source/doc jar of a dependency is corrupted, causing the
upstream corruption. In fact it would be best for me to have a thinFat jar
for running, excluding the sources and docs (especially of dependencies).
Is that already an option?

**Comment by lefou** [comment]
To be honest, I have no clue what you wanna tell us. It would be helpful to be more concrete. E.g. the exact mill cmdline you used when mill crashed. The exact error message.If possible, the `build.sc`...

Looks like you should better ask on https://gitter.im/lihaoyi/mill.

**Comment by siddhartha-gadgil** [comment]
I did not mean that _mill_ crashes, but that the _executable jar_ generated by `mill myproject.assembly` crashes, and in a random and hard to diagnose (at least for me) way. The reason is almost certainly some cached corrupt jar, and probably a source/documentation jar.

* My main request was to `publishLocal`, as an alternative, which @lihaoyi pointed out is already part of mill.
* A feature that would be nice is a _minimal fat-jar_, i.e. excluding source and documentation dependencies, so reducing the chance of corrupt jars fouling this up.
* Even better would be better diagnostics while building jars, though this may not be a mill issue.

**Comment by lihaoyi** [comment]
@siddhartha-gadgil do you happen to be using Mill concurrently? Mill doesn't have proper concurrency control, so while concurrent usually works, if tasks happen to overlap in what they are doing things blow up in odd ways.

If you want diagnostics while building jars, feel free to build the jars yourself by copy-pasting the Mill code into your build.sc and add whatever diagnostics you'd like.

**Comment by siddhartha-gadgil** [comment]
Quite possibly that is happening. But the main problem is probably a giant dependency on the Stanford Parser (coupled with not great internet) - random bits get corrupted in the cache, and any piece corrupted seems to make the jar unusable.

I'll try manually building by copy-pasting, with checks thrown in for corrupt jars.

**Comment by lihaoyi** [comment]
@siddhartha-gadgil internet-related issues with upstream dependencies, those issues *should* be persistent until you clean your coursier cache in `~/.coursier`. If you are seeing things behave nondeterministically without clearing that cache, it is unlikely to be internet related.

Also, if you think things are being corrupted while building jars, use `mill inspect` and `mill show` to trawl the dependency graph of your task that created the corrupted jar and look at the input jars/folders to see if they contain what you expect. This might help you narrow down the corrupted jar to the actual culprit doing the corruption

**Comment by siddhartha-gadgil** [comment]
It is not non-deterministic - I have a natural experiment because of two work systems, and I meant built on one and not on the other. I also meant changes when some dependencies change. I have tried trawling and resetting, but it is not easy manually at least on large scale.

For example, today  I used _publishLocal_, got a crash in ammonite, deleting the corresponding coursier file and re-published to fix the error. But without the pointer from running (or some other script-based way) it would not be practical to find which dependency is corrupt.

**Comment by siddhartha-gadgil** [comment]
This may actually be a mill issue, but I will get more data and report. I
generated a list in mill of the _upstreamAssemblyClasspath_, and checked
that "jar tf _" loaded successfully in each of them.  However the same
command on the output gives "java.util.zip.ZipException: invalid END header
(bad central directory size)"

**Comment by siddhartha-gadgil** [comment]
Sorry for the probably wrong report. Looks by searching that the sheer size
may be the issue (over 65k files) because of the large dependency. I
confirmed that unzip worked fine.

**Comment by lefou** [comment]
FYI, it looks like the `assembly` target has an issue with very large assemblies and an non-empty `prependShellScript`. Here is a  workaround:

```scala
override def prependShellScript: T[String] = ""
```

**Comment by lefou** [comment]
So, I think we should create a test case that reproduced this issue and then fix it. After a first glace at the code I think it could be, a proper fix will need to go to os-lib.

**Comment by lefou** [comment]
I recently fixed some issues left open file handles in assembly processing (which constantly failed windows tests). There is a minimal chance this issue just vanishes after hat fix. it would be nice, If someone could report if this issue is still present with mill >= `0.9.7-9-848292`.

**Comment by lefou** [comment]
This is probably fixed?

**Comment by lefou** [comment]
Please reopen or comment if you find this issue is still valid!

**Comment by lefou** [comment]
This issue is still present. See #2650 for a reproduction.

**Comment by abbadmus** [comment]
why do i keep getting this error

jar tf out/app/assembly.dest/out.jar

java.util.zip.ZipException: invalid CEN header (bad signature)
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1827)
        at java.base/java.util.zip.ZipFile$Source.checkAndAddEntry(ZipFile.java:1211)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1766)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1541)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1504)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:724)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:251)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:180)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:151)
        at jdk.jartool/sun.tools.jar.Main.list(Main.java:1527)
        at jdk.jartool/sun.tools.jar.Main.run(Main.java:367)
        at jdk.jartool/sun.tools.jar.Main.main(Main.java:1708)

**Comment by lefou** [comment]
> why do i keep getting this error

You probably have a too large assembly and hit an issue with the JVM/JDK. Latest Mill snapshots and the upcoming version `0.11.8` will detect this and recommend a fix.

In the meantime, just use the workaround from https://github.com/com-lihaoyi/mill/issues/528#issuecomment-768965337.
