### ISSUE TITLE
Tasks overridden in multiple traits are not cached

### ISSUE THREAD

**Issue by jeantil** [com-lihaoyi/mill#554]
I think this may be related to #86 

Consider the following build :
```scala
trait A extends JavaModule{
  def aSources = T.sources{millSourcePath / 'a}
  def aOutput = T{aSources()}
  override def generatedSources = T{ super.generatedSources() ++  aOutput() }
}

trait B extends JavaModule{
  def bSources = T.sources{millSourcePath / 'b}
  def bOutput = T{bSources()}

  override def generatedSources = T{ super.generatedSources() ++  bOutput() }
}
object core extends A with B{
  def ok = T{
    aOutput() ++ bOutput()
  }
}
```

running `mill core.ok` twice yields the following `mill-profile.json`
```json
[
    {
        "label": "core.aSources",
        "millis": 2,
        "cached": false
    },
    {
        "label": "core.aOutput",
        "millis": 0,
        "cached": true
    },
    {
        "label": "core.bSources",
        "millis": 2,
        "cached": false
    },
    {
        "label": "core.bOutput",
        "millis": 1,
        "cached": true
    },
    {
        "label": "core.ok",
        "millis": 0,
        "cached": true
    }
]
```
as expected both `T.source`'s are reevaluated but everything else is cached. 

However running `mill core.generatedSources` yields : 
```json
[
    {
        "label": "core.generatedSources.overriden.mill.scalalib.JavaModule.generatedSources",
        "millis": 0,
        "cached": true
    },
    {
        "label": "core.aSources",
        "millis": 2,
        "cached": false
    },
    {
        "label": "core.aOutput",
        "millis": 1,
        "cached": true
    },
    {
        "label": "core.generatedSources",
        "millis": 2,
        "cached": false
    },
    {
        "label": "core.bSources",
        "millis": 2,
        "cached": false
    },
    {
        "label": "core.bOutput",
        "millis": 0,
        "cached": true
    },
    {
        "label": "core.generatedSources",
        "millis": 2,
        "cached": false
    }
]
```
Here the `core.generatedSources` task appears twice, neither of which is cached 

I would expect:
- the first occurrence to be labeled `core.generatedSources.overriden.A.generatedSources`), and to be cached.
- the second occurrence to be the actual `core.generatedSources` and to also be cached

Inspecting the task `core.generatedSources` yields : 
```
/Users/jean/mill-release inspect core.generatedSources
[1/1] inspect
core.generatedSources(build.sc:14)
    Folders containing source files that are generated rather than
    hand-written; these files can be generated in this target itself,
    or can refer to files generated from other targets

Inputs:
    core.aOutput
    core.bOutput
```

The above profile shows that both aOutput and bOutput were cached. So is  `core.generatedSources.overriden.mill.scalalib.JavaModule.generatedSources` which is evaluated but not identified in the inspect output.

Removing either trait from the object definition returns to an expected behavior such as this: 
```json
[
    {
        "label": "core.generatedSources.overriden.mill.scalalib.JavaModule.generatedSources",
        "millis": 1,
        "cached": true
    },
    {
        "label": "core.aSources",
        "millis": 2,
        "cached": false
    },
    {
        "label": "core.aOutput",
        "millis": 0,
        "cached": true
    },
    {
        "label": "core.generatedSources",
        "millis": 1,
        "cached": true
    }
]
```

**Comment by lefou** [comment]
Is this still valid?

**Comment by lihaoyi** [comment]
This can be minimized as follows:

```scala
import mill._

trait X extends Module{
  def f = T{ 1 }
}
trait A extends X{
  override def f = T{ super.f() +  2 }
}

trait B extends X{
  override def f = T{ super.f() + 3 }
}
object m extends A with B
```

`mill m.f` generates the following profile:

```json
[
    {
        "label": "m.f.overriden.ammonite.$file.build.X.f",
        "millis": 19,
        "cached": true
    },
    {
        "label": "m.f",
        "millis": 15,
        "cached": false
    },
    {
        "label": "m.f",
        "millis": 4,
        "cached": false
    }
]
```

The issue here is that our detection of overrides is wonky; we correctly notice that `X#f` is overriden, and thus give it a long prefixed path, but do not recognize that `A#f` is overriden while `B#f` is not. Thus `A#f` and `B#f` are both given unprefixed paths `m.f`, and because they are then given the same place on disk to store their metadata, they'll keep stomping over each other back and forth and never get cached.

I don't know exactly what the solution to fix the override detection is yet

**Comment by lefou** [comment]
Am I assuming right, that we should be technically able to differentiate between those overridden tasks and assign them different `dest` paths?

**Comment by lihaoyi** [comment]
Here's a possible fix https://github.com/com-lihaoyi/mill/pull/1600

**Comment by lefou** [comment]
Great @lihaoyi . I'll have a look (later). Ideally, we find an encoding, which is stable, even when we edit the `build.sc`. So that the dest path doesn't change depending on the amount of additional traits stacked in.

**Comment by lihaoyi** [comment]
@lefou the current encoding is already like that I believe; each overridden method gets a static path, which is basically the normal path suffixed by `overriden/my/pkg/path/MyClassName`. The only bug in this case was that detecting whether a method was overridden or not was broken, but the disk path we put the things is fine

The one time a targets path may change is when it gets overridden, and is no longer the "final" version of a target. However that's probably unavoidable as long as we want to provide a "nice" filesystem path for the common case of accessing the final version of a target
