### ISSUE TITLE
Exclude Scala from assembly JAR file

### ISSUE THREAD

**Issue by MrPowers** [com-lihaoyi/mill#575]
SBT lets you exclude Scala from `sbt assembly` JAR files by adding this line to your `build.sbt` file:

```scala
assemblyOption in assembly := (assemblyOption in assembly).value.copy(includeScala = false)
```

How can Scala be excluded from Mill assembly JAR files (JAR files generated with `mill foo.assembly`).

**Comment by nvander1** [comment]
I think you can do the following (untested):

```scala
import mill._
import mill.scalalib._
import mill.modules.Assembly
import mill.modules.Assmebly.Rule.ExcludePattern

object foo extends ScalaModule {
  def assemblyRules = Assembly.defaultRules ++ Seq(ExcludePattern("scala*"))
}
```

**Comment by andres-pipicello-olx** [comment]
it doesn't work when the scala library is a transitive dependency:

```scala
// build.sc
import mill._
import mill.api.Loose
import mill.define.Target
import mill.scalalib._

object foo extends ScalaModule {
  def scalaVersion = "2.12.4"

  def scalaLibraryIvyDeps = T { Agg.empty }

  override def ivyDeps: Target[Loose.Agg[Dep]] = T{ Agg(ivy"org.scalaz::scalaz-core:7.2.21") }
}
```

```sh
$ mill show foo.upstreamAssemblyClasspath
[1/1] show
[
    "qref:494767f2:/Users/andres/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scalaz/scalaz-core_2.12/7.2.21/scalaz-core_2.12-7.2.21.jar",
    "qref:c6cc657e:/Users/andres/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4.jar"
]
```

**Comment by nvander1** [comment]
I haven't tested this but I think it should work (it's essentially what sbt does)
```scala
import mill._
import mill.scalalib._
import mill.modules.Assembly
import mill.modules.Assmebly.Rule.ExcludePattern

 val scalaLibPatterns = Vector("scala-actors",
      "scala-compiler",
      "scala-continuations",
      "scala-library",
      "scala-parser-combinators",
      "scala-reflect",
      "scala-swing",
      "scala-xml")

  val pattern = scalaLibPatterns.mkString("(", "|", ")") + ".*"

object foo extends ScalaModule {
  def assemblyRules = Assembly.defaultRules ++ Seq(ExcludePattern(pattern))
}
```

Patterns in sbt:
https://github.com/sbt/sbt-assembly/blob/08a3fc3aa0279bed3188ba73f343f5cafa8589ce/src/main/scala/sbtassembly/Assembly.scala#L175
https://github.com/sbt/sbt-assembly/blob/08a3fc3aa0279bed3188ba73f343f5cafa8589ce/src/main/scala/sbtassembly/Assembly.scala#L281

**Comment by andres-pipicello-olx** [comment]
AFAIK, mill `ExcludePattern`s work at the classpath level, not at the dependency level

**Comment by nvander1** [comment]
In that case, are there any classes in the scala libraries that won't match the pattern `scala.*` ?

**Comment by nvander1** [comment]
Here is a more comprehensive example:
```scala
// build.sc
import mill._
import mill.api.Loose
import mill.define.Target
import mill.scalalib._
import mill.modules.Assembly.Rule.ExcludePattern
import mill.modules.Assembly

object foo extends ScalaModule {
  def scalaVersion = "2.11.8"

  def scalaLibraryIvyDeps = T { Agg.empty }

  def assemblyRules = Assembly.defaultRules ++ Seq(ExcludePattern("scala/.*"))

   val scalaLibPatterns = Vector(
      "scala-actors",
      "scala-compiler",
      "scala-library",
      "scala-parser-combinators",
      "scala-reflect",
      "scala-swing",
      "scala-xml")

  override def ivyDeps: Target[Loose.Agg[Dep]] = T{
    Agg(scalaLibPatterns.map(x => ivy"org.scala-lang:${x}:2.11.0-M4"):_*) ++
    Agg(ivy"org.scala-lang.plugins:scala-continuations-library_2.11:1.0.3") ++
    Agg(ivy"org.scalaz::scalaz-core:7.2.21")
  }
}
```

`jar -tf out/foo/assembly/dest/out.jar | grep scala/` is empty

**Comment by MrPowers** [comment]
@nvander1 @andres-pipicello-olx - thanks for the responses.

I just messed around with this for about an hour and confused myself.  Once we figure this out, I am going to publish a blog on how to use Mill for Spark projects, so the work we're doing will hopefully help shift the Spark community from SBT to Mill.  I'm excited to help move the community in a good direction!

Let's use this [mill_spark_example](https://github.com/mrpowers/mill_spark_example/) repo, so we're all on the same page with how to run the code snippets.  

When I run `mill foo.assembly`, I'd like a JAR file that includes spark-daria and all the project files, but that's it (I don't want the assembly JAR file to include Spark or Scala).  

I think the `scalaLibraryIvyDeps`, `ivyDeps`, and `compileIvyDeps` are all related - I'm still struggling to figure out how.

If you could submit a pull request on the mill_spark_example repo, that'd be ideal.  I'm also fine to just keep trying different combinations of code snippets in the repo myself until we figure it out!

I just tried to figure this out for a while and got nowhere.  Thanks for the help!

**Comment by MrPowers** [comment]
Here's the work-in-progress blog post by the way: https://www.mungingdata.com/apache-spark/mill-build-tool

I will officially publish the blog post after figuring out how to properly generate the assembly JAR file and a couple of other little bugs 😄

**Comment by nvander1** [comment]
@MrPowers This does what you want I believe: https://github.com/MrPowers/mill_spark_example/pull/6

**Comment by nvander1** [comment]
This confused me at first too coming from sbt:

If you have this in sbt:
```scala
libraryDependencies ++= Seq("org.apache.spark" %% "spark-sql" % "2.4.0" % "provided")

**Comment by nvander1** [comment]
@MrPowers Note that on this PR: https://github.com/MrPowers/mill_spark_example/pull/6 You could also omit the spark pattern in the assembly rules and it will produce the expected jar still. But like @andres-pipicello-olx  pointed out for the scala lib, I don't think it will cover transitive spark deps. We should experiment with that to be sure

**Comment by nvander1** [comment]
@andres-pipicello-olx do you know if that transitive dep issue applies only to the scala-library or if it is for any dependency? If it applies to any dependency, I'd imagine that would need to be addressed.

**Comment by MrPowers** [comment]
@nvander1 - Thank you so much for the help!!!  Your PR solves almost all of my issues.

Kind of shockingly, it looks like `com/github/mrpowers/spark/fast/tests/*` is included in the assembly JAR file?  I guess this part of the `build.sc` file needs to be modified as well?

```scala
object test extends Tests{
  def ivyDeps = Agg(
    ivy"org.apache.spark::spark-sql:2.3.0",
    ivy"com.lihaoyi::utest:0.6.0",
    ivy"MrPowers:spark-fast-tests:0.17.1-s_2.11",
    ivy"mrpowers:spark-daria:0.26.1-s_2.11",
  )
  def testFrameworks = Seq("utest.runner.Framework")
}
```

**Comment by nvander1** [comment]
Happy to help! Before we go too far down a rabbit hole @lefou @lihaoyi do you all have any insights into this?

**Comment by andres-pipicello-olx** [comment]
@nvander1 honoring provided scope in transitive dependencies seem to work fine. Sadly, the exclude rules you defined in https://github.com/MrPowers/mill_spark_example/pull/6 don't work because some spark libraries like to have classes in the `org.apache.spark` package :S

@MrPowers I am in the same predicament, making mill work right with spark. 

The main problem is that libraries have no consistency on how they depend on spark and on scala- library(so it is not really a mill problem). Some libraries include spark as a provided dependency(e.g. spark-cassandra-connector), others as a compile dependency(e.g. spark-kinesis). 

In the first case, you are ok including them in `ivyDeps`, in the second case `compileIvyDeps` doesn't help you, as you need the root dependency on the classpath when running.

I have and ad-hoc solution in one of my projects (basically, overriding upstreamAssemblyClasspath and filtering the offending classpath entries) but I think it would make more sense to fix this at dependency-resolution-time

**Comment by nvander1** [comment]
You're right @andres-pipicello-olx, a simple pattern won't work here.

 Perhaps we implement a `trait SparkModule` with a default list of `def clusterProvidedDeps` (spark-core, spark-streaming, spark-sql, ...) `def extraClusterProvidedDeps` for non-standard deployments of spark that may have additional runtime deps included. Then the user would supply something like `spark-streaming-kinesis` as a normal `ivyDep`

@MrPowers

**Comment by nvander1** [comment]
I've added a more concrete implementation first draft of the SparkModule here: https://github.com/nvander1/mill-spark

**Comment by lefou** [comment]
Excluding files from assembly is covered by the documentation, https://com-lihaoyi.github.io/mill/mill/Configuring_Mill.html#_mergeexcluderelocate_files_from_assembly. If you feel there is need for a more detailed example, please open a PR and add the example.

@nvander1 You might want to add your plugin the the external plugins list: https://com-lihaoyi.github.io/mill/mill/Thirdparty_Plugins.html

**Comment by Renkai** [comment]
The document is missing from the newest, consider have an update?

**Comment by lefou** [comment]
Please don't request new things on already closed issues. Open a new issue instead.
