### ISSUE TITLE
Order of dependencies on `module.runClasspath` and generated Idea files differ

### ISSUE THREAD

**Issue by ghost** [com-lihaoyi/mill#583]
The order of the entries on the `.iml` files generated for modules have a different order than the order defined in the `JavaModule`'s properties.

For example, in `runClasspath` unamanged dependencies come before ivy deps, but entries on the module files do not necessarily follow this.

**Comment by andres-pipicello-olx** [comment]
Also, it seems that `runIvyDeps` is not being honored by the idea generator

**Comment by lefou** [comment]
Has IDEA an concept of runtime dependencies, or do we need to add them as ordinary compile-time dependencies?

**Comment by lefou** [comment]
Meanwhile, `runIvyDeps` are supported by `GenIdea`. #1110

**Comment by lefou** [comment]
Going to close this, as the order of classpath entries has been addressed multiple time meanwhile and work reasonable (IMHO). But there are conceptual differences between Mill classpaths and IDEA classpaths, which can't be resolved entirely. I think we have a good "local optimum".
