### ISSUE TITLE
Importing script files into build.sc behaves oddly

### ISSUE THREAD

**Issue by nrktkt** [com-lihaoyi/mill#586]
I have a project that pulls dependency declaration out into another file `Dependencies.sc`.
There are a handful of unexpected things preventing use of this setup.
1. Declaring 
    ```scala
    import $file.Dependencies
    import Dependencies._
    ```
    at the top of the `build.sc` causes modules to no longer compile
    > Modules, Targets and Commands can only be defined within a mill Module
    > object foo extends ScalaModule {
2. moving `import Dependencies._` into the module object allows the module to compile, but `Agg`s no longer automatically convert to a `Target` for assignment to `ivyDeps`
    > type mismatch;
 found   : mill.api.Loose.Agg[mill.scalalib.Dep]
 required: mill.define.Target[mill.api.Loose.Agg[mill.scalalib.Dep]]
  def ivyDeps = Agg(

3. explicitly wrapping `Aggs` in a `T` results in 
    > Modules, Targets and Commands can only be defined within a mill Module
    > def ivyDeps = T( Agg(

full files for reference
```scala
// build.sc
import mill._
import scalalib._
import $file.Dependencies
import Dependencies._

val scala12 = "2.12.7"

object foo extends ScalaModule {
  def scalaVersion = scala12
  def ivyDeps = Agg(scalatest)
}
```
```scala
// Dependencies.sc
import mill.scalalib._
val scalatest = ivy"org.scalatest::scalatest:3.0.7"
```

EDIT:
Wrapping top level `val`s in `Dependencies.sc` in an object seems to make things work more predictably (I can `import $file.Dependencies, Dependencies.deps._`). I'm not sure if this is because I'm not aware of file imports work in Ammonite, but it would be nice if the mill error messages along the way were more helpful.

**Comment by pedrohjordao** [comment]
I know this issue is quite old, but this has been causing some trouble for me. 

Especially since I'm trying to setup a more "modularized" project with many subfolders (similar to a monorepo) 

Having `Modules` defined  in files inside folders forces me to do stuff like

`import $file.subfolder.{build => SubfolderBuild}, SubfolderBuild.{A, Bunch, Of, Modules}`

having the import all syntax working would make my life a whole lot easier

**Comment by lihaoyi** [comment]
This appears to be fixed, presumably from https://github.com/com-lihaoyi/mill/pull/2377
