### ISSUE TITLE
Input tasks require JSON readable and writable output

### ISSUE THREAD

**Issue by kag0** [com-lihaoyi/mill#598]
I'm not sure what the intended behavior is, but the there's a little inconsistency between the documentation and the code for [input tasks](http://www.lihaoyi.com/mill/page/tasks.html#inputs).
The [task cheat sheet](http://www.lihaoyi.com/mill/page/tasks.html#cheat-sheet) confirms that inputs do not need to be JSON readable or JSON writable, however [`T.input`](https://github.com/lihaoyi/mill/blob/master/main/core/src/define/Task.scala#L153) requires an implicit upickle `ReadWriter` for the result type. 

steps to reproduce:
```scala
import mill._, scalalib._
import java.time.Instant

object baz extends JavaModule {
  def test = T.input(Instant.now)
}
```
Confirm the build does not compile due to 
> could not find implicit value for parameter rw: upickle.default.ReadWriter[java.time.Instant]

**Comment by lihaoyi** [comment]
Not sure how easy it would be to remove the `ReadWriter` dependency in `Input`, but one workaround could be to define a `ReadWriter` for `java.time.Instant`. Since it's in the standard library, perhaps even push it upstream to the uPickle repo

**Comment by kag0** [comment]
The workaround I'm currently using is 
```scala
def w[T] = writer[Unit].comap[T](_ => ())
def r[T] = reader[Unit].map[T](_ => ???)
def rw[T]: ReadWriter[T] = ReadWriter.join(r, w)
def task = T.input(...)(rw, implicitly[Ctx])
```

For two reasons
1. This works for any type, and as far as I can tell the actual JSON value is unused. 
2. Some of the values I want to use are sensitive (db credentials for the flyway plugin) and I don't want them written to disk unnecessarily. 

This second point could probably be expanded into a separate feature request except that the documented behavior of an input task already does pretty much what I want.
