### ISSUE TITLE
Mill is stuck on windows with no output

### ISSUE THREAD

**Issue by ColOfAbRiX** [com-lihaoyi/mill#646]
I've just downloaded the latest version 0.4.2 of mill on my Windows 10 machine. I followed the instructions to run it but there is no visual output and it seems stuck, no visual output, no interaction, nothing, just a blinking screen. Expectated result: any form of output, a version number, an error.

To troubleshoot I checked what command is run and I tried to run directly:
```
java -DMILL_CLASSPATH=mill-0.4.2 -DMILL_VERSION=0.4.2 -Djna.nosys=true -cp mill-0.4.2 mill.main.client.MillClientMain
```
but the result is the same, all stuck.

I performed these tests:

- Windows 10, java version Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
- Cygwin, same java executable as above
- Windows Subsystem for linux, java version Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

All with the same result, no output, program stuck

As additional test I also tried to run an older version and I picked randomly version 0.3.3 but same result

**Comment by lefou** [comment]
Can you please test with the additional `-i` option and report the result?

```
mill -i your.target
```

**Comment by ColOfAbRiX** [comment]
I'm now getting inconsistent behaviour. lt started to work on WSL using `-i`, then it started to work under windows *without* `-i` and it now works on Cygwin too, using `-i`.

The documentation says to use the `-i` option on WSL but doesn't say the criterias when the flag is useful. A clarification would be useful.

My ultimate goal is to use it from VSCode through the [metals](https://marketplace.visualstudio.com/items?itemName=scalameta.metals) plugins and there still doesn't work, no output and endless waiting. Is there any form of log I can enable or check?

**Comment by krotton** [comment]
I can confirm the same happens in 0.5.7 under WSL 1. It seems to be related to using `exec` in the launch script, as seemingly the WSL's implementation of `exec` is buggy. Under WSL 2 (where `exec` uses a native Linux kernel call) it works without any issues.

Anyway, calling with `-i` seems to actually fix it, so maybe that's worth including in some doc.

**Comment by lefou** [comment]
@krotton Thanks for the feedback.

@ColOfAbRiX I guess, you have to open an issue in the metals plugin project or ask in their support channel if you need help with that issue.

**Comment by lefou** [comment]
Related: #781

**Comment by sake92** [comment]
@ColOfAbRiX @krotton can you try with latest Mill? E.g. "0.6.1-121-3f10a4-assembly" 
Note that pipe still complains with "Failed to connect to server" on end..

**Comment by sake92** [comment]
Works on Windows, WSL and in GitBash too now!
https://github.com/com-lihaoyi/mill/pull/1230
