### ISSUE TITLE
Generalize `.runBackground` to work with all kinds of subprocesses

### ISSUE THREAD

**Issue by lihaoyi-databricks** [com-lihaoyi/mill#657]
Currently it's hardcoded to only work for the main method of Java/Scala modules, but it could be useful for running other sorts of long-running daemons too: webpack proxy, `docker run`, databases, etc.

We might need to replace the auto-shutdown thread with a auto-shutdown subprocess, since we'll be running non-JVM things

**Comment by lihaoyi** [comment]
Maybe could even make it a general-purpose wrapper that works with all kinds of Tasks as well

**Comment by lihaoyi** [comment]
We've hit the need for a non-JVM runBackground now that we're aiming to support Javascript https://github.com/com-lihaoyi/mill/pull/4022/files and Python https://github.com/com-lihaoyi/mill/issues/3928.

**Comment by himanshumahajan138** [comment]
@lihaoyi actually yesterday i was working on this same issue for web examples and i was mimicing the same code as we have for java/scala like having backgroundwrapper in .py extension and then run that file with all the necessary args.

I will pull a request for this in some time and i think untill we don't get general support we can go with this one

Your thoughts?

**Comment by lihaoyi** [comment]
@himanshumahajan138 I think it should be doable to generalize `MillBackgroundWrapper` to wrap a subprocess, lemme try and implement that
