### ISSUE TITLE
Variable in pom.xml not resolved

### ISSUE THREAD

**Issue by Dennis4b** [com-lihaoyi/mill#759]
I am trying to use an ivyDep (included via dependencies):
  com.helger / ph-jaxb-pom / 1.0.3

In its pom.xml file at
  https://github.com/phax/ph-jaxb-pom/blob/master/pom.xml

it has the following section near the bottom:
```
      <dependency>
        <groupId>org.glassfish.jaxb</groupId>
        <artifactId>jaxb-bom</artifactId>
        <version>${jaxb.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
```

which gives:

```
--------------------------------------------
  org.glassfish.jaxb:jaxb-bom:${jaxb.version} 
	not found: /home/dennis/.ivy2/local/org.glassfish.jaxb/jaxb-bom/${jaxb.version}/ivys/ivy.xml
	not found: https://repo1.maven.org/maven2/org/glassfish/jaxb/jaxb-bom/${jaxb.version}/jaxb-bom-${jaxb.version}.pom
	download error: Caught java.net.URISyntaxException: Illegal character in path at index 84: https://oss.sonatype.org/content/repositories/releases/org/glassfish/jaxb/jaxb-bom/${jaxb.version}/jaxb-bom-${jaxb.version}.pom (Illegal character in path at index 84: https://oss.sonatype.org/content/repositories/releases/org/glassfish/jaxb/jaxb-bom/${jaxb.version}/jaxb-bom-${jaxb.version}.pom) while downloading https://oss.sonatype.org/content/repositories/releases/org/glassfish/jaxb/jaxb-bom/${jaxb.version}/jaxb-bom-${jaxb.version}.pom

```

I don't know enough about maven to say if the problem is in the (generated?) pom.xml file, or if mill should be able to resolve this.

Making my project directly depend on the latest version of `org.glassfish.jaxb / jaxb.com` (which is fetched succesfully) does not solve the problem as it will still try to fetch `${jaxb.version}`.

**Comment by alexarchambault** [comment]
That seems to be an issue with coursier. I opened https://github.com/coursier/coursier/issues/1503 for it, I have a fix underway.

**Comment by lihaoyi** [comment]
@alexarchambault I assume we can close this now? Since the upstream fix landed a while back and we've been using recent versions of coursier
