### ISSUE TITLE
mill.contrib.Bloop/install generates invalid dotty configuration

### ISSUE THREAD

**Issue by heksesang** [com-lihaoyi/mill#784]
The scala configuration in the project files generated by `mill mill.contrib.Bloop/install` is invalid when `dotty-compiler` is being used instead of `scala-compiler`.

This is caused by the fact that `BloopImpl` generates a `BloopConfig.Scala` instance with `organization = "org.scala-lang"` regardless of version, while Bloop requires `organization = "ch.epfl.lamp"` to look for `dotty-compiler`:
```
def isDotty: Boolean = organization == "ch.epfl.lamp" && version.startsWith("0.")
```

As a result, Bloop fails to load the projects because it expects `scala-compiler` to exist in the projects where `dotty-compiler` is provided instead.

**Comment by lolgab** [comment]
I'm closing this since now Dotty from `ch.epfl.lamp` is not relevant anymore. All the development has moved to `org.scala-lang` which is correctly supported.
