### ISSUE TITLE
ScalaPB module should support `ZIO` code generation

### ISSUE THREAD

**Issue by DamianReeves** [com-lihaoyi/mill#789]
ScalaPB now allows `ZIO` code gen along with downloading artifacts from Maven as seen here:

https://scalapb.github.io/scalapbc.html#loading-additional-generators-from-maven

**Comment by DanielBlanco** [comment]
@lefou are you working on this? I want to create a [zio-grpc](https://github.com/scalapb/zio-grpc) service for a personal project and I'm using mill so having this ready would be great.

If not, I think I can try to extend [ScalaPBWorker](https://github.com/DamianReeves/mill/blob/master/contrib/scalapblib/src/ScalaPBWorker.scala) and add the ZIO-grpc stuff but I will appreciate any tips you can give me to get it started.

**Comment by lefou** [comment]
@DanielBlanco Great, and welcome! I've not planned to work on it in near future. @DamianReeves already started pull request #789 which is a good starting point to try out and experiment. If you have questions, best is to ask in the mill channel on Gitter. Or just ping me there.

**Comment by DanielBlanco** [comment]
Opened this PR https://github.com/lihaoyi/mill/pull/1002 @lefou maybe you can look at it and give me your thoughts.

**Comment by lihaoyi** [comment]
I guess we can close this since the linked PR is merged?
