### ISSUE TITLE
Feature request: Run external modules directly from their ivy resource

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#793]
Currently, to run external modules such like `BSP` it is necessary to modify the `build.sc` and add the dependency to it (`ivy'group:artifact:version'`). 

It would be cool, if we could run them directly from the command line, without the need to modify the `build.sc`.

**Comment by lihaoyi** [comment]
yeah that would be pretty cool, not sure how it would look but we could probably make it work somehow

**Comment by lefou** [comment]
Isn't it almost the same as simulating a custom predef or some code (`-c`) directly?

```
mill ivy com.lihaoyi::mill-contrib-bsp:_ mill.contrib.BSP/install
```

The underscope `_` could be a placeholder for the exact mill version.

**Comment by lihaoyi** [comment]
@lefou we can close this one right?

**Comment by lefou** [comment]
Oh yeah. Implemented by https://github.com/com-lihaoyi/mill/pull/1526.

**Comment by lefou** [comment]
> Isn't it almost the same as simulating a custom predef or some code (`-c`) directly?
> 
> ```
> mill ivy com.lihaoyi::mill-contrib-bsp:_ mill.contrib.BSP/install
> ```
> 
> The underscore `_` could be a placeholder for the exact mill version. Or just leave it out, when version should be identical to mills version.

Beside the fact, that the BSP contrib module no longer exists (it's built-in now), with mill 0.10.0-M4, it would look like this:

```
mill --import ivy:com.lihaoyi::mill-contrib-bsp: mill.contrib.BSP/install.

See also https://com-lihaoyi.github.io/mill/mill/Contrib_Plugins.html#_bloop
```
