### ISSUE TITLE
Running `mill` in source directory causes subsequent tasks to fail

### ISSUE THREAD

**Issue by yilinwei** [com-lihaoyi/mill#823]
Reproduction can be found [here](https://github.com/yilinwei/mill-issue-reproduction).

I've not tested on a different computer or OS.

**Comment by lefou** [comment]
Thanks for reporting and providing a reproduction.

After a first glace, I think it's because mill creates a socket file under `out/mill-worker-*/io`, which is not readable as a source file.

**Comment by tfenne** [comment]
I just got caught out by this.  Accidentally ran mill deep down in a source directory, then spent 10-15 minutes trying to figure out why mill was generating such a cryptic error before stumbling on this issue.  Putting my stack trace here so it's easier for others to find when searching issues:

```
$ mill _.test
[32/55] tools.test.sources
1 targets failed
tools.test.sources java.nio.file.FileSystemException: [...]/src/test/scala/com/[...]/out/mill-worker-BzhyNALGB6i84adFWul54iUnoFc=-1/io: Operation not supported on socket
```

**Comment by lefou** [comment]
I'm not sure what the best approach is to solve this issue. Maybe we should filter out socket files when searching for source files? Or vice versa, explicitly only collect "real" files?

**Comment by lefou** [comment]
Yeah, exiting mill with a good message in case a `build.sc` is missing is a good idea.

**Comment by timshen24** [comment]
HelloWorld.sources java.nio.file.FileSystemException: /Users/.../MillTest1/HelloWorld/src/main/scala/hello/out/mill-worker-dRTtqvVZYalRvhruw0ZliMCsBnA=-1/io: Operation not supported on socket
    java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
    java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
    java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
    java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
    java.base/java.nio.file.Files.newByteChannel(Files.java:371)
    java.base/java.nio.file.Files.newByteChannel(Files.java:422)
    java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
    java.base/java.nio.file.Files.newInputStream(Files.java:156)
    os.Path.getInputStream(Path.scala:475)
    os.read$inputStream$.apply(ReadWriteOps.scala:229)
    mill.api.PathRef$.$anonfun$apply$2(PathRef.scala:47)
    mill.api.PathRef$.$anonfun$apply$2$adapted(PathRef.scala:37)
    scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
    scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
    scala.collection.AbstractIterable.foreach(Iterable.scala:919)
    scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:889)
    mill.api.PathRef$.apply(PathRef.scala:37)
    mill.scalalib.JavaModule.$anonfun$sources$4(JavaModule.scala:204)
    mill.api.Result$Success.map(Result.scala:28)
    mill.api.Result$Success.map(Result.scala:27)
    mill.scalalib.JavaModule.$anonfun$sources$2(JavaModule.scala:204)
    mill.define.Applicative$Applyer.$anonfun$zipMap$1(Applicative.scala:35)
    mill.define.Task$MappedDest.evaluate(Task.scala:396)

I encountered the same problem, can anyone help me?
