### ISSUE TITLE
Custom Ivy repo makes GenIdea throw NoSuchFileException

### ISSUE THREAD

**Issue by joan38** [com-lihaoyi/mill#831]
Given:
```
interp.repositories() = List(
  IvyRepository.of(
    "https://artifacts.netflix.com/nfrepo-everything/[orgPath]/[module]/[revision]/[artifact]-[revision](-[classifier]).[ext]",
    "https://artifacts.netflix.com/nfrepo-everything/[orgPath]/[module]/[revision]/[module]-[revision]-ivy.[ext]"
  )
)
```
I get:
```
> mill mill.scalalib.GenIdea/idea
[1/1] mill.scalalib.GenIdea.idea 
Analyzing modules ...
[157/159] batch.test.ideaConfigFiles 
1 targets failed
mill.scalalib.GenIdea.idea java.nio.file.NoSuchFileException: /Users/jgoyeau/Library/Caches/Coursier/v1/https/artifacts.netflix.com/nfrepo-everything/netflix/com/google/protobuf/protobuf-java-nflx/3.7.2/protobuf-java-nflx-3.7.2.pom
    java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
    java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
    java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
    java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
    java.base/java.nio.file.Files.newByteChannel(Files.java:374)
    java.base/java.nio.file.Files.newByteChannel(Files.java:425)
    java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
    java.base/java.nio.file.Files.newInputStream(Files.java:159)
    os.Path.getInputStream(Path.scala:474)
    os.read$bytes$.apply(ReadWriteOps.scala:258)
    os.read$.apply(ReadWriteOps.scala:218)
    os.read$.apply(ReadWriteOps.scala:216)
    mill.scalalib.GenIdeaImpl.sbtLibraryNameFromPom$1(GenIdeaImpl.scala:278)
    mill.scalalib.GenIdeaImpl.libraryNames$1(GenIdeaImpl.scala:291)
    mill.scalalib.GenIdeaImpl.$anonfun$xmlFileLayout$84(GenIdeaImpl.scala:327)
    scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:244)
    scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:321)
    scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:977)
    scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:977)
    scala.collection.TraversableLike.flatMap(TraversableLike.scala:244)
    scala.collection.TraversableLike.flatMap$(TraversableLike.scala:241)
    scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
    mill.scalalib.GenIdeaImpl.xmlFileLayout(GenIdeaImpl.scala:327)
    mill.scalalib.GenIdeaImpl.run(GenIdeaImpl.scala:37)
    mill.scalalib.GenIdea$.$anonfun$idea$2(GenIdea.scala:14)
    scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
```
The pom file is indeed not here because it's an Ivy dependency.

Thanks

**Comment by lefou** [comment]
Is this still relevant?

**Comment by mtk** [comment]
i'm not sure if this is related but both './mill mill.scalalib.GenIdea/idea' and './mill mill.contrib.Bloop/install' have failed consistently for a couple of weeks on VirtusLab/scala-cli.  the error is similar but different.  i git bisect'ed it and the bad commit is e1141059 (the last good one is ced5e0db).  the only significant change was to build.sc but the changes looked harmless to me (although my mill-fu is very weak).  thoughts/comments?

**Comment by mtk** [comment]
the error in my case was:

1 targets failed
mill.scalalib.GenIdea.idea Failure during resolving modules: integration.modulesPath java.nio.file.FileSystemException: /home/mtk/proj/scala-cli/scala-cli/out/mill-worker-i1zQnaJa0KooD/A5m29nsZSuV80=-1/mill-6458df6e56df4169ed534376d918dc24-io: No such device or address

**Comment by lefou** [comment]
> i'm not sure if this is related but both './mill mill.scalalib.GenIdea/idea' and './mill mill.contrib.Bloop/install' have failed consistently for a couple of weeks on VirtusLab/scala-cli. the error is similar but different. i git bisect'ed it and the bad commit is e1141059 (the last good one is ced5e0db). the only significant change was to build.sc but the changes looked harmless to me (although my mill-fu is very weak). thoughts/comments?

If you can post the full git hash, GitHub will make a link to the commit. :-)

**Comment by mtk** [comment]
good: https://github.com/VirtusLab/scala-cli/commit/e11410595592ee1787512a515662f552ae586868

bad: https://github.com/VirtusLab/scala-cli/commit/ced5e0dbbb820fc17d4d30772a3c305573018cfd

**Comment by lefou** [comment]
This doesn't look related to me. Other error message, other change, seems not related to the use of an ivy repo. 

@mtk I had a quick glance at your changes, but I couldn't detect anything suspicious. GenIdea/idea and Bloop/install are typically triggering targets which are needed to build the project. Does your project build and run tests without issues on the CLI? 

I'm closing this issue, as I think the original issue is already fixed.
