### ISSUE TITLE
BSP protocol: support for context-applied plugin

### ISSUE THREAD

**Issue by psisoyev** [com-lihaoyi/mill#847]
It seems that the current implementation of BSP protocol server does not support context-applied plugin in IntelliJ. 

I have built 2 projects for demonstration purpose:
https://github.com/psisoyev/mill-test
https://github.com/psisoyev/sbt-test

They are absolutely identical, just one uses SBT and another uses Mill. If they are imported as BSP projects, in Mill project you won't have auto-completion in the code (plus it will make `F` red). You can find behavior screenshots in the root folders of both projects.

**Comment by lefou** [comment]
In Mill 0.10.0, scalac plugins should work using BSP. Can you please retry?

**Comment by lihaoyi** [comment]
This seems to work now with 0.11.12

<img width="860" alt="Screenshot 2024-10-18 at 9 01 02 AM" src="https://github.com/user-attachments/assets/3d5f4b5f-408a-43b0-818b-64f37b5221f7">
