### ISSUE TITLE
BSP: Import build related deps for IDE support in build.sc files

### ISSUE THREAD

**Issue by joan38** [com-lihaoyi/mill#863]
It seems with BSP that `build.sc` and other `.sc` files are all red because we don't import the mill library and other `$ivy` dependencies.
Would be cool to support that too.

Thanks

**Comment by joan38** [comment]
This is partially fixed in 0.7.2
We are only missing the `$file` imports

**Comment by joan38** [comment]
I found out that the `$file` imports are supported in the current GenIdea through enabling the sc files support with `<option name="scFileMode" value="Ammonite" />`. I don't know how to enable this with BSP. But the change will happen on the Intellij codebase. It should automatically enable the Ammonite support as soon as it sees a `build.sc`

**Comment by lefou** [comment]
> Until this is fixed I don't think the docs should call GenIdea legacy

I agree. Right now `GenIdea` is better maintained than BSP. Although I have some ideas and also prototypes for BSP improvements, nothing is ready to use. So yes, please go ahead and update the docs.

**Comment by lefou** [comment]
Fixed for a while, but I can't say in which version.
