### ISSUE TITLE
Double inclusion of scala-library in bloop config breaks Metals

### ISSUE THREAD

**Issue by heksesang** [com-lihaoyi/mill#901]
Including both `scala-library-2.13.1.jar` and `scala-library-0.23.0.jar` seems to break Metals support.

See https://github.com/scalameta/metals/issues/1768.

**Comment by tgodzik** [comment]
This is connected to the config for Bloop being generated by Mill. It adds `scala-library-0.23.0.jar `, which breaks the compilation for Bloop. This most likely shouldn't be an issue, since that jar exists, but I think it would be better not to include it for Dotty.

**Comment by lefou** [comment]
Fixed by https://github.com/com-lihaoyi/mill/pull/915
