### ISSUE TITLE
Corrupt stdout when using 'run'

### ISSUE THREAD

**Issue by nornagon** [com-lihaoyi/mill#903]
<img width="573" alt="" src="https://user-images.githubusercontent.com/172800/82742579-08754a80-9d15-11ea-9c9f-1999c519df7e.png">

When running with `mill foo.run` I'm sometimes seeing what looks like corrupt output from stdout. I don't observe the same behavior when running with `mill -i`.

Mill version 0.7.0, running on macOS 10.14.6.

**Comment by devlynns** [comment]
> <img alt="" width="573" src="https://user-images.githubusercontent.com/172800/82742579-08754a80-9d15-11ea-9c9f-1999c519df7e.png">
> 
> When running with `mill foo.run` I'm sometimes seeing what looks like corrupt output from stdout. I don't observe the same behavior when running with `mill -i`.
> 
> Mill version 0.7.0, running on macOS 10.14.6.

**Comment by nornagon** [comment]
NB this is still an issue with Mill version 0.10.8 on macOS 12.6.

**Comment by lefou** [comment]
If the interleaving streams both result from Mill (and are not direct output of external processes), chances are high we fixed it in the main branch, which will become Mill 0.11.0-M9.

**Comment by lihaoyi** [comment]
Since 0.11.x is out, which we think fixes this, let's close this for now. We can re-open it if the issue persists
