### ISSUE TITLE
--bell does not make sound when combined with --jobs <n> and --watch unless in --interactive mode

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#908]
It's kind of weird that such a specific combination of flags would cause an issue, but it is. Haven't investigated why

**Comment by lefou** [comment]
My guess is, this now works, as we improved the interactive behavior even in server mode, and we also changed the way `--watch` works. Additional we now also make sure we don't loose any output and `--bell` is using the output stream, technically. I think it's worth a re-test.

**Comment by lihaoyi** [comment]
Yeah going to call this probably fixed for now, can repoen if necessary
