### ISSUE TITLE
toolsClasspath from ScalaJSModule and ScoverageModule conflict

### ISSUE THREAD

**Issue by fabianhjr** [com-lihaoyi/mill#916]
These are the conflicting definitions:

https://github.com/lihaoyi/mill/blob/3f1f1856c7d9af1e8d269d9dd80a2a8cf0f5f243/scalajslib/src/ScalaJSModule.scala#L75

https://github.com/lihaoyi/mill/blob/3f1f1856c7d9af1e8d269d9dd80a2a8cf0f5f243/contrib/scoverage/src/ScoverageModule.scala#L67

Would an appropriate solution be to create an empty `toolsClasspath` target on `ScalaModule` and transform those conflicting defs to overrides adding on the `ScalaModule` `toolsClasspath` target?

**Comment by lefou** [comment]
No. There is no easy solution, as each `toolsClasspath` target is used for different purposes. I'M going to rename these targets in mill 0.10.0-M2. There is no easy way to work around. You need to inherit both traits (`ScalaJSModule` and `ScoverageModule`) separately and re-implement the toolsClasspath targets to refer to other targets with unequal names.
