### ISSUE TITLE
Manual installation instructions on website need a little work

### ISSUE THREAD

**Issue by readyready15728** [com-lihaoyi/mill#919]
The suggested code:

```
sudo curl -L https://github.com/lihaoyi/mill/releases/download/0.7.3/0.7.3 > /usr/local/bin/mill && sudo chmod +x /usr/local/bin/mill
```

...doesn't work. This is because elevation of permissions from `sudo` doesn't apply to shell redirection. The following works just fine however:

```
curl -L https://github.com/lihaoyi/mill/releases/download/0.7.3/0.7.3 2> /dev/null | sudo tee /usr/local/bin/mill > /dev/null && sudo chmod +x /usr/local/bin/mill
```

**Comment by lihaoyi** [comment]
It appears we no longer recommend installing it in somewhere that needs `sudo`

![Uploading Screenshot 2023-04-23 at 9.48.36 AM.png…]()
