### ISSUE TITLE
mill mill.scalalib.GenIdea/idea should report problems

### ISSUE THREAD

**Issue by axaluss** [com-lihaoyi/mill#950]
`mill mill.scalalib.GenIdea/idea` does not report any problems. 
Errors are just silently swallowed and projects are not getting generated.

Errors and warnings need to be logged to tell the user what's wrong.

**Comment by lefou** [comment]
Can you give an example or a project to reproduce the errors?

**Comment by axaluss** [comment]
I currently can't reproduce.
I remember when debugging that it probably was related to `mill-scalalib_2.13/0.8.0/mill-scalalib_2.13-0.8.0-sources.jar!/GenIdeaImpl.scala:208` 

`val resolved = evalOrElse(evaluator, T.sequence(resolveTasks), Seq())`

Ah I found a todo: 
`GenIdeaImpl.scala:181`
`// TODO: make this a separate eval to handle resolve errors`
