### ISSUE TITLE
Mill config file concept (RFC)

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#954]
Some settings are relevant for mill but can not be controlled via the `build.sc`. Thus these should be placed into a config file.

I think we should have only one config file which holds all various settings, that are needed to control mills behavior. In contrast to having multiple files which would clutter the directories. As such a single config file need to serve multiple entry points (e.g. the mill executable (JVM), the various start scripts (shell script), metals, IDEs) we should choose a very simple file format, which does not require any sophisticated parsing. I think some property file style without any logic should serve that purpose very well. We should also migrate and deprecate other supported config files like `.mill-version` after that. 

These config files should be project specific as well as user specific, so we need to look for it in the project directory (highest priority) as well as in the user config directory (fallback).

The following settings are suspected to be configurable:

* JVM settings
** JVM client settings (memory, stack, ...) for mill client
** JVM server settings (memory, stack, ...) for mill server
* mill version (replaces `.mill-version`)
* mill default settings (job count, colors (#471), verbose, no-server)

We need a good name for it, my candidates are:
* `.millrc` - this is very Unix/Linux style, I'm used to it but don't know if some users expect some specific format
* `.mill.conf` - this is probably the clearest choice
* `.mill.properties` - this implies JVM properties files in ISO 8859-1 format, where I would prefer UTF-8 content

Example:

```conf
# comments start with a # and will be ignored
mill.version=0.8.0
mill.jobs=0
mill.server.jvm.opts=-Xms2g -Xmx2g -Xss4m -XX:ReservedCodeCacheSize=512m -XX:MaxMetaspaceSize=512m
mill.client.jvm.opts= 
```

What do you think?

**Comment by lihaoyi** [comment]
This seems like a good idea to me

**Comment by lefou** [comment]
We might also consider the following addition settings:
* proxy settings
* Ivy/Maven/Coursier repository settings
* Environment variables

**Comment by joan38** [comment]
+1 for `.mill.conf`

**Comment by Ichoran** [comment]
Why can't these things be controlled via build.sc?  If you can't do it with normal syntax, add a special header.

/*!! mill.conf {
  "mill.version" = "0.8.0",
 "mill.server.jvm.opts" = [
    "-Xms2g", "-Xmx2g", "-Xss4m",
    "-XX:ReservedCodeCacheSize=512m",
    "-XX:MaxMetaspaceSize=512m"
  ],
  "mill.client.jvm.opts" = []
} !!*/

(Or use the variant you showed above instead of JSON.)

**Comment by lefou** [comment]
It could, but the effort to parse it somehow from the `*.sc` file will be far from trivial, especially for a small shell script, which needs to decide which version of mill to download. Also you have to ensure no editor ever messes up with that comment. We should keep things simple, if possible.

**Comment by Ichoran** [comment]
That isn't hard if you make the start and stop lines really easy to match.  And whatever parses the build.sc can throw an error if they're malformed (if it will even run at all).

See several solutions at https://stackoverflow.com/questions/4857424/extract-lines-between-2-tokens-in-a-text-file-using-bash

**Comment by joan38** [comment]
I found out the we currently have `.mill-jvm-opts` and want to document that here so that we eventually merge that in the new config system.

**Comment by kag0** [comment]
Seems like a good idea to me. 

One detail that occurs to me is that it might be awkward to have mill server options configurable at the project level. We could a) have those settings only available at the user level or b) restart the server every time the project changes (this does happen already for mill version changes I think).

**Comment by lefou** [comment]
Experience has shown, that you always need some kind of project-specific environment settings for your tool chain. Each project has different needs, e.g. memory settings. The JVM defaults highly depend on the user environment like OS, count of CPU cores, RAM, and so on. Project-specific version-controlled settings ensure a reproducible setup for team members, CI systems and your future self. The mill server is the component which holds the various tools in caches, so it's the mill server runtime settings which determine the available memory for your compiler.
