### ISSUE TITLE
Piggyback on ammonite's BSP implementation for build files 

### ISSUE THREAD

**Issue by Baccata** [com-lihaoyi/mill#971]
The BSP implementation (which allows editors to talk to mill when the user edits module files) is becoming [first-class-citizen in mill](https://github.com/lihaoyi/mill/pull/969), it'd be interesting to piggyback on ammonite's BSP implementation for `build.sc`, to get all the autocompletion/navigation features metals users would like to have when editing mill build files. 

#### A few possibly relevant details 

Mill's entrypoint that ties it to ammonite is [there](https://github.com/lihaoyi/mill/blob/ef71368bbd4f71ba3f22ac3da51533bacda3b197/main/src/main/RunScript.scala#L26). This method outputs a "Evaluator", which is a construct that is aware of the build-graph and able to evaluate mill-tasks. It is is used [by the BSP implementation](https://github.com/lihaoyi/mill/blob/master/contrib/bsp/src/mill/contrib/bsp/MillBuildServer.scala#L21). The evaluator potentially be accompanied by the information required by ammonite's bsp, in order to enrich mill's bsp for build-files. 

One essential thing, specific to mill, that differs from ammonite is the [codeWrapper]( https://github.com/lihaoyi/mill/blob/c9f8badca307d2c271c5fafa677de648193ba3d7/main/src/main/MainRunner.scala#L162), which would have to be communicated to the ammonite's bsp somehow. The classpath is also obviously different. 

@alexarchambault 👋 , could I ask you for a brain-dump when you have time, on how such an integration would be possible ?

**Comment by lefou** [comment]
This is likely superseded by 

* https://github.com/com-lihaoyi/mill/issues/1675
* https://github.com/com-lihaoyi/mill/issues/1972
