### ISSUE TITLE
[BSP] - Support for `workspace/reload`

### ISSUE THREAD

**Issue by ckipp01** [com-lihaoyi/mill#986]
### Feature Request

A part of the BSP spec that doesn't seem to be implemented yet in the Mill BSP is support is the  [`workspace/reload`](https://build-server-protocol.github.io/docs/specification.html#reload-request) request. This is useful for editors like Metals so when the user edits their build file, we can detect it and send a reload request for the server.

**Comment by lefou** [comment]
I'm not sure, we can implement it in the current design, asthe whole BSP server is implemented as an opaque mill command. Mill very well supports reloading (with it's `--watch` feature), in fact it will detect the need for it in most cases automatically, but only after the command execution finished. So, IMHO, a proper implementation of BSP `workspace/reload` might be to just finish the `BSP/start` target. But if we run mill with `--watch`, be might see unexpected output in between, also stopping the `BSP/start` target might be a bit harder. But without `--watch` I don't know if a BSP client is expected to handle a stop of the server that gracefully, e.g. just restart it. If not, we probably need something in between mill invokations without `--watch` and with `--watch`. Or we might come up with a dedicated start option / entry point in mill.

**Comment by ckipp01** [comment]
> So, IMHO, a proper implementation of BSP `workspace/reload` might be to just finish the BSP/start target

I'm not extremely familiar with all the mill terms, so my apologies if I get some of the lingo wrong. But in this case, by _finish the BSP/start target_ mean terminating the BSP connection?

> But if we run mill with --watch, be might see unexpected output in between

Depending on what you mean by _unexpected output_ here it's important to remember that all the communication during the connect _must_ be able to be parsed as JSON-RPC, if not you run into all sorts of issues. This happened with [sbt here](https://github.com/sbt/sbt/issues/5993), and it caused the server not work correctly with neither IntelliJ or Metals with certain versions. Again, it depends on what you mean by output here, but just make sure any weird output isn't piped into the actual BSP communication that isn't part of the spec.

>  But without --watch I don't know if a BSP client is expected to handle a stop of the server that gracefully, e.g. just restart it

Well the client will handle the lifecyle of the the connect, and end with a request to shutdown and then exit [as outlined here](https://build-server-protocol.github.io/docs/specification.html#shutdown-build-request). As for a restart, not really part of the BSP spec, but in the Metals case we have a `build-restart` command that we expose that a LSP client can trigger to shutdown and restart a BSP connection. However, I wouldn't use this as an alternative to `workspace/reload`.

Mainly, I think it's helpful to think of it in terms of flow of how it will be used with a client. Again from a Metals perspective I'll outline what we'd like to ideally have happen.

1. BSP connection made with whatever is in `.bsp/mill.json`
2. User edits the `build.sc`
3. Metals recognizes that the build definition has changed and then triggers a `workspace/reload`
4. User just keeps on editing like normal

I think however Mill implements stage 3 it's just important (if possible) to not rely on any special logic in the client specific to Mill, but simply stay inline with the spec. That's probably easier said than done, but it makes it was easier for clients to deal with various BSP servers.

**Comment by lefou** [comment]
Thanks for your comment. As an outcome, I think we should not implement our BSP support as a `T.command`. To better control the lifecycle we might provide a dedicated entry-point (or cmdline option).

**Comment by srdo** [comment]
I think that's a good idea. That will also allow us to better control what goes on stdout, since as a Command, there will be some time where Mill might log to stdout before reaching the BSP code (e.g. `Compiling build.sc`)

**Comment by lefou** [comment]
I started a draft pull request: #1093
